// Property of Bricsys NV. All rights reserved.
// This file is part of the BRX SDK, and its use is subject to the terms
// of the BRX SDK license agreement.
/////////////////////////////////////////////////////////////////////////

#undef ALIAS_LIST
#define ALIAS_LIST()\
ON_ALIAS(IfcAbsorbedDoseMeasure)\
ON_ALIAS(IfcAccelerationMeasure)\
ON_ALIAS(IfcAmountOfSubstanceMeasure)\
ON_ALIAS(IfcAngularVelocityMeasure)\
ON_ALIAS(IfcArcIndex)\
ON_ALIAS(IfcAreaDensityMeasure)\
ON_ALIAS(IfcAreaMeasure)\
ON_ALIAS(IfcBinary)\
ON_ALIAS(IfcBoolean)\
ON_ALIAS(IfcComplexNumber)\
ON_ALIAS(IfcCompoundPlaneAngleMeasure)\
ON_ALIAS(IfcContextDependentMeasure)\
ON_ALIAS(IfcCountMeasure)\
ON_ALIAS(IfcCurvatureMeasure)\
ON_ALIAS(IfcDate)\
ON_ALIAS(IfcDateTime)\
ON_ALIAS(IfcDescriptiveMeasure)\
ON_ALIAS(IfcDoseEquivalentMeasure)\
ON_ALIAS(IfcDuration)\
ON_ALIAS(IfcDynamicViscosityMeasure)\
ON_ALIAS(IfcElectricCapacitanceMeasure)\
ON_ALIAS(IfcElectricChargeMeasure)\
ON_ALIAS(IfcElectricConductanceMeasure)\
ON_ALIAS(IfcElectricCurrentMeasure)\
ON_ALIAS(IfcElectricResistanceMeasure)\
ON_ALIAS(IfcElectricVoltageMeasure)\
ON_ALIAS(IfcEnergyMeasure)\
ON_ALIAS(IfcForceMeasure)\
ON_ALIAS(IfcFrequencyMeasure)\
ON_ALIAS(IfcHeatFluxDensityMeasure)\
ON_ALIAS(IfcHeatingValueMeasure)\
ON_ALIAS(IfcIdentifier)\
ON_ALIAS(IfcIlluminanceMeasure)\
ON_ALIAS(IfcInductanceMeasure)\
ON_ALIAS(IfcInteger)\
ON_ALIAS(IfcIntegerCountRateMeasure)\
ON_ALIAS(IfcIonConcentrationMeasure)\
ON_ALIAS(IfcIsothermalMoistureCapacityMeasure)\
ON_ALIAS(IfcKinematicViscosityMeasure)\
ON_ALIAS(IfcLabel)\
ON_ALIAS(IfcLengthMeasure)\
ON_ALIAS(IfcLineIndex)\
ON_ALIAS(IfcLinearForceMeasure)\
ON_ALIAS(IfcLinearMomentMeasure)\
ON_ALIAS(IfcLinearStiffnessMeasure)\
ON_ALIAS(IfcLinearVelocityMeasure)\
ON_ALIAS(IfcLogical)\
ON_ALIAS(IfcLuminousFluxMeasure)\
ON_ALIAS(IfcLuminousIntensityDistributionMeasure)\
ON_ALIAS(IfcLuminousIntensityMeasure)\
ON_ALIAS(IfcMagneticFluxDensityMeasure)\
ON_ALIAS(IfcMagneticFluxMeasure)\
ON_ALIAS(IfcMassDensityMeasure)\
ON_ALIAS(IfcMassFlowRateMeasure)\
ON_ALIAS(IfcMassMeasure)\
ON_ALIAS(IfcMassPerLengthMeasure)\
ON_ALIAS(IfcModulusOfElasticityMeasure)\
ON_ALIAS(IfcModulusOfLinearSubgradeReactionMeasure)\
ON_ALIAS(IfcModulusOfRotationalSubgradeReactionMeasure)\
ON_ALIAS(IfcModulusOfSubgradeReactionMeasure)\
ON_ALIAS(IfcMoistureDiffusivityMeasure)\
ON_ALIAS(IfcMolecularWeightMeasure)\
ON_ALIAS(IfcMomentOfInertiaMeasure)\
ON_ALIAS(IfcMonetaryMeasure)\
ON_ALIAS(IfcNonNegativeLengthMeasure)\
ON_ALIAS(IfcNormalisedRatioMeasure)\
ON_ALIAS(IfcNullStyle)\
ON_ALIAS(IfcNumericMeasure)\
ON_ALIAS(IfcPHMeasure)\
ON_ALIAS(IfcParameterValue)\
ON_ALIAS(IfcPlanarForceMeasure)\
ON_ALIAS(IfcPlaneAngleMeasure)\
ON_ALIAS(IfcPositiveInteger)\
ON_ALIAS(IfcPositiveLengthMeasure)\
ON_ALIAS(IfcPositivePlaneAngleMeasure)\
ON_ALIAS(IfcPositiveRatioMeasure)\
ON_ALIAS(IfcPowerMeasure)\
ON_ALIAS(IfcPressureMeasure)\
ON_ALIAS(IfcPropertySetDefinitionSet)\
ON_ALIAS(IfcRadioActivityMeasure)\
ON_ALIAS(IfcRatioMeasure)\
ON_ALIAS(IfcReal)\
ON_ALIAS(IfcRotationalFrequencyMeasure)\
ON_ALIAS(IfcRotationalMassMeasure)\
ON_ALIAS(IfcRotationalStiffnessMeasure)\
ON_ALIAS(IfcSectionModulusMeasure)\
ON_ALIAS(IfcSectionalAreaIntegralMeasure)\
ON_ALIAS(IfcShearModulusMeasure)\
ON_ALIAS(IfcSolidAngleMeasure)\
ON_ALIAS(IfcSoundPowerLevelMeasure)\
ON_ALIAS(IfcSoundPowerMeasure)\
ON_ALIAS(IfcSoundPressureLevelMeasure)\
ON_ALIAS(IfcSoundPressureMeasure)\
ON_ALIAS(IfcSpecificHeatCapacityMeasure)\
ON_ALIAS(IfcSpecularExponent)\
ON_ALIAS(IfcSpecularRoughness)\
ON_ALIAS(IfcTemperatureGradientMeasure)\
ON_ALIAS(IfcTemperatureRateOfChangeMeasure)\
ON_ALIAS(IfcText)\
ON_ALIAS(IfcThermalAdmittanceMeasure)\
ON_ALIAS(IfcThermalConductivityMeasure)\
ON_ALIAS(IfcThermalExpansionCoefficientMeasure)\
ON_ALIAS(IfcThermalResistanceMeasure)\
ON_ALIAS(IfcThermalTransmittanceMeasure)\
ON_ALIAS(IfcThermodynamicTemperatureMeasure)\
ON_ALIAS(IfcTime)\
ON_ALIAS(IfcTimeMeasure)\
ON_ALIAS(IfcTimeStamp)\
ON_ALIAS(IfcTorqueMeasure)\
ON_ALIAS(IfcVaporPermeabilityMeasure)\
ON_ALIAS(IfcVolumeMeasure)\
ON_ALIAS(IfcVolumetricFlowRateMeasure)\
ON_ALIAS(IfcWarpingConstantMeasure)\
ON_ALIAS(IfcWarpingMomentMeasure)\

