[build]
target = "index.html" # The index HTML file to drive the bundling process.
release = false       # Build in release mode.
dist = "src/dist"     # The output dir for all final assets.
public_url = "/"      # The public URL from which assets are to be served.
filehash = true       # Whether to include hash values in the output file names.
inject_scripts = true # Whether to inject scripts (and module preloads) into the finalized output.
offline = false       # Run without network access
frozen = false        # Require Cargo.lock and cache are up to date
locked = false        # Require Cargo.lock is up to date
minify = "on_release" # Control minification: can be one of: never, on_release, always
no_sri = false        # Allow disabling sub-resource integrity (SRI)

# [serve]
# addresses = ["127.0.0.1"]                    # The address to serve on.
# port = 8080                                  # The port to serve on.
# aliases = ["http://localhost.mywebsite.com"] # The aliases to serve on.
# open = false                                 # Open a browser tab once the initial build is complete.
# no_spa = false                               # Whether to disable fallback to index.html for missing files.
# no_autoreload = false                        # Disable auto-reload of the web app.
# no_error_reporting = false                   # Disable error reporting
# ws_protocol = "ws"                           # Protocol used for autoreload WebSockets connection.
# # Additional headers set for responses.
# headers = { "test-header" = "header value", "test-header2" = "header value 2" }
# # The certificate/private key pair to use for TLS, which is enabled if both are set.
# tls_key_path = "self_signed_certs/key.pem"
# tls_cert_path = "self_signed_certs/cert.pem"
