// Copyright (C) Menhirs NV. All rights reserved.
#pragma once

#ifdef _DBX_HOST_APPLICATION_
#error ObjectDBX Host Applications are not supported. If your project does not require this API, please undefine _DBX_HOST_APPLICATION_
#endif

#ifdef _WIN32
#pragma warning(disable:4312)
#endif

#include <windows.h>

#pragma pack(push, 8)

// Include's for C++
#if defined(__cplusplus)

//BRX START
//MFC (afx...) headers must be included before windows headers
//to avoid compile error C1189
#if defined(_AFXEXT) && defined(_WIN32) && defined(__cplusplus)
  #if defined(_DEBUG) && !defined(BRX_BCAD_DEBUG)
    #undef _DEBUG
    #include <afxcoll.h>
    #define _DEBUG
  #else
    #include <afxcoll.h>
  #endif
#endif
//BRX END

#include "brx_importexport.h"  // BRX_IMPORTEXPORT

#include "brx_platform_3264.h" // 32/64 bit detection
#include "Ac64BitHelpers.h"    // 32+64 bit tools (conversions etc.)

#include "Ads/AdsGlobal.h"     // ads_xxx data types

#include "AcAp/AcApProfileManager.h"
#include "AcAp/AcApProfileManagerReactor.h"
#include "AcAp/AcApProfileStorage.h"

#include "AcRx/AcRxObject.h"
#include "AcRx/AcRxService.h"
#include "AcRx/AcRxKernel.h"
#include "AcRx/AcRxIterator.h"
#include "AcRx/AcRxClass.h"
#include "AcRx/AcRxDbxApp.h"
#include "AcRx/AcRxDictionary.h"
#include "AcRx/AcRxEvent.h"
#include "AcRx/AcRxEventReactor.h"
//#include "AcRx/AcRxProtocolReactor.h"
#include "AcRx/AcRxDynamicLinker.h"
#include "AcRx/AcRxDLinkerReactor.h"
//#include "AcRx/AcRxProtocolReactorIterator.h"
//#include "AcRx/AcRxProtocolReactorList.h"
//#include "AcRx/AcRxProtocolReactorListIterator.h"
//#include "AcRx/AcRxProtocolReactorManager.h"
//#include "AcRx/AcRxProtocolReactorManagerFactory.h"

#include "AcTrans/AcTransaction.h"
#include "AcTrans/AcTransactionReactor.h"
#include "AcTrans/AcTransactionManager.h"

#include "AcDb/AcDbBoiler.h"
#include "AcDb/AcDbObjectId.h"
#include "AcDb/AcDbHostApplicationServices.h"
#include "AcDb/AcDbPolyline.h"
#include "AcDb/AcDb2dPolyline.h"
#include "AcDb/AcDb2dVertex.h"
#include "AcDb/AcDb2LineAngularDimension.h"
#include "AcDb/AcDb3dPolyline.h"
#include "AcDb/AcDb3dPolylineVertex.h"
#include "AcDb/AcDb3dSolid.h"
#include "AcDb/AcDb3PointAngularDimension.h"
#include "AcDb/AcDbAbbreviation.h"
#include "AcDb/AcDbAlignedDimension.h"
#include "AcDb/AcDbAlignment.h"
#include "AcDb/AcDbAnnoAlertDisabler.h"
#include "AcDb/AcDbAppSystemVariables.h"
#include "AcDb/AcDbArc.h"
#include "AcDb/AcDbArcDimension.h"
#include "AcDb/AcDbAttribute.h"
#include "AcDb/AcDbAttributeDefinition.h"
#include "AcDb/AcDbBlockBegin.h"
#include "AcDb/AcDbBlockChangeIterator.h"
#include "AcDb/AcDbBlockEnd.h"
#include "AcDb/AcDbBlockInsertionPoints.h"
#include "AcDb/AcDbBlockReferenceIdIterator.h"
#include "AcDb/AcDbBlockTableIterator.h"
#include "AcDb/AcDbBlockTableRecord.h"
#include "AcDb/AcDbBlockTableRecordIterator.h"
#include "AcDb/AcDbBody.h"
#include "AcDb/AcDbCircle.h"
#include "AcDb/AcDbClassIterator.h"
#include "AcDb/AcDbCompositeFilteredBlockIterator.h"
#include "AcDb/AcDbDataTable.h"
#include "AcDb/AcDbDate.h"
#include "AcDb/AcDbDiametricDimension.h"
#include "AcDb/AcDbDictionaryIterator.h"
#include "AcDb/AcDbDictionaryWithDefault.h"
#include "AcDb/AcDbDictUtil.h"
#include "AcDb/AcDbDimAssoc.h"
#include "AcDb/AcDbPointRef.h"
#include "AcDb/AcDbOsnapPointRef.h"
#include "AcDb/AcDbDimData.h"
#include "AcDb/AcDbDimStyleTableIterator.h"
#include "AcDb/AcDbDimStyleTableRecord.h"
//#include "AcDb/AcDbDwgFiler.h"
//#include "AcDb/AcDbDxfFiler.h"
#include "AcDb/AcDbDynBlockReference.h"
#include "AcDb/AcDbEllipse.h"
#include "AcDb/AcDbEntityHyperlinkPE.h"
#include "AcDb/AcDbEvalConnectable.h"
#include "AcDb/AcDbEvalContext.h"
#include "AcDb/AcDbEvalContextIterator.h"
#include "AcDb/AcDbEvalContextPair.h"
#include "AcDb/AcDbEvalEdgeInfo.h"
#include "AcDb/AcDbFace.h"
#include "AcDb/AcDbFaceRecord.h"
#include "AcDb/AcDbFcf.h"
#include "AcDb/AcDbField.h"
//#include "AcDb/AcDbFilter.h"
//#include "AcDb/AcDbFilteredBlockIterator.h"
#include "AcDb/AcDbGradientBackground.h"
#include "AcDb/AcDbGraphStack.h"
#include "AcDb/AcDbGripData.h"
#include "AcDb/AcDbGroundPlaneBackground.h"
#include "AcDb/AcDbGroup.h"
#include "AcDb/AcDbGroupIterator.h"
//#include "AcDb/AcDbHardOwnershipId.h"
//#include "AcDb/AcDbHardPointerId.h"
#include "AcDb/AcDbHatch.h"
#include "AcDb/AcDbHyperlinkCollection.h"
#include "AcDb/AcDbIdMappingIter.h"
#include "AcDb/AcDbImage.h"
#include "AcDb/AcDbImageBackground.h"
#include "AcDb/AcDbIndexFilterManager.h"
#include "AcDb/AcDbIndexUpdateDataIterator.h"
#include "AcDb/AcDbLayerTableRecord.h"
#include "AcDb/AcDbLayerTable.h"
#include "AcDb/AcDbLayerFilter.h"
#include "AcDb/AcDbLayerIndexIterator.h"
#include "AcDb/AcDbLayerStateManager.h"
#include "AcDb/AcDbLayerStateManagerReactor.h"
#include "AcDb/AcDbLayerTableIterator.h"
#include "AcDb/AcDbLayout.h"
#include "AcDb/AcDbLayoutManager.h"
#include "AcDb/AcDbLayoutManagerReactor.h"
#include "AcDb/AcDbLeader.h"
#include "AcDb/AcDbMLeaderStyle.h"
#include "AcDb/AcDbMLeader.h"
#include "AcDb/AcDbLine.h"
#include "AcDb/AcDbLinetypeTableIterator.h"
#include "AcDb/AcDbLinetypeTableRecord.h"
#include "AcDb/AcDbMaterial.h"
#include "AcDb/AcDbMInsertBlock.h"
#include "AcDb/AcDbMline.h"
#include "AcDb/AcDbMlineStyle.h"
#include "AcDb/AcDbObjectContext.h"
#include "AcDb/AcDbObjectContextCollection.h"
#include "AcDb/AcDbObjectContextManager.h"
#include "AcDb/AcDbObjectIdGraph.h"
#include "AcDb/AcDbObjectPointer.h"
#include "AcDb/AcDbOle2Frame.h"
#include "AcDb/AcDbOrdinateDimension.h"
#include "AcDb/AcDbPasswordedFile.h"
#include "AcDb/AcDbPlaceHolder.h"
#include "AcDb/AcDbPlotSettings.h"
#include "AcDb/AcDbPlotSettingsValidator.h"
#include "AcDb/AcDbPoint.h"
#include "AcDb/AcDbPolyFaceMesh.h"
#include "AcDb/AcDbPolyFaceMeshVertex.h"
#include "AcDb/AcDbPolygonMesh.h"
#include "AcDb/AcDbPolygonMeshVertex.h"
#include "AcDb/AcDbProxyObject.h"
#include "AcDb/AcDbProxyEntity.h"
#include "AcDb/AcDbR13ObjectId.h"
#include "AcDb/AcDbRadialDimension.h"
#include "AcDb/AcDbRadialDimensionLarge.h"
#include "AcDb/AcDbRasterImage.h"
#include "AcDb/AcDbRasterImageDefFileAccessReactor.h"
#include "AcDb/AcDbRasterImageDefTransReactor.h"
#include "AcDb/AcDbRasterVariables.h"
#include "AcDb/AcDbWipeout.h"
#include "AcDb/AcDbRay.h"
#include "AcDb/AcDbRegAppTableIterator.h"
#include "AcDb/AcDbRegAppTableRecord.h"
#include "AcDb/AcDbRegion.h"
#include "AcDb/AcDbRotatedDimension.h"
#include "AcDb/AcDbSequenceEnd.h"
#include "AcDb/AcDbShape.h"
#include "AcDb/AcDbSoftOwnershipId.h"
#include "AcDb/AcDbSoftPointerId.h"
#include "AcDb/AcDbSolid.h"
#include "AcDb/AcDbSolidBackground.h"
#include "AcDb/AcDbSortentsTable.h"
#include "AcDb/AcDbSpatialFilter.h"
#include "AcDb/AcDbSpatialIndexIterator.h"
#include "AcDb/AcDbSpline.h"
#include "AcDb/AcDbSummaryInfoManager.h"
#include "AcDb/AcDbSymbolTablePointer.h"
#include "AcDb/AcDbSymbolTableRecordPointer.h"
#include "AcDb/AcDbSymbolUtilities.h"
#include "AcDb/AcDbSymbolUtilities_Services.h"
#include "AcDb/AcDbTable.h"
#include "AcDb/AcDbTableStyle.h"
#include "AcDb/AcDbTextStyleTableIterator.h"
#include "AcDb/AcDbTrace.h"
#include "AcDb/AcDbTransactionManager.h"
#include "AcDb/AcDbUCSTableIterator.h"
#include "AcDb/AcDbUCSTableRecord.h"
#include "AcDb/AcDbViewport.h"
#include "AcDb/AcDbViewportTableIterator.h"
#include "AcDb/AcDbViewportTableRecord.h"
#include "AcDb/AcDbViewTableIterator.h"
#include "AcDb/AcDbViewTableRecord.h"
#include "AcDb/AcDbWblockCloneFiler.h"
#include "AcDb/AcDbXline.h"
#include "AcDb/AcDbXrecordIterator.h"
#include "AcDb/AcDbXrefGraph.h"
#include "AcDb/AcDbXrefGraphNode.h"
#include "AcDb/AcDbXrefObjectId.h"
#include "AcDb/AcDbExtents.h"
#include "AcDb/AcDbExtents2d.h"
#include "AcDb/AcDbCustomOsnapInfo.h"
#include "AcDb/AcDbCustomOsnapManager.h"
#include "AcDb/AcDbCustomOsnapMode.h"
//#include "AcDb/AcDbDatabase.h"
//#include "AcDb/AcDbDatabaseReactor.h"
#include "AcDb/AcDbDoubleClickEdit.h"
//#include "AcDb/AcDbEntity.h"
//#include "AcDb/AcDbEntityReactor.h"
//#include "AcDb/AcDbFullSubentPath.h"
#include "AcDb/AcDbInterferencePE.h"
#include "AcDb/AcDbLongTransaction.h"
#include "AcDb/AcDbMatchProperties.h"
//#include "AcDb/AcDbObjectIterator.h"
#include "AcDb/AcDbMPolygon.h" //because is not explicitely included in ARX headers
#include "AcDb/AcDbDwfDefinition.h"
#include "AcDb/AcDbDwfReference.h"
#include "AcDb/AcDbDgnDefinition.h"
#include "AcDb/AcDbDgnReference.h"
#include "AcDb/AcDbExtrudedSurface.h"
#include "AcDb/AcDbHelix.h"
#include "AcDb/AcDbLight.h"
#include "AcDb/AcDbLoftedSurface.h"
#include "AcDb/AcDbMentalRayRenderSettings.h"
#include "AcDb/AcDbPdfDefinition.h"
#include "AcDb/AcDbPdfReference.h"
#include "AcDb/AcDbPlaneSurface.h"
#include "AcDb/AcDbRenderEnvironment.h"
#include "AcDb/AcDbRenderGlobal.h"
#include "AcDb/AcDbRenderSettings.h"
#include "AcDb/AcDbRevolvedSurface.h"
#include "AcDb/AcDbSection.h"
#include "AcDb/AcDbSectionManager.h"
#include "AcDb/AcDbSectionSettings.h"
#include "AcDb/AcDbSun.h"
#include "AcDb/AcDbSweptSurface.h"
#include "AcDb/AcDbVisualStyle.h"
#include "AcDb/AcDbUnderlayHost.h"
#include "AcDb/AcDbUnderlayItem.h"
#include "AcDb/AcDbAnnotativeObjectPE.h"
#include "AcDb/AcDbSubDMesh.h"

#include "AcEd/AcEdSymbolUtilities.h"
#include "AcEd/AcEdSymbolUtilities_Services.h"

#include "AcFd/AcFdFieldEngine.h"
#include "AcFd/AcFdFieldEvaluator.h"
#include "AcFd/AcFdFieldEvaluatorLoader.h"
#include "AcFd/AcFdFieldReactor.h"
#include "AcFd/AcFdFieldResult.h"
#include "AcFd/AcFdFieldValue.h"

#include "AcGe/AcGeAugPolyline3d.h"
#include "AcGe/AcGeBoundBlock2d.h"
#include "AcGe/AcGeBoundBlock3d.h"
#include "AcGe/AcGeBoundedPlane.h"
#include "AcGe/AcGeCircArc2d.h"
#include "AcGe/AcGeCircArc3d.h"
#include "AcGe/AcGeLineSeg2d.h"
#include "AcGe/AcGeLineSeg3d.h"
#include "AcGe/AcGeClipBoundary2d.h"
#include "AcGe/AcGeCompositeCurve2d.h"
#include "AcGe/AcGeCompositeCurve3d.h"
#include "AcGe/AcGeCone.h"
#include "AcGe/AcGeCubicSplineCurve2d.h"
#include "AcGe/AcGeCubicSplineCurve3d.h"
#include "AcGe/AcGeCurveBoundary.h"
#include "AcGe/AcGeCurveCurveInt2d.h"
#include "AcGe/AcGeCurveCurveInt3d.h"
#include "AcGe/AcGeCurveSurfInt.h"
#include "AcGe/AcGeCylinder.h"
#include "AcGe/AcGeDwgIO.h"
#include "AcGe/AcGeDxfIO.h"
#include "AcGe/AcGeEllipArc2d.h"
#include "AcGe/AcGeEllipArc3d.h"
#include "AcGe/AcGeExternalBoundedSurface.h"
#include "AcGe/AcGeExternalCurve2d.h"
#include "AcGe/AcGeExternalCurve3d.h"
#include "AcGe/AcGeExternalSurface.h"
#include "AcGe/AcGeFileIO.h"
#include "AcGe/AcGeFiler.h"
//#include "AcGe/AcGeInterval.h"
//#include "AcGe/AcGeKnotVector.h"
#include "AcGe/AcGeNurbCurve2d.h"
#include "AcGe/AcGeNurbCurve3d.h"
#include "AcGe/AcGeNurbSurface.h"
#include "AcGe/AcGeOffsetCurve2d.h"
#include "AcGe/AcGeOffsetCurve3d.h"
#include "AcGe/AcGeOffsetSurface.h"
#include "AcGe/AcGePoint2d.h"
#include "AcGe/AcGePoint3d.h"
//#include "AcGe/AcGePointOnCurve2d.h"
//#include "AcGe/AcGePointOnCurve3d.h"
#include "AcGe/AcGeMatrix2d.h"
#include "AcGe/AcGeMatrix3d.h"
#include "AcGe/AcGePointOnSurface.h"
#include "AcGe/AcGePolyline2d.h"
//#include "AcGe/AcGePolyline3d.h"
#include "AcGe/AcGePosition2d.h"
#include "AcGe/AcGePosition3d.h"
#include "AcGe/AcGeRay2d.h"
#include "AcGe/AcGeRay3d.h"
#include "AcGe/AcGeScale2d.h"
#include "AcGe/AcGeSphere.h"
//#include "AcGe/AcGeSplineEnt2d.h"
//#include "AcGe/AcGeSplineEnt3d.h"
#include "AcGe/AcGeSurfSurfInt.h"
#include "AcGe/AcGeTorus.h"

#include "AcGi/AcGiLightAttenuation.h"
#include "AcGi/AcGiContext.h"
#include "AcGi/AcGiContextualColors.h"
#include "AcGi/AcGiDrawable.h"
#include "AcGi/AcGiDrawableOverrule.h"
#include "AcGi/AcGiEdgeData.h"
#include "AcGi/AcGiFaceData.h"
#include "AcGi/AcGiGradientBackgroundTraits.h"
#include "AcGi/AcGiGroundPlaneBackgroundTraits.h"
#include "AcGi/AcGiImageBackgroundTraits.h"
#include "AcGi/AcGiImageFileTexture.h"
#include "AcGi/AcGiKernelDescriptor.h"
#include "AcGi/AcGiLineAttributes.h"
#include "AcGi/AcGiLineAttrUtils.h"
#include "AcGi/AcGiLinetypeEngine.h"
#include "AcGi/AcGiMapper.h"
#include "AcGi/AcGiMarbleTexture.h"
#include "AcGi/AcGiMaterialColor.h"
#include "AcGi/AcGiMaterialMap.h"
#include "AcGi/AcGiMaterialTraits.h"
#include "AcGi/AcGiMentalRayRenderSettingsTraits.h"
#include "AcGi/AcGiRenderEnvironmentTraits.h"
#include "AcGi/AcGiSolidBackgroundTraits.h"
#include "AcGi/AcGiStyleAttributes.h"
#include "AcGi/AcGiTextEngine.h"
//#include "AcGi/AcGiTextStyle.h"
#include "AcGi/AcGiVertexData.h"
#include "AcGi/AcGiViewport.h"
#include "AcGi/AcGiViewportDraw.h"
#include "AcGi/AcGiViewportGeometry.h"
#include "AcGi/AcGiVisualStyleTraits.h"
#include "AcGi/AcGiWoodTexture.h"
//#include "AcGi/AcGiWorldDraw.h"
#include "AcGi/AcGiWorldGeometry.h"
#include "AcGi/AcGiShadowParameters.h"
#include "AcGi/AcGiStandardLightTraits.h"
#include "AcGi/AcGiGlyph.h"
#include "AcGi/AcGiEdgeStyle.h"
#include "AcGi/AcGiVariant.h"
#include "AcGi/AcGiTransientManager.h"

//#include "AcGs/AcGsGlobal.h"
#include "AcGs/AcGsManager.h"
#include "AcGs/AcGsClassFactory.h" //deprecated
#include "AcGs/AcGsConfig.h"
#include "AcGs/AcGsDevice.h"
#include "AcGs/AcGsGraphicsKernel.h"
#include "AcGs/AcGsKernelDescriptor.h"
#include "AcGs/AcGsNode.h"
#include "AcGs/AcGsReactor.h"
#include "AcGs/AcGs2DViewLimitManager.h"
#include "AcGs/AcGsScreenShot.h"

#include "AcLy/AcLyGlobal.h"
#include "AcLy/AcLyLayerFilterManager.h"
#include "AcLy/AcLyLayerGroup.h"
#include "AcLy/AcLyLayerFilter.h"

#include "AcUt/AcUtGlobal.h"
#include "Misc/AcadAppInfo.h"
#include "Misc/AcDmUtil.h"
#include "Misc/AcFileDependencyManager.h"
#include "Misc/AcString.h"
#include "Misc/AcUniqueString.h"

#ifdef __ATLCOM_H__

  #include "acadi.h"
  #include "axboiler.h"
  #include "AcAx/AcAxGlobal.h"
  #include "AcAx/AcAxDocLock.h"
  #include "AcAx/AcAxMatrix3d.h"
  #include "AcAx/AcAxObjectRefPtr.h"
  #include "AcAx/AcAxOleLinkManager.h"
  #include "AcAx/AcAxPoint2d.h"
  #include "AcAx/AcAxPoint2dArray.h"
  #include "AcAx/AcAxPoint3d.h"
  #include "AcAx/AcAxPoint3dArray.h"

  #ifdef _WIN32 // not yet available for Linux,Mac
    #include "PropertyPalette/OPMPerInstancePropertyExtension.h"
    #include "PropertyPalette/OPMPerInstancePropertyExtensionFactory.h"
    #include "PropertyPalette/OPMPerInstancePropertySources.h"
    #include "PropertyPalette/OPMPropertyExtension.h"
    #include "PropertyPalette/OPMPropertyExtensionFactory.h"
    #include "PropertyPalette/OPMFunctions.h"
    #include "PropertyPalette/PropertyPaletteGlobal.h"
    #include "COM/IOPMPropertyDialog.h"
  #endif
#endif // __ATLCOM_H__

#ifdef _AMODELER_SUPPORT_
  #include "BModeler/BmBody.h"
  #include "BModeler/BmCircle3d.h"
  #include "BModeler/BmCircleCurve.h"
  #include "BModeler/BmConeSurface.h"
  #include "BModeler/BmCylinderSurface.h"
  #include "BModeler/BmDarray.h"
  #include "BModeler/BmEdge.h"
  #include "BModeler/BmEntity.h"
  #include "BModeler/BmFace.h"
  #include "BModeler/BmGlobal.h"
  #include "BModeler/BmInterval1d.h"
  #include "BModeler/BmInterval2d.h"
  #include "BModeler/BmInterval3d.h"
  #include "BModeler/BmIntInterval1d.h"
  #include "BModeler/BmIntInterval2d.h"
  #include "BModeler/BmIntInterval3d.h"
  #include "BModeler/BmIntPoint2d.h"
  #include "BModeler/BmIntPoint3d.h"
  #include "BModeler/BmIntVector2d.h"
  #include "BModeler/BmIntVector3d.h"
  #include "BModeler/BmLine3d.h"
  #include "BModeler/BmMorphingMap.h"
  #include "BModeler/BmOutputPolylineCallback.h"
  #include "BModeler/BmOutputToDxfFileCallback.h"
  #include "BModeler/BmOutputTriangleCallback.h"
  #include "BModeler/BmPlane.h"
  #include "BModeler/BmPoint2d.h"
  #include "BModeler/BmPoint3d.h"
  #include "BModeler/BmPolygonVertexData.h"
  #include "BModeler/BmSaveRestoreCallback.h"
  #include "BModeler/BmSaveToSatCallback.h"
  #include "BModeler/BmSphereSurface.h"
  #include "BModeler/BmTopologyChangeCallback.h"
  #include "BModeler/BmTorusSurface.h"
  #include "BModeler/BmTransf3d.h"
  #include "BModeler/BmUnspecifiedCurve.h"
  #include "BModeler/BmUnspecifiedSurface.h"
  #include "BModeler/BmVector2d.h"
  #include "BModeler/BmVector3d.h"
  #include "BModeler/BmVertex.h"
  #include "BModeler/BmVertexSurfaceData.h"
  #ifdef _WIN32
    #pragma comment(lib ,"bmodeler23.lib")
  #endif // _WIN32
#endif //_AMODELER_SUPPORT_

#ifdef _HLR_SUPPORT_
  #include "HLR/AsdkHiddenLineBase.h"
  #include "HLR/AsdkHlrCollector.h"
  #include "HLR/AsdkHlrData.h"
  #include "HLR/AsdkHlrEngine.h"
  #ifdef _WIN32
    #pragma comment(lib ,"BrxHlrApi23.lib")
  #endif // _WIN32
#endif //_HLR_SUPPORT_

#ifdef _BREP_SUPPORT_
  #include "AcBr/AcBrBrep.h"
  #include "AcBr/AcBrBrepComplexTraverser.h"
  #include "AcBr/AcBrBrepEdgeTraverser.h"
  #include "AcBr/AcBrBrepFaceTraverser.h"
  #include "AcBr/AcBrBrepShellTraverser.h"
  #include "AcBr/AcBrBrepVertexTraverser.h"
  #include "AcBr/AcBrComplex.h"
  #include "AcBr/AcBrComplexShellTraverser.h"
  #include "AcBr/AcBrEdge.h"
  #include "AcBr/AcBrEdgeLoopTraverser.h"
  #include "AcBr/AcBrElement.h"
  #include "AcBr/AcBrElement2d.h"
  #include "AcBr/AcBrElement2dNodeTraverser.h"
  #include "AcBr/AcBrEntity.h"
  #include "AcBr/AcBrFace.h"
  #include "AcBr/AcBrFaceLoopTraverser.h"
  #include "AcBr/AcBrGlobal.h"
  #include "AcBr/AcBrHit.h"
  #include "AcBr/AcBrLoop.h"
  #include "AcBr/AcBrLoopEdgeTraverser.h"
  #include "AcBr/AcBrLoopVertexTraverser.h"
  #include "AcBr/AcBrMassProps.h"
  #include "AcBr/AcBrMesh.h"
  #include "AcBr/AcBrMesh2d.h"
  #include "AcBr/AcBrMesh2dControl.h"
  #include "AcBr/AcBrMesh2dElement2dTraverser.h"
  #include "AcBr/AcBrMesh2dFilter.h"
  #include "AcBr/AcBrMeshControl.h"
  #include "AcBr/AcBrMeshEntity.h"
  #include "AcBr/AcBrNode.h"
  #include "AcBr/AcBrShell.h"
  #include "AcBr/AcBrShellFaceTraverser.h"
  #include "AcBr/AcBrTraverser.h"
  #include "AcBr/AcBrVertex.h"
  #include "AcBr/AcBrVertexEdgeTraverser.h"
  #include "AcBr/AcBrVertexLoopTraverser.h"
#endif //_BREP_SUPPORT_

#endif // __cplusplus

// C API ObjectDBX
#include "adslib.h"
#include "adsdlg.h"

#pragma pack(pop)

// the HLR API module provided by Bricscad
#ifndef HLR_API_MODULE
  #ifdef _WIN32 // Windows
    #define HLR_API_MODULE  ACRX_T("BrxHlrApi23.dbx")
  #else         // Linux, Mac
    #define HLR_API_MODULE  ACRX_T("libbrxhlrapi23.so")
  #endif
#endif

// the BMODELER API module provided by Bricscad
#ifndef BMODELER_API_MODULE
  #ifdef _WIN32 // Windows
    #define BMODELER_API_MODULE  ACRX_T("bmodeler23.dbx")
  #else         // Linux, Mac
    #define BMODELER_API_MODULE  ACRX_T("libbmodeler23.so")
  #endif
#endif
// and AModeler alias ...
#ifndef AMODELER_API_MODULE
  #define AMODELER_API_MODULE BMODELER_API_MODULE
#endif
