// Copyright (C) 2017-2018 Menhirs NV. All rights reserved.
#pragma once

#define ATILIMAGEAPIMAJORVERSION "3"
#define ATILIMAGEAPIMIMORVERSION "0"

#define ATILSUBSYSTEMAPIMAJORVERSION "3"
#define ATILSUBSYSTEMAPIMINORVERSION "0"

#define ATILFORMATCODECAPIMAJORVERSION "0"
#define ATILFORMATCODECAPIMINORVERSION "0"
