name: Bug Report
description: File a bug report
labels: [Bug]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill this out!
  - type: textarea
    id: how
    attributes:
      label: Problem
      description: Please give a text description of how you reached the problem
      placeholder: |
        1. Install...
        2. Do this...
        3. Do that...
        4. Observe the error...
    validations:
      required: true
  - type: textarea
    id: what
    attributes:
      label: Solution (if any)
      description: Explain where you think the problem comes from (optional)
      placeholder: The code to place a is missing b and c...
    validations:
      required: false
  - type: input
    id: version
    attributes:
      label: Version
      description: What version are you running?
      placeholder: DO NOT SAY "LATEST"
    validations:
      required: true
  - type: input
    id: logs
    attributes:
      label: Log
      description: Paste a full log. Always use [Pastebin](https://pastebin.com/). Must not be a crash report. Must be a full log. Must not be a screenshot of a log.
      placeholder: https://pastebin.com/...
    validations:
      required: true
  - type: markdown
    id: thanks
    attributes:
      value: "Thank you for filling out the form! We will be with you soon. Please do not ask support to review your report."
