// AcOpmNativePropertyIds.h
// definition of enum for native OPM property ids

// Copyright © Menhirs NV. All rights reserved.

//HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH

#pragma once

#undef  OPM_NATIVE_PROPERTY
#define OPM_NATIVE_PROPERTY(id, name) acOpmId_##id,

enum AcOpmNativePropertyId
{
    acOpmId_EmptyProperty = -1,
    //                    id                                  English name for Property Panel
    //                                                        (only intended as hint)
    OPM_NATIVE_PROPERTY ( None,                               _T("UNDEFINED"))
    OPM_NATIVE_PROPERTY ( 3DArea,                             _("Surface area"))
    OPM_NATIVE_PROPERTY ( AdjustBgColors,                     _("Adjust colors for background"))
    OPM_NATIVE_PROPERTY ( AltEnabled,                         _("Alt enabled"))
    OPM_NATIVE_PROPERTY ( Altitude,                           _("Altitude"))
    OPM_NATIVE_PROPERTY ( AltPrecision,                       _("Alt precision"))
    OPM_NATIVE_PROPERTY ( AltPrefix,                          _("Alt prefix"))
    OPM_NATIVE_PROPERTY ( AltRound,                           _("Alt round"))
    OPM_NATIVE_PROPERTY ( AltScaleFactor,                     _("Alt scale factor"))
    OPM_NATIVE_PROPERTY ( AltSuffix,                          _("Alt suffix"))
    OPM_NATIVE_PROPERTY ( AltSuppressLeadingZeros,            _("Alt suppress leading zeros"))
    OPM_NATIVE_PROPERTY ( AltSuppressTrailingZeros,           _("Alt suppress trailing zeros"))
    OPM_NATIVE_PROPERTY ( AltSuppressZeroFeet,                _("Alt suppress zero feet"))
    OPM_NATIVE_PROPERTY ( AltSuppressZeroInches,              _("Alt suppress zero inches"))
    OPM_NATIVE_PROPERTY ( AltTolerancePrecision,              _("Alt tolerance precision"))
    OPM_NATIVE_PROPERTY ( AltToleranceSuppressLeadingZeros,   _("Alt tolerance suppress leading zeros"))
    OPM_NATIVE_PROPERTY ( AltToleranceSuppressTrailingZeros,  _("Alt tolerance suppress trailing zeros"))
    OPM_NATIVE_PROPERTY ( AltToleranceSuppressZeroFeet,       _("Alt tolerance suppress zero feet"))
    OPM_NATIVE_PROPERTY ( AltToleranceSuppressZeroInches,     _("Alt tolerance suppress zero inches"))
    OPM_NATIVE_PROPERTY ( AltUnits,                           _("Alt units"))
    OPM_NATIVE_PROPERTY ( AltZeroFactor,                      _("Alt sub-units scale"))
    OPM_NATIVE_PROPERTY ( AltZeroSuffix,                      _("Alt sub-units suffix"))
    OPM_NATIVE_PROPERTY ( AlwaysOnTop,                        _("Always on top"))
    OPM_NATIVE_PROPERTY ( Angle,                              _("Angle"))
    OPM_NATIVE_PROPERTY ( AnnoMatchOrientation,               _("Match orientation to layout"))
    OPM_NATIVE_PROPERTY ( AnnoModelDefinedHeight,             _("Model defined height"))
    OPM_NATIVE_PROPERTY ( AnnoModelDefinedWidth,              _("Model defined width"))
    OPM_NATIVE_PROPERTY ( AnnoModelTextHeight,                _("Model text height"))
    OPM_NATIVE_PROPERTY ( AnnoPaperDefinedHeight,             _("Paper defined height"))
    OPM_NATIVE_PROPERTY ( AnnoPaperDefinedWidth,              _("Paper defined width"))
    OPM_NATIVE_PROPERTY ( AnnoPaperTextHeight,                _("Paper text height"))
    OPM_NATIVE_PROPERTY ( AnnotationScale,                    _("Annotation scale"))
    OPM_NATIVE_PROPERTY ( Annotative,                         _("Annotative"))
    OPM_NATIVE_PROPERTY ( AnnotativeScale,                    _("Annotative scale"))
    OPM_NATIVE_PROPERTY ( ArcCircleSmoothing,                 _("Arc/circle smoothing"))
    OPM_NATIVE_PROPERTY ( ArcLength,                          _("Arc length"))
    OPM_NATIVE_PROPERTY ( ArcLengthSymbol,                    _("Arc length symbol"))
    OPM_NATIVE_PROPERTY ( ArcOffset,                          _("Arc offset"))
    OPM_NATIVE_PROPERTY ( Area,                               _("Area"))
    OPM_NATIVE_PROPERTY ( ArrayAlignItems,                    _("Align items"))
    OPM_NATIVE_PROPERTY ( ArrayAngleBetweenItems,             _("Angle between items"))
    OPM_NATIVE_PROPERTY ( ArrayBase,                          _("Base"))
    OPM_NATIVE_PROPERTY ( ArrayColumns,                       _("Columns"))
    OPM_NATIVE_PROPERTY ( ArrayColumnSpacing,                 _("Column spacing"))
    OPM_NATIVE_PROPERTY ( ArrayDirection,                     _("Direction"))
    OPM_NATIVE_PROPERTY ( ArrayEndOffset,                     _("End offset"))
    OPM_NATIVE_PROPERTY ( ArrayIncludedAxisAngle,             _("Included axis angle"))
    OPM_NATIVE_PROPERTY ( ArrayItemOffset,                    _("Offset"))
    OPM_NATIVE_PROPERTY ( ArrayItemRotation,                  _("Rotation"))
    OPM_NATIVE_PROPERTY ( ArrayItems,                         _("Items"))
    OPM_NATIVE_PROPERTY ( ArrayItemScale,                     _("Scale"))
    OPM_NATIVE_PROPERTY ( ArrayItemSpacing,                   _("Item spacing"))
    OPM_NATIVE_PROPERTY ( ArrayFillAngle,                     _("Fill angle"))
    OPM_NATIVE_PROPERTY ( ArrayFillEntirePath,                _("Fill entire path"))
    OPM_NATIVE_PROPERTY ( ArrayLevels,                        _("Levels"))
    OPM_NATIVE_PROPERTY ( ArrayLevelSpacing,                  _("Level spacing"))
    OPM_NATIVE_PROPERTY ( ArrayMethod,                        _("Method"))
    OPM_NATIVE_PROPERTY ( ArrayPathLength,                    _("Path length"))
    OPM_NATIVE_PROPERTY ( ArrayRadius,                        _("Radius"))
    OPM_NATIVE_PROPERTY ( ArrayRowElevationInc,               _("Row elevation increment"))
    OPM_NATIVE_PROPERTY ( ArrayRows,                          _("Rows"))
    OPM_NATIVE_PROPERTY ( ArrayRowSpacing,                    _("Row spacing"))
    OPM_NATIVE_PROPERTY ( ArrayRotateItems,                   _("Rotate items"))
    OPM_NATIVE_PROPERTY ( ArrayStartOffset,                   _("Start offset"))
    OPM_NATIVE_PROPERTY ( Arrow,                              _("Arrow"))
    OPM_NATIVE_PROPERTY ( Arrow1,                             _("Arrow 1"))
    OPM_NATIVE_PROPERTY ( Arrow2,                             _("Arrow 2"))
    OPM_NATIVE_PROPERTY ( ArrowHeads,                         _("Arrowheads"))
    OPM_NATIVE_PROPERTY ( ArrowSize,                          _("Arrow size"))
    OPM_NATIVE_PROPERTY ( Associative,                        _("Associative"))
    OPM_NATIVE_PROPERTY ( AssociativeHatch,                   _("Associative"))
    OPM_NATIVE_PROPERTY ( AttachmentType,                     _("Attachment type"))
    OPM_NATIVE_PROPERTY ( AttenuationType,                    _("Type"))
    OPM_NATIVE_PROPERTY ( Attributes,                         _T("DYNAMIC"))
    OPM_NATIVE_PROPERTY ( Azimuth,                            _("Azimuth"))
    OPM_NATIVE_PROPERTY ( Background,                         _("Background"))
    OPM_NATIVE_PROPERTY ( Backgrounds,                        _("Backgrounds"))
    OPM_NATIVE_PROPERTY ( BackgroundMask,                     _("Background mask"))
    OPM_NATIVE_PROPERTY ( BackgroundColor,                    _("Color"))
    OPM_NATIVE_PROPERTY ( BackgroundHiddenLine,               _("Hidden line"))
    OPM_NATIVE_PROPERTY ( BackgroundLayer,                    _("Layer"))
    OPM_NATIVE_PROPERTY ( BackgroundLinetype,                 _("Linetype"))
    OPM_NATIVE_PROPERTY ( BackgroundLinetypeScale,            _("Linetype scale"))
    OPM_NATIVE_PROPERTY ( BackgroundLineweight,               _("Lineweight"))
    OPM_NATIVE_PROPERTY ( BackgroundPlotStyle,                _("Plot style"))
    OPM_NATIVE_PROPERTY ( BackgroundTransparency,             _("Background transparency"))
    OPM_NATIVE_PROPERTY ( BackgroundVisibility,               _("Show"))
    OPM_NATIVE_PROPERTY ( BackPlane,                          _("Back plane"))
    OPM_NATIVE_PROPERTY ( Backward,                           _("Backward"))
    OPM_NATIVE_PROPERTY ( BasedOn,                            _("Based on"))
    OPM_NATIVE_PROPERTY ( Basepoint,                          _("Basepoint"))
    OPM_NATIVE_PROPERTY ( BaseRadius,                         _("Base radius"))
    OPM_NATIVE_PROPERTY ( Bitmap,                             _("Bitmap"))
    OPM_NATIVE_PROPERTY ( BlockConnectionType,                _("Attachment"))
    OPM_NATIVE_PROPERTY ( BlockUnits,                         _("Block unit"))
    OPM_NATIVE_PROPERTY ( BlockScale,                         _("Scale"))
    OPM_NATIVE_PROPERTY ( BlockScaleUniformly,                _("Scale Uniformly"))
    OPM_NATIVE_PROPERTY ( BottomAttachment,                   _("Bottom attachment"))
    OPM_NATIVE_PROPERTY ( BottomExtension,                    _("Bottom extension"))
    OPM_NATIVE_PROPERTY ( BottomPlane,                        _("Bottom plane"))
    OPM_NATIVE_PROPERTY ( BoundaryColor,                      _("Color"))
    OPM_NATIVE_PROPERTY ( BoundaryDivisionLines,              _("Division lines"))
    OPM_NATIVE_PROPERTY ( BoundaryLayer,                      _("Layer"))
    OPM_NATIVE_PROPERTY ( BoundaryLinetype,                   _("Linetype"))
    OPM_NATIVE_PROPERTY ( BoundaryLinetypeScale,              _("Linetype scale"))
    OPM_NATIVE_PROPERTY ( BoundaryPlotStyle,                  _("Plot style"))
    OPM_NATIVE_PROPERTY ( BoundaryLineweight,                 _("Lineweight"))
    OPM_NATIVE_PROPERTY ( BoundaryVisibility,                 _("Show"))
    OPM_NATIVE_PROPERTY ( Brightness,                         _("Brightness"))
    OPM_NATIVE_PROPERTY ( Bulge,                              _("Bulge"))
    OPM_NATIVE_PROPERTY ( Camera,                             _("Camera"))
    OPM_NATIVE_PROPERTY ( Category,                           _("Category"))
    OPM_NATIVE_PROPERTY ( CellWidth,                          _("Cell width"))
    OPM_NATIVE_PROPERTY ( CellHeight,                         _("Cell height"))
    OPM_NATIVE_PROPERTY ( CellVerticalMargin,                 _("Vertical cell margin"))
    OPM_NATIVE_PROPERTY ( CellHorizontalMargin,               _("Horizontal cell margin"))
    OPM_NATIVE_PROPERTY ( CellContentType,                    _("Cell type"))
    OPM_NATIVE_PROPERTY ( CellContentLayout,                  _("Content layout"))
    OPM_NATIVE_PROPERTY ( CellContentBlocks,                  _("Blocks in cell"))
    OPM_NATIVE_PROPERTY ( CellContentTexts,                   _("Text items in cell"))
    OPM_NATIVE_PROPERTY ( CellContentBlockName,               _("Block name"))
    OPM_NATIVE_PROPERTY ( CellContentBlockAutoScale,          _("Auto scale"))
    OPM_NATIVE_PROPERTY ( CellContentBlockScale,              _("Block Scale"))
    OPM_NATIVE_PROPERTY ( CellContentBlockRotation,           _("Block Rotation"))
    OPM_NATIVE_PROPERTY ( Center,                             _("Center"))
    OPM_NATIVE_PROPERTY ( Centered,                           _("Centered"))
    OPM_NATIVE_PROPERTY ( CenterLocationOverride,             _("Center location override"))
    OPM_NATIVE_PROPERTY ( CenterMarkType,                     _("Center mark"))
    OPM_NATIVE_PROPERTY ( CenterMarkSize,                     _("Center mark size"))
    OPM_NATIVE_PROPERTY ( Centroid,                           _("Centroid"))
    OPM_NATIVE_PROPERTY ( CharSpacing,                        _("Char spacing"))
    OPM_NATIVE_PROPERTY ( Circumference,                      _("Circumference"))
    OPM_NATIVE_PROPERTY ( ClipDisplay,                        _("Clip display"))
    OPM_NATIVE_PROPERTY ( Clipped,                            _("Clipped"))
    OPM_NATIVE_PROPERTY ( Clipping,                           _("Clipping"))
    OPM_NATIVE_PROPERTY ( ClipInverted,                       _("Clip inverted"))
    OPM_NATIVE_PROPERTY ( Closed,                             _("Closed"))
    OPM_NATIVE_PROPERTY ( Color,                              _("Color"))
    OPM_NATIVE_PROPERTY ( Color1,                             _("Color 1"))
    OPM_NATIVE_PROPERTY ( Color2,                             _("Color 2"))
    OPM_NATIVE_PROPERTY ( Columns,                            _("Columns"))
    OPM_NATIVE_PROPERTY ( ColumnSpacing,                      _("Column spacing"))
    OPM_NATIVE_PROPERTY ( CommandString,                      _("Command string"))
    OPM_NATIVE_PROPERTY ( Constant,                           _("Constant"))
    OPM_NATIVE_PROPERTY ( Constrain,                          _("Constrain"))
    OPM_NATIVE_PROPERTY ( ConstraintForm,                     _("Constraint form"))
    OPM_NATIVE_PROPERTY ( Contents,                           _("Contents"))
    OPM_NATIVE_PROPERTY ( ContourLines,                       _("Contour lines"))
    OPM_NATIVE_PROPERTY ( Contrast,                           _("Contrast"))
    OPM_NATIVE_PROPERTY ( ControlPoint,                       _("Control point"))
    OPM_NATIVE_PROPERTY ( ControlPoints,                      _("Number of control points"))
    OPM_NATIVE_PROPERTY ( Coordinate,                         _("Coordinate"))
    OPM_NATIVE_PROPERTY ( Count,                              _("Count"))
    OPM_NATIVE_PROPERTY ( Crease,                             _("Crease"))
    OPM_NATIVE_PROPERTY ( CreaseAngle,                        _("Crease angle"))
    OPM_NATIVE_PROPERTY ( CrossSize,                          _("Cross size"))
    OPM_NATIVE_PROPERTY ( CrossGap,                           _("Cross gap"))
    OPM_NATIVE_PROPERTY ( CRS,                                _("CRS"))
    OPM_NATIVE_PROPERTY ( Current,                            _("Current"))
    OPM_NATIVE_PROPERTY ( CustomPen,                          _("Custom pen"))
    OPM_NATIVE_PROPERTY ( CustomPenOnOff,                     _("On/Off"))
    OPM_NATIVE_PROPERTY ( CustomScale,                        _("Custom scale"))
    OPM_NATIVE_PROPERTY ( CVFrame,                            _("CV frame"))
    OPM_NATIVE_PROPERTY ( Date,                               _("Date"))
    OPM_NATIVE_PROPERTY ( DaylightSaving,                     _("Daylight saving"))
    OPM_NATIVE_PROPERTY ( DecimalSeparator,                   _("Decimal separator"))
    OPM_NATIVE_PROPERTY ( DefaultLighting,                    _("Default lighting"))
    OPM_NATIVE_PROPERTY ( DefinedHeight,                      _("Defined height"))
    OPM_NATIVE_PROPERTY ( DefinedWidth,                       _("Defined width"))
    OPM_NATIVE_PROPERTY ( Degree,                             _("Degree"))
    OPM_NATIVE_PROPERTY ( Delta,                              _("Delta"))
    OPM_NATIVE_PROPERTY ( Dependency,                         _("Dependency"))
    OPM_NATIVE_PROPERTY ( Description,                        _("Description"))
    OPM_NATIVE_PROPERTY ( DestinationFile,                    _("Destination file"))
    OPM_NATIVE_PROPERTY ( DeviceName,                         _("Device name"))
    OPM_NATIVE_PROPERTY ( Diameter,                           _("Diameter"))
    OPM_NATIVE_PROPERTY ( DiffType,                           _("Diff type"))
    OPM_NATIVE_PROPERTY ( DimAnglePrecision,                  _("Dim angle precision"))
    OPM_NATIVE_PROPERTY ( DimAngleUnits,                      _("Dim angle units"))
    OPM_NATIVE_PROPERTY ( DimBaselineSpacing,                 _("Dim baseline spacing"))
    OPM_NATIVE_PROPERTY ( DimBreakSize,                       _("Dim break size"))
    OPM_NATIVE_PROPERTY ( DimLine,                            _("Dim line"))
    OPM_NATIVE_PROPERTY ( DimLine1,                           _("Dim line 1"))
    OPM_NATIVE_PROPERTY ( DimLine2,                           _("Dim line 2"))
    OPM_NATIVE_PROPERTY ( DimLineColor,                       _("Dim line color"))
    OPM_NATIVE_PROPERTY ( DimLineExt,                         _("Dim line ext"))
    OPM_NATIVE_PROPERTY ( DimLineForced,                      _("Dim line forced"))
    OPM_NATIVE_PROPERTY ( DimLineInside,                      _("Dim line inside"))
    OPM_NATIVE_PROPERTY ( DimLineLW,                          _("Dim line LW"))
    OPM_NATIVE_PROPERTY ( DimLineType,                        _("Dim line type"))
    OPM_NATIVE_PROPERTY ( DimPrecision,                       _("Dim precision"))
    OPM_NATIVE_PROPERTY ( DimPrefix,                          _("Dim prefix"))
    OPM_NATIVE_PROPERTY ( DimRound,                           _("Dim round"))
    OPM_NATIVE_PROPERTY ( DimScaleLinear,                     _("Dim scale linear"))
    OPM_NATIVE_PROPERTY ( DimScaleOverall,                    _("Dim scale overall"))
    OPM_NATIVE_PROPERTY ( DimStyle,                           _("Dim style"))
    OPM_NATIVE_PROPERTY ( DimSuffix,                          _("Dim suffix"))
    OPM_NATIVE_PROPERTY ( DimUnits,                           _("Dim units"))
    OPM_NATIVE_PROPERTY ( DimZeroFactor,                      _("Dim sub-units scale"))
    OPM_NATIVE_PROPERTY ( DimZeroSuffix,                      _("Dim sub-units suffix"))
    OPM_NATIVE_PROPERTY ( Direction,                          _("Direction"))
    OPM_NATIVE_PROPERTY ( DirectionVector,                    _("Direction vector"))
    OPM_NATIVE_PROPERTY ( DisplayLocked,                      _("Display locked"))
    OPM_NATIVE_PROPERTY ( Double,                             _("Double"))
    OPM_NATIVE_PROPERTY ( Download,                           _("Download"))
    OPM_NATIVE_PROPERTY ( DrawingUnits,                       _("Drawing units"))
    OPM_NATIVE_PROPERTY ( DrawTrueSilhouettes,                _("Draw true silhouettes"))
    OPM_NATIVE_PROPERTY ( GridFiller,                         _T(""))
    OPM_NATIVE_PROPERTY ( DynBlock,                           _T("DYNAMIC"))
    OPM_NATIVE_PROPERTY ( Edge1,                              _("Edge 1"))
    OPM_NATIVE_PROPERTY ( Edge2,                              _("Edge 2"))
    OPM_NATIVE_PROPERTY ( Edge3,                              _("Edge 3"))
    OPM_NATIVE_PROPERTY ( Edge4,                              _("Edge 4"))
    OPM_NATIVE_PROPERTY ( EdgeColor,                          _("Color"))
    OPM_NATIVE_PROPERTY ( EdgeWidth,                          _("Width"))
    OPM_NATIVE_PROPERTY ( Elevation,                          _("Elevation "))
    OPM_NATIVE_PROPERTY ( EndAngle,                           _("End angle"))
    OPM_NATIVE_PROPERTY ( EndExtension,                       _("End extension"))
    OPM_NATIVE_PROPERTY ( EndLimitOffset,                     _("End limit offset"))
    OPM_NATIVE_PROPERTY ( EndPoint,                           _("End point"))
    OPM_NATIVE_PROPERTY ( EndSegmentWidth,                    _("End width"))
    OPM_NATIVE_PROPERTY ( EndTangent,                         _("End tangent"))
    OPM_NATIVE_PROPERTY ( EntityType,                         _("Entity type"))
    OPM_NATIVE_PROPERTY ( EffectiveName,                      _("Name"))
    OPM_NATIVE_PROPERTY ( EffectiveType,                      _("Effective type"))
    OPM_NATIVE_PROPERTY ( ExistingBlocks,                     _("Existing blocks"))
    OPM_NATIVE_PROPERTY ( Explodable,                         _("Explodable"))
    OPM_NATIVE_PROPERTY ( Explode,                            _("Explode"))
    OPM_NATIVE_PROPERTY ( Expression,                         _("Expression"))
    OPM_NATIVE_PROPERTY ( ExtLine1,                           _("Ext line 1"))
    OPM_NATIVE_PROPERTY ( ExtLine2,                           _("Ext line 2"))
    OPM_NATIVE_PROPERTY ( ExtLineColor,                       _("Ext line color"))
    OPM_NATIVE_PROPERTY ( ExtLineExt,                         _("Ext line ext"))
    OPM_NATIVE_PROPERTY ( ExtLineFixed,                       _("Ext line fixed"))
    OPM_NATIVE_PROPERTY ( ExtLineFixedLength,                 _("Ext line fixed length"))
    OPM_NATIVE_PROPERTY ( ExtLineLW,                          _("Ext line LW"))
    OPM_NATIVE_PROPERTY ( ExtLineOffset,                      _("Ext line offset"))
    OPM_NATIVE_PROPERTY ( ExtLineType1,                       _("Ext line type 1"))
    OPM_NATIVE_PROPERTY ( ExtLineType2,                       _("Ext line type 2"))
    OPM_NATIVE_PROPERTY ( Exposed,                            _("Exposed"))
    OPM_NATIVE_PROPERTY ( FaceCamera,                         _("Face camera"))
    OPM_NATIVE_PROPERTY ( Faces,                              _("Faces"))
    OPM_NATIVE_PROPERTY ( FaceStyle,                          _("Face style"))
    OPM_NATIVE_PROPERTY ( Fade,                               _("Fade"))
    OPM_NATIVE_PROPERTY ( FalloffAngle,                       _("Falloff angle"))
    OPM_NATIVE_PROPERTY ( FieldOfView,                        _("Field of view"))
    OPM_NATIVE_PROPERTY ( FileName,                           _("File name"))
    OPM_NATIVE_PROPERTY ( FilePath,                           _("Source file"))
    OPM_NATIVE_PROPERTY ( FillAngle,                          _("Angle"))
    OPM_NATIVE_PROPERTY ( FillColor,                          _("Color"))
    OPM_NATIVE_PROPERTY ( FillFaceHatch,                      _("Face hatch"))
    OPM_NATIVE_PROPERTY ( FillHatchScale,                     _("Hatch scale"))
    OPM_NATIVE_PROPERTY ( FillHatchSpacing,                   _("Hatch spacing"))
    OPM_NATIVE_PROPERTY ( FillLayer,                          _("Layer"))
    OPM_NATIVE_PROPERTY ( FillLinetype,                       _("Linetype"))
    OPM_NATIVE_PROPERTY ( FillLinetypeScale,                  _("Linetype scale"))
    OPM_NATIVE_PROPERTY ( FillLineweight,                     _("Lineweight"))
    OPM_NATIVE_PROPERTY ( FillPlotStyle,                      _("Plot Style"))
    OPM_NATIVE_PROPERTY ( FillVisibility,                     _("Show"))
    OPM_NATIVE_PROPERTY ( FillSurfaceTransparency,            _("Surface transparency"))
    OPM_NATIVE_PROPERTY ( FilterColor,                        _("Filter color"))
    OPM_NATIVE_PROPERTY ( Fit,                                _("Arrow and text fit"))
    OPM_NATIVE_PROPERTY ( FitPoint,                           _("Fit point"))
    OPM_NATIVE_PROPERTY ( FitPoints,                          _("Number of fit points"))
    OPM_NATIVE_PROPERTY ( FitSmooth,                          _("Fit/Smooth"))
    OPM_NATIVE_PROPERTY ( FitTolerance,                       _("Fit tolerance"))
    OPM_NATIVE_PROPERTY ( FontBackwards,                      _("Font backwards"))
    OPM_NATIVE_PROPERTY ( FontBig,                            _("Bigfont"))
    OPM_NATIVE_PROPERTY ( FontHeight,                         _("Font height"))
    OPM_NATIVE_PROPERTY ( FontLanguage,                       _("Font language"))
    OPM_NATIVE_PROPERTY ( FontName,                           _("Saved font"))
    OPM_NATIVE_PROPERTY ( FoundFont,                          _("Found font"))
    OPM_NATIVE_PROPERTY ( FontObliqueAngle,                   _("Font oblique angle"))
    OPM_NATIVE_PROPERTY ( FontStyle,                          _("Font style"))
    OPM_NATIVE_PROPERTY ( FontUpsideDown,                     _("Font upside down"))
    OPM_NATIVE_PROPERTY ( FontVertical,                       _("Font vertical"))
    OPM_NATIVE_PROPERTY ( FontWidthFactor,                    _("Font width factor"))
    OPM_NATIVE_PROPERTY ( ForegroundColor,                    _("Color"))
    OPM_NATIVE_PROPERTY ( ForegroundEdgeTransparency,         _("Edge transparency"))
    OPM_NATIVE_PROPERTY ( ForegroundFaceTransparency,         _("Face transparency"))
    OPM_NATIVE_PROPERTY ( ForegroundHiddenLine,               _("Hidden line"))
    OPM_NATIVE_PROPERTY ( ForegroundLayer,                    _("Layer"))
    OPM_NATIVE_PROPERTY ( ForegroundLinetype,                 _("Linetype"))
    OPM_NATIVE_PROPERTY ( ForegroundLinetypeScale,            _("Linetype scale"))
    OPM_NATIVE_PROPERTY ( ForegroundLineweight,               _("Lineweight"))
    OPM_NATIVE_PROPERTY ( ForegroundPlotStyle,                _("Plot style"))
    OPM_NATIVE_PROPERTY ( ForegroundVisibility,               _("Show"))
    OPM_NATIVE_PROPERTY ( FoundPath,                          _("Found path"))
    OPM_NATIVE_PROPERTY ( FractionalType,                     _("Fractional type"))
    OPM_NATIVE_PROPERTY ( Freeze,                             _("Freeze"))
    OPM_NATIVE_PROPERTY ( FromVector,                         _("From vector"))
    OPM_NATIVE_PROPERTY ( FrontPlane,                         _("Front plane"))
    OPM_NATIVE_PROPERTY ( GlobalWidth,                        _("Global width"))
    OPM_NATIVE_PROPERTY ( GlyphDisplay,                       _("Glyph display"))
    OPM_NATIVE_PROPERTY ( GradientAngle,                      _("Gradient angle"))
    OPM_NATIVE_PROPERTY ( GradientName,                       _("Gradient name"))
    OPM_NATIVE_PROPERTY ( GyrationRadii,                      _("Gyration radii"))
    OPM_NATIVE_PROPERTY ( HaloGap,                            _("Halo gap %"))
    OPM_NATIVE_PROPERTY ( HaloGap2dWireframe,                 _("Halo gap %"))
    OPM_NATIVE_PROPERTY ( HalfAngle,                          _("Half angle"))
    OPM_NATIVE_PROPERTY ( Handle,                             _("Handle"))
    OPM_NATIVE_PROPERTY ( HatchType,                          _("Tool type"))
    OPM_NATIVE_PROPERTY ( HatchBackgroundColor,               _("Background color"))
    OPM_NATIVE_PROPERTY ( Height,                             _("Height"))
    OPM_NATIVE_PROPERTY ( HiddenLineVisibility,               _("Show"))
    OPM_NATIVE_PROPERTY ( HiddenLineColor,                    _("Color"))
    OPM_NATIVE_PROPERTY ( HiddenLineLayer,                    _("Layer"))
    OPM_NATIVE_PROPERTY ( HiddenLineLinetype,                 _("Linetype"))
    OPM_NATIVE_PROPERTY ( HiddenLineLinetypeScale,            _("Linetype scale"))
    OPM_NATIVE_PROPERTY ( HiddenLineLineweight,               _("Lineweight"))
    OPM_NATIVE_PROPERTY ( HiddenLinePlotStyle,                _("Plot style"))
    OPM_NATIVE_PROPERTY ( HighlightIntensity,                 _("Highlight intensity"))
    OPM_NATIVE_PROPERTY ( HighlightIntensityOnOff,            _("On/Off"))
    OPM_NATIVE_PROPERTY ( History,                            _("History"))
    OPM_NATIVE_PROPERTY ( Holes,                              _("Holes"))
    OPM_NATIVE_PROPERTY ( HotspotAngle,                       _("Hotspot angle"))
    OPM_NATIVE_PROPERTY ( Hyperlink,                          _("Hyperlink"))
    OPM_NATIVE_PROPERTY ( InertiaMoments,                     _("Moments of inertia"))
    OPM_NATIVE_PROPERTY ( InertiaProductXY,                   _("Product of inertia XY"))
    OPM_NATIVE_PROPERTY ( InertiaProductYZ,                   _("Product of inertia YZ"))
    OPM_NATIVE_PROPERTY ( InertiaProductXZ,                   _("Product of inertia XZ"))
    OPM_NATIVE_PROPERTY ( InsertionPoint,                     _("Insertion point"))
    OPM_NATIVE_PROPERTY ( IntensityFactor,                    _("Intensity factor"))
    OPM_NATIVE_PROPERTY ( IntersectionColor,                  _("Color"))
    OPM_NATIVE_PROPERTY ( IntersectionEdgesColor,             _("Color"))
    OPM_NATIVE_PROPERTY ( IntersectionEdgesLinetype,          _("Linetype"))
    OPM_NATIVE_PROPERTY ( Invisible,                          _("Invisible"))
    OPM_NATIVE_PROPERTY ( IslandDetectionStyle,               _("Island detection style"))
    OPM_NATIVE_PROPERTY ( ISOPenWidth,                        _("ISO pen width"))
    OPM_NATIVE_PROPERTY ( Jitter,                             _("Jitter"))
    OPM_NATIVE_PROPERTY ( JitterOnOff,                        _("Jitter On/Off"))
    OPM_NATIVE_PROPERTY ( JogAngle,                           _("Jog angle"))
    OPM_NATIVE_PROPERTY ( JogLocation,                        _("Jog location"))
    OPM_NATIVE_PROPERTY ( Justify,                            _("Justify"))
    OPM_NATIVE_PROPERTY ( JustifyMtext,                       _("Justify"))
    OPM_NATIVE_PROPERTY ( KnotParameterization,               _("Knot parameterization"))
    OPM_NATIVE_PROPERTY ( LampColor,                          _("Lamp color"))
    OPM_NATIVE_PROPERTY ( LampIntensity,                      _("Lamp intensity"))
    OPM_NATIVE_PROPERTY ( LandingDist,                        _("Landing distance"))
    OPM_NATIVE_PROPERTY ( LandingGap,                         _("Landing gap"))
    OPM_NATIVE_PROPERTY ( Layer,                              _("Layer"))
    OPM_NATIVE_PROPERTY ( LayerFilter,                        _("Layer filter"))
    OPM_NATIVE_PROPERTY ( LayerSnapshot,                      _("Layer snapshot"))
    OPM_NATIVE_PROPERTY ( LayerState,                         _("Layer state"))
    OPM_NATIVE_PROPERTY ( LeaderColor,                        _("Leader color"))
    OPM_NATIVE_PROPERTY ( LeaderArrow,                        _("Leader arrow"))
    OPM_NATIVE_PROPERTY ( LeaderExtentsion,                   _("Leader extension"))
    OPM_NATIVE_PROPERTY ( LeaderIsHorizontal,                 _("Horizontal landing"))
    OPM_NATIVE_PROPERTY ( LeaderLinetype,                     _("Leader linetype"))
    OPM_NATIVE_PROPERTY ( LeaderLineweight,                   _("Leader lineweight"))
    OPM_NATIVE_PROPERTY ( LeaderType,                         _("Type"))
    OPM_NATIVE_PROPERTY ( LeaderType1,                        _("Leader type"))
    OPM_NATIVE_PROPERTY ( LeftAttachment,                     _("Left attachment"))
    OPM_NATIVE_PROPERTY ( LeftExtension,                      _("Left extension"))
    OPM_NATIVE_PROPERTY ( LeftOffset,                         _("Left offset"))
    OPM_NATIVE_PROPERTY ( Length,                             _("Length"))
    OPM_NATIVE_PROPERTY ( LensLength,                         _("Lens length"))
    OPM_NATIVE_PROPERTY ( LightingQuality,                    _("Lighting quality"))
    OPM_NATIVE_PROPERTY ( LightOnOff,                         _("On/Off"))
    OPM_NATIVE_PROPERTY ( LightType,                          _("Type"))
    OPM_NATIVE_PROPERTY ( LimitsDisplay,                      _("Limits display"))
    OPM_NATIVE_PROPERTY ( LinearUnits,                        _("Linear units"))
    OPM_NATIVE_PROPERTY ( LineExtensions,                     _("Line extensions"))
    OPM_NATIVE_PROPERTY ( LineExtensionsOnOff,                _("On/Off"))
    OPM_NATIVE_PROPERTY ( LineSpaceDistance,                  _("Line space distance"))
    OPM_NATIVE_PROPERTY ( LineSpaceFactor,                    _("Line space factor"))
    OPM_NATIVE_PROPERTY ( LineSpaceStyle,                     _("Line space style"))
    OPM_NATIVE_PROPERTY ( Linetype,                           _("Linetype"))
    OPM_NATIVE_PROPERTY ( LinetypeDescription,                _("Linetype description"))
    OPM_NATIVE_PROPERTY ( LinetypeAppearance,                 _("Linetype appearance"))
    OPM_NATIVE_PROPERTY ( LinetypeGeneration,                 _("Linetype generation"))
    OPM_NATIVE_PROPERTY ( LinetypeScale,                      _("Linetype scale"))
    OPM_NATIVE_PROPERTY ( LineWeight,                         _("Lineweight"))
    OPM_NATIVE_PROPERTY ( LiveSection,                        _("Live section"))
    OPM_NATIVE_PROPERTY ( Loaded,                             _("Loaded"))
    OPM_NATIVE_PROPERTY ( LockAspect,                         _("Lock aspect"))
    OPM_NATIVE_PROPERTY ( Locked,                             _("Locked"))
    OPM_NATIVE_PROPERTY ( LockPosition,                       _("Lock position"))
    OPM_NATIVE_PROPERTY ( Lumps,                              _("Lumps"))
    OPM_NATIVE_PROPERTY ( MajorAxisVector,                    _("Major axis vector"))
    OPM_NATIVE_PROPERTY ( MajorRadius,                        _("Major radius"))
    OPM_NATIVE_PROPERTY ( MatchOrientation,                   _("Match orientation to layout"))
    OPM_NATIVE_PROPERTY ( Material,                           _("Material"))
    OPM_NATIVE_PROPERTY ( MaterialDisplay,                    _("Material display"))
    OPM_NATIVE_PROPERTY ( MaterialsOnOff,                     _("On/Off"))
    OPM_NATIVE_PROPERTY ( MaxDepth,                           _("Max depth"))
    OPM_NATIVE_PROPERTY ( MaxZ,                               _("Maximum"))
    OPM_NATIVE_PROPERTY ( MaxReflections,                     _("Max reflections"))
    OPM_NATIVE_PROPERTY ( MaxRefractions,                     _("Max refractions"))
    OPM_NATIVE_PROPERTY ( MClosed,                            _("M closed"))
    OPM_NATIVE_PROPERTY ( MDensity,                           _("M density"))
    OPM_NATIVE_PROPERTY ( Measurement,                        _("Measurement "))
    OPM_NATIVE_PROPERTY ( Measurements,                       _("Measurements"))
    OPM_NATIVE_PROPERTY ( MeshSmoothness,                     _("Smoothness"))
    OPM_NATIVE_PROPERTY ( Method,                             _("Method"))
    OPM_NATIVE_PROPERTY ( MinZ,                               _("Minimum"))
    OPM_NATIVE_PROPERTY ( MinorAxisVector,                    _("Minor axis vector"))
    OPM_NATIVE_PROPERTY ( MinorRadius,                        _("Minor radius"))
    OPM_NATIVE_PROPERTY ( MleaderStyle,                       _("Mleader style"))
    OPM_NATIVE_PROPERTY ( MlineJustification,                 _("Mline justification"))
    OPM_NATIVE_PROPERTY ( MlineStyle,                         _("Mline style"))
    OPM_NATIVE_PROPERTY ( Monochrome,                         _("Monochrome"))
    OPM_NATIVE_PROPERTY ( MonochromeColor,                    _("Monochrome color"))
    OPM_NATIVE_PROPERTY ( MTextAttribute,                     _("Multiple lines"))
    OPM_NATIVE_PROPERTY ( MTextBoundaryWidth,                 _("Boundary width"))
    OPM_NATIVE_PROPERTY ( MTextColumns,                       _("Columns"))
    OPM_NATIVE_PROPERTY ( MTextDirection,                     _("Direction"))
    OPM_NATIVE_PROPERTY ( MTextFrame,                         _("Text frame"))
    OPM_NATIVE_PROPERTY ( MVertexCount,                       _("M vertex count"))
    OPM_NATIVE_PROPERTY ( Name,                               _("Name"))
    OPM_NATIVE_PROPERTY ( NClosed,                            _("N closed"))
    OPM_NATIVE_PROPERTY ( NDensity,                           _("N density"))
    OPM_NATIVE_PROPERTY ( NewVP,                              _("New VP"))
    OPM_NATIVE_PROPERTY ( Normal,                             _("Normal "))
    OPM_NATIVE_PROPERTY ( NumberOfFaces,                      _("Number of faces"))
    OPM_NATIVE_PROPERTY ( NumberOfLines,                      _("Number of lines"))
    OPM_NATIVE_PROPERTY ( NumberOfVertices,                   _("Number of vertices"))
    OPM_NATIVE_PROPERTY ( NVertexCount,                       _("N vertex count"))
    OPM_NATIVE_PROPERTY ( ObjectName,                         _("Object name"))
    OPM_NATIVE_PROPERTY ( Obliquing,                          _("Obliquing"))
    OPM_NATIVE_PROPERTY ( OccludedEdgesColor,                 _("Color"))
    OPM_NATIVE_PROPERTY ( OccludedEdgesLinetype,              _("Linetype"))
    OPM_NATIVE_PROPERTY ( OccludedLinesColor,                 _("Color"))
    OPM_NATIVE_PROPERTY ( Offset,                             _("Offset"))
    OPM_NATIVE_PROPERTY ( OLEType,                            _("Type"))
    OPM_NATIVE_PROPERTY ( OnOff,                              _("On/Off"))
    OPM_NATIVE_PROPERTY ( Opacity,                            _("Opacity"))
    OPM_NATIVE_PROPERTY ( OpacityOnOff,                       _("On/Off"))
    OPM_NATIVE_PROPERTY ( Orientation,                        _("Orientation"))
    OPM_NATIVE_PROPERTY ( Origin,                             _("Origin point"))
    OPM_NATIVE_PROPERTY ( OriginWCS,                          _("Origin (WCS)"))
    OPM_NATIVE_PROPERTY ( OverallScale,                       _("Overall scale"))
    OPM_NATIVE_PROPERTY ( PageNum,                            _("Page number"))
    OPM_NATIVE_PROPERTY ( PageSetup,                          _("Page setup"))
    OPM_NATIVE_PROPERTY ( Parametric,                         _("Parametric"))
    OPM_NATIVE_PROPERTY ( Path,                               _("Path"))
    OPM_NATIVE_PROPERTY ( PatternName,                        _("Pattern name"))
    OPM_NATIVE_PROPERTY ( PatternScale,                       _("Scale"))
    OPM_NATIVE_PROPERTY ( PatternType,                        _("Type"))
    OPM_NATIVE_PROPERTY ( Perimeter,                          _("Perimeter"))
    OPM_NATIVE_PROPERTY ( Periodic,                           _("Periodic"))
    OPM_NATIVE_PROPERTY ( Perspective,                        _("Perspective"))
    OPM_NATIVE_PROPERTY ( Planar,                             _("Planar"))
    OPM_NATIVE_PROPERTY ( PlaneColor,                         _("Plane color"))
    OPM_NATIVE_PROPERTY ( PlaneTransparency,                  _("Plane transparency"))
    OPM_NATIVE_PROPERTY ( Plot,                               _("Plot"))
    OPM_NATIVE_PROPERTY ( PlotGlyph,                          _("Plot glyph"))
    OPM_NATIVE_PROPERTY ( PlotQuality,                        _("Plot quality"))
    OPM_NATIVE_PROPERTY ( PlotSize,                           _("Plot size"))
    OPM_NATIVE_PROPERTY ( PlotStyle,                          _("Plot style"))
    OPM_NATIVE_PROPERTY ( Position,                           _("Position"))
    OPM_NATIVE_PROPERTY ( Position2d,                         _("Position"))
    OPM_NATIVE_PROPERTY ( PositionLight,                      _("Position"))
    OPM_NATIVE_PROPERTY ( PositionPoint,                      _("Position"))
    OPM_NATIVE_PROPERTY ( Preset,                             _("Preset"))
    OPM_NATIVE_PROPERTY ( Prompt,                             _("Prompt"))
    OPM_NATIVE_PROPERTY ( PromptForRotation,                  _("Prompt for rotation"))
    OPM_NATIVE_PROPERTY ( Radius,                             _("Radius"))
    OPM_NATIVE_PROPERTY ( RadiusRatio,                        _("Radius ratio"))
    OPM_NATIVE_PROPERTY ( RayTracingOnOff,                    _("On/Off"))
    OPM_NATIVE_PROPERTY ( RefCount,                           _("Reference count"))
    OPM_NATIVE_PROPERTY ( Reference,                          _("Reference"))
    OPM_NATIVE_PROPERTY ( RestoreColor,                       _("Color"))
    OPM_NATIVE_PROPERTY ( RestoreCurVPFrozenThawed,           _("Current VP frozen/thawed"))
    OPM_NATIVE_PROPERTY ( RestoreFrozenThawed,                _("Frozen/thawed"))
    OPM_NATIVE_PROPERTY ( RestoreLinetype,                    _("Linetype"))
    OPM_NATIVE_PROPERTY ( RestoreLineweight,                  _("Lineweight"))
    OPM_NATIVE_PROPERTY ( RestoreLockedUnlocked,              _("Locked/unlocked"))
    OPM_NATIVE_PROPERTY ( RestoreNewVPFrozenThawed,           _("New VP frozen/thawed"))
    OPM_NATIVE_PROPERTY ( RestoreOnOff,                       _("On/Off"))
    OPM_NATIVE_PROPERTY ( RestorePlotNoPlot,                  _("Plot/No plot"))
    OPM_NATIVE_PROPERTY ( RestorePlotStyle,                   _("Plot style"))
    OPM_NATIVE_PROPERTY ( ResultingColor,                     _("Resulting color"))
    OPM_NATIVE_PROPERTY ( ResultingIntensity,                 _("Resulting intensity"))
    OPM_NATIVE_PROPERTY ( RightAttachment,                    _("Right attachment"))
    OPM_NATIVE_PROPERTY ( RightExtension,                     _("Right extension"))
    OPM_NATIVE_PROPERTY ( RightOffset,                        _("Right offset"))
    OPM_NATIVE_PROPERTY ( RollAngle,                          _("Roll angle"))
    OPM_NATIVE_PROPERTY ( Rotation,                           _("Rotation"))
    OPM_NATIVE_PROPERTY ( Rows,                               _("Rows"))
    OPM_NATIVE_PROPERTY ( RowSpacing,                         _("Row spacing"))
    OPM_NATIVE_PROPERTY ( SavedPath,                          _("Saved path"))
    OPM_NATIVE_PROPERTY ( Scale,                              _("Scale"))
    OPM_NATIVE_PROPERTY ( ScaleHeight,                        _("Scale height %"))
    OPM_NATIVE_PROPERTY ( ScaleWidth,                         _("Scale width %"))
    OPM_NATIVE_PROPERTY ( ScaleX,                             _("Scale X"))
    OPM_NATIVE_PROPERTY ( ScaleY,                             _("Scale Y"))
    OPM_NATIVE_PROPERTY ( ScaleZ,                             _("Scale Z"))
    OPM_NATIVE_PROPERTY ( SecondPoint,                        _("Second point"))
    OPM_NATIVE_PROPERTY ( Server,                             _("Server"))
    OPM_NATIVE_PROPERTY ( ShadePlot,                          _("Shade plot"))
    OPM_NATIVE_PROPERTY ( ShadowDisplay,                      _("Shadow display"))
    OPM_NATIVE_PROPERTY ( ShadowLength,                       _("Length"))
    OPM_NATIVE_PROPERTY ( ShadowMapSize,                      _("Map size"))
    OPM_NATIVE_PROPERTY ( ShadowMapSoftness,                  _("Softness"))
    OPM_NATIVE_PROPERTY ( ShadowRadius,                       _("Radius"))
    OPM_NATIVE_PROPERTY ( ShadowRotation,                     _("Rotation"))
    OPM_NATIVE_PROPERTY ( Shadows,                            _("Shadows"))
    OPM_NATIVE_PROPERTY ( ShadowSamples,                      _("Samples"))
    OPM_NATIVE_PROPERTY ( ShadowShape,                        _("Shape"))
    OPM_NATIVE_PROPERTY ( ShadowsOnOff,                       _("On/Off"))
    OPM_NATIVE_PROPERTY ( ShadowType,                         _("Type"))
    OPM_NATIVE_PROPERTY ( ShadowVisibility,                   _("Visible in render"))
    OPM_NATIVE_PROPERTY ( ShadowWidth,                        _("Width"))
    OPM_NATIVE_PROPERTY ( Show,                               _("Show"))
    OPM_NATIVE_PROPERTY ( ShowIntersectionDisplay,            _("Show"))
    OPM_NATIVE_PROPERTY ( ShowIntersectionEdges,              _("Show"))
    OPM_NATIVE_PROPERTY ( ShowOccludedEdges,                  _("Show"))
    OPM_NATIVE_PROPERTY ( ShowSilhouetteEdges,                _("Show"))
    OPM_NATIVE_PROPERTY ( ShowClipped,                        _("Show clipped"))
    OPM_NATIVE_PROPERTY ( ShowExtensions,                     _("Show extensions"))
    OPM_NATIVE_PROPERTY ( ShowImage,                          _("Show image"))
    OPM_NATIVE_PROPERTY ( ShowParameter,                      _("Show parameter"))
    OPM_NATIVE_PROPERTY ( ShowUnderlay,                       _("Show underlay"))
    OPM_NATIVE_PROPERTY ( SilhouetteWidth,                    _("Width"))
    OPM_NATIVE_PROPERTY ( Size,                               _("Size"))
    OPM_NATIVE_PROPERTY ( Slope,                              _("Slope"))
    OPM_NATIVE_PROPERTY ( SolidSmoothness,                    _("Solid smoothness"))
    OPM_NATIVE_PROPERTY ( SourceApp,                          _("Source application"))
    OPM_NATIVE_PROPERTY ( SourceBlock,                        _("Source block"))
    OPM_NATIVE_PROPERTY ( SourceVector,                       _("Source vector"))
    OPM_NATIVE_PROPERTY ( Space,                              _("Space"))
    OPM_NATIVE_PROPERTY ( Spacing,                            _("Spacing"))
    OPM_NATIVE_PROPERTY ( SplineSegments,                     _("Spline segments"))
    OPM_NATIVE_PROPERTY ( SsCalloutBlocks,                    _("Callout blocks"))
    OPM_NATIVE_PROPERTY ( SsCustomSheet,                      _T("CUSTOM PROP SHEET"))
    OPM_NATIVE_PROPERTY ( SsCustomSheetSet,                   _T("CUSTOM PROP SHEETSET"))
    OPM_NATIVE_PROPERTY ( SsDescription,                      _("Description"))
    OPM_NATIVE_PROPERTY ( SsFilePath,                         _("File path"))
    OPM_NATIVE_PROPERTY ( SsIssuePurpose,                     _("Issue purpose"))
    OPM_NATIVE_PROPERTY ( SsLockStatus,                       _("Status"))
    OPM_NATIVE_PROPERTY ( SsName,                             _("Name"))
    OPM_NATIVE_PROPERTY ( SsNewSheetLocation,                 _("New sheet location"))
    OPM_NATIVE_PROPERTY ( SsOverrideSheetPublish,             _("Publish sheets in subset"))
    OPM_NATIVE_PROPERTY ( SsProjectMilestone,                 _("Project milestone"))
    OPM_NATIVE_PROPERTY ( SsProjectName,                      _("Project name"))
    OPM_NATIVE_PROPERTY ( SsProjectNumber,                    _("Project number"))
    OPM_NATIVE_PROPERTY ( SsProjectPhase,                     _("Project phase"))
    OPM_NATIVE_PROPERTY ( SsPrompt,                           _("Prompt"))
    OPM_NATIVE_PROPERTY ( SsPublish,                          _("Publish"))
    OPM_NATIVE_PROPERTY ( SsRevisionDate,                     _("Revision date"))
    OPM_NATIVE_PROPERTY ( SsRevisionNumber,                   _("Revision number"))
    OPM_NATIVE_PROPERTY ( SsSheetCategory,                    _("Category"))
    OPM_NATIVE_PROPERTY ( SsSheetCount,                       _("Total sheets"))
    OPM_NATIVE_PROPERTY ( SsSheetLayout,                      _("Layout"))
    OPM_NATIVE_PROPERTY ( SsSheetNumber,                      _("Number"))
    OPM_NATIVE_PROPERTY ( SsSheetTitle,                       _("Title"))
    OPM_NATIVE_PROPERTY ( SsTemplateLayout,                   _("Sheet template layout"))
    OPM_NATIVE_PROPERTY ( SsViewCategory,                     _("Category"))
    OPM_NATIVE_PROPERTY ( SsViewLabelBlock,                   _("View label block"))
    OPM_NATIVE_PROPERTY ( SsViewNumber,                       _("Number"))
    OPM_NATIVE_PROPERTY ( SsViewTitle,                        _("Title"))
    OPM_NATIVE_PROPERTY ( StandardScale,                      _("Standard scale"))
    OPM_NATIVE_PROPERTY ( StartAngle,                         _("Start angle"))
    OPM_NATIVE_PROPERTY ( StartExtension,                     _("Start extension"))
    OPM_NATIVE_PROPERTY ( StartLimitOffset,                   _("Start limit offset"))
    OPM_NATIVE_PROPERTY ( StartPoint,                         _("Start point"))
    OPM_NATIVE_PROPERTY ( StartSegmentWidth,                  _("Start width"))
    OPM_NATIVE_PROPERTY ( StartTangent,                       _("Start tangent"))
    OPM_NATIVE_PROPERTY ( State,                              _("State"))
    OPM_NATIVE_PROPERTY ( Status,                             _("Status"))
    OPM_NATIVE_PROPERTY ( Style,                              _("Style"))
    OPM_NATIVE_PROPERTY ( SuppressAngleLeadingZeros,          _("Suppress angle leading zeros"))
    OPM_NATIVE_PROPERTY ( SuppressAngleTrailingZeros,         _("Suppress angle trailing zeros"))
    OPM_NATIVE_PROPERTY ( SuppressEndCaps,                    _("Suppress end caps"))
    OPM_NATIVE_PROPERTY ( SuppressLeadingZeros,               _("Suppress leading zeros"))
    OPM_NATIVE_PROPERTY ( SuppressStartCaps,                  _("Suppress start caps"))
    OPM_NATIVE_PROPERTY ( SuppressTrailingZeros,              _("Suppress trailing zeros"))
    OPM_NATIVE_PROPERTY ( SuppressZeroFeet,                   _("Suppress zero feet"))
    OPM_NATIVE_PROPERTY ( SuppressZeroInches,                 _("Suppress zero inches"))
    OPM_NATIVE_PROPERTY ( SurfaceUIsolines,                   _("Surface U isolines"))
    OPM_NATIVE_PROPERTY ( SurfaceVIsolines,                   _("Surface V isolines"))
    OPM_NATIVE_PROPERTY ( TableBreakFlowDirection,            _("Direction"))
    OPM_NATIVE_PROPERTY ( TableBreakHeight,                   _("Break height"))
    OPM_NATIVE_PROPERTY ( TableBreaksEnabled,                 _("Enabled"))
    OPM_NATIVE_PROPERTY ( TableBreakSpacing,                  _("Spacing"))
    OPM_NATIVE_PROPERTY ( TableColumns,                       _("Columns"))
    OPM_NATIVE_PROPERTY ( TableDirection,                     _("Direction"))
    OPM_NATIVE_PROPERTY ( TableHorizontalCellMargin,          _("Horizontal cell margin"))
    OPM_NATIVE_PROPERTY ( TableManualHeights,                 _("Manual heights"))
    OPM_NATIVE_PROPERTY ( TableManualPositions,               _("Manual positions"))
    OPM_NATIVE_PROPERTY ( TableRepeatBottomLabels,            _("Repeat bottom labels"))
    OPM_NATIVE_PROPERTY ( TableRepeatTopLabels,               _("Repeat top labels"))
    OPM_NATIVE_PROPERTY ( TableRows,                          _("Rows"))
    OPM_NATIVE_PROPERTY ( TableVerticalCellMargin,            _("Vertical cell margin"))
    OPM_NATIVE_PROPERTY ( Tag,                                _("Tag"))
    OPM_NATIVE_PROPERTY ( TangencyColor,                      _("Color"))
    OPM_NATIVE_PROPERTY ( TangencyLayer,                      _("Layer"))
    OPM_NATIVE_PROPERTY ( TangencyLinetype,                   _("Linetype"))
    OPM_NATIVE_PROPERTY ( TangencyLinetypeScale,              _("Linetype scale"))
    OPM_NATIVE_PROPERTY ( TangencyLineweight,                 _("Lineweight"))
    OPM_NATIVE_PROPERTY ( TangencyPlotStyle,                  _("Plot style"))
    OPM_NATIVE_PROPERTY ( TangencyVisibility,                 _("Show"))
    OPM_NATIVE_PROPERTY ( Target,                             _("Target"))
    OPM_NATIVE_PROPERTY ( Targeted,                           _("Targeted"))
    OPM_NATIVE_PROPERTY ( TextAlignment,                      _("Text alignment"))
    OPM_NATIVE_PROPERTY ( TextColor,                          _("Text color"))
    OPM_NATIVE_PROPERTY ( TextFill,                           _("Text fill"))
    OPM_NATIVE_PROPERTY ( TextFillColor,                      _("Text fill color"))
    OPM_NATIVE_PROPERTY ( TextFrame,                          _("Draw frame around text"))
    OPM_NATIVE_PROPERTY ( TextFrameType,                      _("Frame type around text"))
    OPM_NATIVE_PROPERTY ( TextHeight,                         _("Text height"))
    OPM_NATIVE_PROPERTY ( TextInside,                         _("Text inside"))
    OPM_NATIVE_PROPERTY ( TextInsideAlign,                    _("Text inside align"))
    OPM_NATIVE_PROPERTY ( TextMovement,                       _("Text movement"))
    OPM_NATIVE_PROPERTY ( TextOffset,                         _("Text offset"))
    OPM_NATIVE_PROPERTY ( TextOutsideAlign,                   _("Text outside align"))
    OPM_NATIVE_PROPERTY ( TextOverride,                       _("Text override"))
    OPM_NATIVE_PROPERTY ( TextPlaceManually,                  _("Place text manually"))
    OPM_NATIVE_PROPERTY ( TextPosHor,                         _("Text position horizontal"))
    OPM_NATIVE_PROPERTY ( TextPositionX,                      _("Text position X"))
    OPM_NATIVE_PROPERTY ( TextPositionY,                      _("Text position Y"))
    OPM_NATIVE_PROPERTY ( TextPosVert,                        _("Text position vertical"))
    OPM_NATIVE_PROPERTY ( TextRotation,                       _("Text rotation"))
    OPM_NATIVE_PROPERTY ( TextStyle,                          _("Text style"))
    OPM_NATIVE_PROPERTY ( TextVerticalOffset,                 _("Text vertical offset"))
    OPM_NATIVE_PROPERTY ( TextViewDirection,                  _("Text view direction"))
    OPM_NATIVE_PROPERTY ( Thickness,                          _("Thickness"))
    OPM_NATIVE_PROPERTY ( TickSize,                           _("Tick size"))
    OPM_NATIVE_PROPERTY ( TileOrder,                          _("Tile order"))
    OPM_NATIVE_PROPERTY ( TileSize,                           _("Tile size"))
    OPM_NATIVE_PROPERTY ( Time,                               _("Time"))
    OPM_NATIVE_PROPERTY ( TintColor,                          _("Tint color"))
    OPM_NATIVE_PROPERTY ( ToleranceAnglePrecision,            _("Tolerance precision"))
    OPM_NATIVE_PROPERTY ( ToleranceDisplay,                   _("Tolerance display"))
    OPM_NATIVE_PROPERTY ( ToleranceLimitLower,                _("Tolerance limit lower"))
    OPM_NATIVE_PROPERTY ( ToleranceLimitUpper,                _("Tolerance limit upper"))
    OPM_NATIVE_PROPERTY ( TolerancePosVert,                   _("Tolerance position vertical"))
    OPM_NATIVE_PROPERTY ( TolerancePrecision,                 _("Tolerance precision"))
    OPM_NATIVE_PROPERTY ( ToleranceSuppressLeadingZeros,      _("Tolerance suppress leading zeros"))
    OPM_NATIVE_PROPERTY ( ToleranceSuppressTrailingZeros,     _("Tolerance suppress trailing zeros"))
    OPM_NATIVE_PROPERTY ( ToleranceSuppressZeroFeet,          _("Tolerance suppress zero feet"))
    OPM_NATIVE_PROPERTY ( ToleranceSuppressZeroInches,        _("Tolerance suppress zero inches"))
    OPM_NATIVE_PROPERTY ( ToleranceTextHeight,                _("Tolerance text height"))
    OPM_NATIVE_PROPERTY ( TopAttachment,                      _("Top attachment"))
    OPM_NATIVE_PROPERTY ( TopExtension,                       _("Top extension"))
    OPM_NATIVE_PROPERTY ( TopPlane,                           _("Top plane"))
    OPM_NATIVE_PROPERTY ( TopRadius,                          _("Top radius"))
    OPM_NATIVE_PROPERTY ( TotalAngle,                         _("Total angle"))
    OPM_NATIVE_PROPERTY ( TotalLength,                        _("Total length"))
    OPM_NATIVE_PROPERTY ( ToVector,                           _("To vector"))
    OPM_NATIVE_PROPERTY ( Transparency,                       _("Transparency"))
    OPM_NATIVE_PROPERTY ( TransparencyDepth,                  _("Transparency depth"))
    OPM_NATIVE_PROPERTY ( TurnHeight,                         _("Turn height"))
    OPM_NATIVE_PROPERTY ( Turns,                              _("Turns"))
    OPM_NATIVE_PROPERTY ( TurnSlope,                          _("Turn slope"))
    OPM_NATIVE_PROPERTY ( Twist,                              _("Twist"))
    OPM_NATIVE_PROPERTY ( Type,                               _("Type"))
    OPM_NATIVE_PROPERTY ( UCS,                                _("UCS"))
    OPM_NATIVE_PROPERTY ( UCSElevation,                       _("UCS elevation"))
    OPM_NATIVE_PROPERTY ( UCSPerViewport,                     _("UCS per viewport"))
    OPM_NATIVE_PROPERTY ( UnitsFactor,                        _("Unit factor"))
    OPM_NATIVE_PROPERTY ( Update,                             _("Update"))
    OPM_NATIVE_PROPERTY ( UpsideDown,                         _("Upside down"))
    OPM_NATIVE_PROPERTY ( Used,                               _("Used"))
    OPM_NATIVE_PROPERTY ( UseLids,                            _("Use lids"))
    OPM_NATIVE_PROPERTY ( UseLimits,                          _("Use limits"))
    OPM_NATIVE_PROPERTY ( UseOneColor,                        _("Use one color"))
    OPM_NATIVE_PROPERTY ( Value,                              _("Value"))
    OPM_NATIVE_PROPERTY ( Verify,                             _("Verify"))
    OPM_NATIVE_PROPERTY ( Vertex,                             _("Vertex"))
    OPM_NATIVE_PROPERTY ( Vertices,                           _("Vertices"))
    OPM_NATIVE_PROPERTY ( View,                               _("View"))
    OPM_NATIVE_PROPERTY ( ViewDirection,                      _("View direction"))
    OPM_NATIVE_PROPERTY ( ViewportOn,                         _("On"))
    OPM_NATIVE_PROPERTY ( VisualStyle,                        _("Visual style"))
    OPM_NATIVE_PROPERTY ( Volume,                             _("Volume"))
    OPM_NATIVE_PROPERTY ( VpFreeze,                           _("VP freeze"))
    OPM_NATIVE_PROPERTY ( VpColor,                            _("VP color"))
    OPM_NATIVE_PROPERTY ( VpLinetype,                         _("VP linetype"))
    OPM_NATIVE_PROPERTY ( VpLineWeight,                       _("VP lineweight"))
    OPM_NATIVE_PROPERTY ( VpPlotStyle,                        _("VP plotStyle"))
    OPM_NATIVE_PROPERTY ( VpTransparency,                     _("VP transparency"))
    OPM_NATIVE_PROPERTY ( Watertight,                         _("Watertight"))
    OPM_NATIVE_PROPERTY ( WebFile,                            _("Web file"))
    OPM_NATIVE_PROPERTY ( Weight,                             _("Weight"))
    OPM_NATIVE_PROPERTY ( Width,                              _("Width"))
    OPM_NATIVE_PROPERTY ( WidthFactor,                        _("Width factor"))
    OPM_NATIVE_PROPERTY ( Workspace,                          _("Workspace"))
    OPM_NATIVE_PROPERTY ( X,                                  _("X"))
    OPM_NATIVE_PROPERTY ( XAxisDir,                           _("X axis direction (WCS)"))
    OPM_NATIVE_PROPERTY ( Y,                                  _("Y"))
    OPM_NATIVE_PROPERTY ( YAxisDir,                           _("Y axis direction (WCS)"))
    OPM_NATIVE_PROPERTY ( Z,                                  _("Z"))

    // add new entries *HERE* during V23 lifetime
    OPM_NATIVE_PROPERTY ( ArrayPolarItems,                    _("Items"))
    OPM_NATIVE_PROPERTY ( CellContentBlockColor,              _("Block color"))
    OPM_NATIVE_PROPERTY ( CellContentDataType,                _("Data type"))

    acOpmId_PermanentPropEnd // last ID
};

#undef OPM_NATIVE_PROPERTY
