// Property of Bricsys NV. All rights reserved.
// This file is part of the BRX SDK, and its use is subject to the terms
// of the BRX SDK license agreement.
/////////////////////////////////////////////////////////////////////////

virtual Acad::ErrorStatus setDimadec(int);
virtual Acad::ErrorStatus setDimalt(bool);
virtual Acad::ErrorStatus setDimaltd(int);
virtual Acad::ErrorStatus setDimaltf(double);
virtual Acad::ErrorStatus setDimaltrnd(double);
virtual Acad::ErrorStatus setDimalttd(int);
virtual Acad::ErrorStatus setDimalttz(int);
virtual Acad::ErrorStatus setDimaltu(int);
virtual Acad::ErrorStatus setDimaltz(int);
virtual Acad::ErrorStatus setDimapost(const ACHAR*);
virtual Acad::ErrorStatus setDimarcsym(int);
virtual Acad::ErrorStatus setDimasz(double);
virtual Acad::ErrorStatus setDimatfit(int);
virtual Acad::ErrorStatus setDimaunit(int);
virtual Acad::ErrorStatus setDimazin(int);
virtual Acad::ErrorStatus setDimblk(AcDbObjectId);
virtual Acad::ErrorStatus setDimblk(const ACHAR*);
virtual Acad::ErrorStatus setDimblk1(AcDbObjectId);
virtual Acad::ErrorStatus setDimblk1(const ACHAR*);
virtual Acad::ErrorStatus setDimblk2(AcDbObjectId);
virtual Acad::ErrorStatus setDimblk2(const ACHAR*);
virtual Acad::ErrorStatus setDimcen(double);
virtual Acad::ErrorStatus setDimclrd(const AcCmColor&);
virtual Acad::ErrorStatus setDimclre(const AcCmColor&);
virtual Acad::ErrorStatus setDimclrt(const AcCmColor&);
virtual Acad::ErrorStatus setDimdec(int);
virtual Acad::ErrorStatus setDimdle(double);
virtual Acad::ErrorStatus setDimdli(double);
virtual Acad::ErrorStatus setDimdsep(ACHAR);
virtual Acad::ErrorStatus setDimexe(double);
virtual Acad::ErrorStatus setDimexo(double);
virtual Acad::ErrorStatus setDimfrac(int);
virtual Acad::ErrorStatus setDimfxlen(double);
virtual Acad::ErrorStatus setDimfxlenOn(bool);
virtual Acad::ErrorStatus setDimgap(double);
virtual Acad::ErrorStatus setDimjogang(double);
virtual Acad::ErrorStatus setDimjust(int);
virtual Acad::ErrorStatus setDimldrblk(AcDbObjectId);
virtual Acad::ErrorStatus setDimldrblk(const ACHAR*);
virtual Acad::ErrorStatus setDimlfac(double);
virtual Acad::ErrorStatus setDimlim(bool);
virtual Acad::ErrorStatus setDimltex1(AcDbObjectId);
virtual Acad::ErrorStatus setDimltex2(AcDbObjectId);
virtual Acad::ErrorStatus setDimltype(AcDbObjectId);
virtual Acad::ErrorStatus setDimlunit(int);
virtual Acad::ErrorStatus setDimlwd(AcDb::LineWeight);
virtual Acad::ErrorStatus setDimlwe(AcDb::LineWeight);
virtual Acad::ErrorStatus setDimpost(const ACHAR*);
virtual Acad::ErrorStatus setDimrnd(double);
virtual Acad::ErrorStatus setDimsah(bool);
virtual Acad::ErrorStatus setDimscale(double);
virtual Acad::ErrorStatus setDimsd1(bool);
virtual Acad::ErrorStatus setDimsd2(bool);
virtual Acad::ErrorStatus setDimse1(bool);
virtual Acad::ErrorStatus setDimse2(bool);
virtual Acad::ErrorStatus setDimsoxd(bool);
virtual Acad::ErrorStatus setDimtad(int);
virtual Acad::ErrorStatus setDimtdec(int);
virtual Acad::ErrorStatus setDimtfac(double);
virtual Acad::ErrorStatus setDimtfill(int);
virtual Acad::ErrorStatus setDimtfillclr(const AcCmColor&);
virtual Acad::ErrorStatus setDimtih(bool);
virtual Acad::ErrorStatus setDimtix(bool);
virtual Acad::ErrorStatus setDimtm(double);
virtual Acad::ErrorStatus setDimtmove(int);
virtual Acad::ErrorStatus setDimtofl(bool);
virtual Acad::ErrorStatus setDimtoh(bool);
virtual Acad::ErrorStatus setDimtol(bool);
virtual Acad::ErrorStatus setDimtolj(int);
virtual Acad::ErrorStatus setDimtp(double);
virtual Acad::ErrorStatus setDimtsz(double);
virtual Acad::ErrorStatus setDimtvp(double);
virtual Acad::ErrorStatus setDimtxsty(AcDbObjectId);
virtual Acad::ErrorStatus setDimtxt(double);
virtual Acad::ErrorStatus setDimtzin(int);
virtual Acad::ErrorStatus setDimupt(bool);
virtual Acad::ErrorStatus setDimzin(int);
virtual Acad::ErrorStatus setDimtxtdirection(bool);
virtual Acad::ErrorStatus setDimmzf(double);
virtual Acad::ErrorStatus setDimmzs(const ACHAR*);
virtual Acad::ErrorStatus setDimaltmzf(double);
virtual Acad::ErrorStatus setDimaltmzs(const ACHAR*);
virtual AcCmColor dimclrd() const;
virtual AcCmColor dimclre() const;
virtual AcCmColor dimclrt() const;
virtual AcCmColor dimtfillclr() const;
virtual AcDb::LineWeight dimlwd() const;
virtual AcDb::LineWeight dimlwe() const;
virtual AcDbObjectId dimblk() const;
virtual AcDbObjectId dimblk1() const;
virtual AcDbObjectId dimblk2() const;
virtual AcDbObjectId dimldrblk() const;
virtual AcDbObjectId dimltex1() const;
virtual AcDbObjectId dimltex2() const;
virtual AcDbObjectId dimltype() const;
virtual AcDbObjectId dimtxsty() const;
virtual ACHAR dimdsep() const;
virtual bool dimalt() const;
virtual bool dimfxlenOn() const;
virtual bool dimlim() const;
virtual bool dimsah() const;
virtual bool dimsd1() const;
virtual bool dimsd2() const;
virtual bool dimse1() const;
virtual bool dimse2() const;
virtual bool dimsoxd() const;
virtual bool dimtih() const;
virtual bool dimtix() const;
virtual bool dimtofl() const;
virtual bool dimtoh() const;
virtual bool dimtol() const;
virtual bool dimupt() const;
virtual const ACHAR* dimapost() const;
virtual const ACHAR* dimpost() const;
virtual double dimaltf() const;
virtual double dimaltrnd() const;
virtual double dimasz() const;
virtual double dimcen() const;
virtual double dimdle() const;
virtual double dimdli() const;
virtual double dimexe() const;
virtual double dimexo() const;
virtual double dimfxlen() const;
virtual double dimgap() const;
virtual double dimjogang() const;
virtual double dimlfac() const;
virtual double dimrnd() const;
virtual double dimscale() const;
virtual double dimtfac() const;
virtual double dimtm() const;
virtual double dimtp() const;
virtual double dimtsz() const;
virtual double dimtvp() const;
virtual double dimtxt() const;
virtual int dimadec() const;
virtual int dimaltd() const;
virtual int dimalttd() const;
virtual int dimalttz() const;
virtual int dimaltu() const;
virtual int dimaltz() const;
virtual int dimarcsym() const;
virtual int dimatfit() const;
virtual int dimaunit() const;
virtual int dimazin() const;
virtual int dimdec() const;
virtual int dimfrac() const;
virtual int dimjust() const;
virtual int dimlunit() const;
virtual int dimtad() const;
virtual int dimtdec() const;
virtual int dimtfill() const;
virtual int dimtmove() const;
virtual int dimtolj() const;
virtual int dimtzin() const;
virtual int dimzin() const;
virtual bool dimtxtdirection() const;
virtual double dimmzf() const;
virtual const ACHAR* dimmzs() const;
virtual double dimaltmzf() const;
virtual const ACHAR* dimaltmzs() const;
