[package]
name = "xcad"
version = "1.0.0"
edition = "2021"
authors = ["XodiumSoftware <https://xodium.org/>"]
description = "CAD addon/plug-in providing automative tools."
license = "AGPL-3.0"
repository = "https://github.com/XodiumSoftware/xCAD"
keywords = ["Produce at lightspeed"]
categories = ["development-tools::bindings", "asynchronous"]
homepage = "https://xodium.org/"
documentation = "https://wiki.xodium.org/xCAD"
publish = true

[dependencies]
slint = "1.7.2"

[build-dependencies]
slint-build = "1.7.2"
