// Property of Bricsys NV. All rights reserved.
// This file is part of the BRX SDK, and its use is subject to the terms
// of the BRX SDK license agreement.
/////////////////////////////////////////////////////////////////////////

#undef ATTRIBUTES_LIST
#define ATTRIBUTES_LIST()\
ON_ATTRIBUTE(AccessState)\
ON_ATTRIBUTE(AcidityConcentration)\
ON_ATTRIBUTE(ActingRole)\
ON_ATTRIBUTE(ActionID)\
ON_ATTRIBUTE(ActionSource)\
ON_ATTRIBUTE(ActionType)\
ON_ATTRIBUTE(Actor)\
ON_ATTRIBUTE(ActualDate)\
ON_ATTRIBUTE(ActualDuration)\
ON_ATTRIBUTE(ActualFinish)\
ON_ATTRIBUTE(ActualStart)\
ON_ATTRIBUTE(ActualUsage)\
ON_ATTRIBUTE(ActualWork)\
ON_ATTRIBUTE(AdditionalConditions)\
ON_ATTRIBUTE(AddressLines)\
ON_ATTRIBUTE(Addresses)\
ON_ATTRIBUTE(AdmixturesDescription)\
ON_ATTRIBUTE(AgreementFlag)\
ON_ATTRIBUTE(AlkalinityConcentration)\
ON_ATTRIBUTE(AlongHorizontal)\
ON_ATTRIBUTE(AmbientIntensity)\
ON_ATTRIBUTE(AmountOfSubstanceExponent)\
ON_ATTRIBUTE(AnchorageSlip)\
ON_ATTRIBUTE(Angle)\
ON_ATTRIBUTE(AnnotatedCurve)\
ON_ATTRIBUTE(ApplicableDate)\
ON_ATTRIBUTE(ApplicableDates)\
ON_ATTRIBUTE(ApplicableEntity)\
ON_ATTRIBUTE(ApplicableOccurrence)\
ON_ATTRIBUTE(ApplicableValueRatio)\
ON_ATTRIBUTE(ApplicationDeveloper)\
ON_ATTRIBUTE(ApplicationFullName)\
ON_ATTRIBUTE(ApplicationIdentifier)\
ON_ATTRIBUTE(AppliedCondition)\
ON_ATTRIBUTE(AppliedLoad)\
ON_ATTRIBUTE(AppliedValue)\
ON_ATTRIBUTE(Approval)\
ON_ATTRIBUTE(ApprovalDateTime)\
ON_ATTRIBUTE(ApprovalLevel)\
ON_ATTRIBUTE(ApprovalQualifier)\
ON_ATTRIBUTE(ApprovalStatus)\
ON_ATTRIBUTE(ApprovedProperties)\
ON_ATTRIBUTE(AreaValue)\
ON_ATTRIBUTE(ArithmeticOperator)\
ON_ATTRIBUTE(AssemblyPlace)\
ON_ATTRIBUTE(AssetID)\
ON_ATTRIBUTE(AssignedItems)\
ON_ATTRIBUTE(AssociatedGeometry)\
ON_ATTRIBUTE(AttributeIdentifier)\
ON_ATTRIBUTE(Axis)\
ON_ATTRIBUTE(Axis1)\
ON_ATTRIBUTE(Axis2)\
ON_ATTRIBUTE(Axis3)\
ON_ATTRIBUTE(AxisCurve)\
ON_ATTRIBUTE(AxisPosition)\
ON_ATTRIBUTE(AxisTag)\
ON_ATTRIBUTE(BackgroundColour)\
ON_ATTRIBUTE(BarCount)\
ON_ATTRIBUTE(BarLength)\
ON_ATTRIBUTE(BarRole)\
ON_ATTRIBUTE(BarSurface)\
ON_ATTRIBUTE(BaseCosts)\
ON_ATTRIBUTE(BaseDepth1)\
ON_ATTRIBUTE(BaseDepth2)\
ON_ATTRIBUTE(BaseDepth3)\
ON_ATTRIBUTE(BaseQuantity)\
ON_ATTRIBUTE(BaseSurface)\
ON_ATTRIBUTE(BaseWidth2)\
ON_ATTRIBUTE(BaseWidth4)\
ON_ATTRIBUTE(BasisCurve)\
ON_ATTRIBUTE(BasisSurface)\
ON_ATTRIBUTE(BeamWidthAngle)\
ON_ATTRIBUTE(Benchmark)\
ON_ATTRIBUTE(BenchmarkValues)\
ON_ATTRIBUTE(BendingParameters)\
ON_ATTRIBUTE(BendingShapeCode)\
ON_ATTRIBUTE(Blue)\
ON_ATTRIBUTE(BoilingPoint)\
ON_ATTRIBUTE(BottomFlangeEdgeRadius)\
ON_ATTRIBUTE(BottomFlangeFilletRadius)\
ON_ATTRIBUTE(BottomFlangeSlope)\
ON_ATTRIBUTE(BottomFlangeThickness)\
ON_ATTRIBUTE(BottomFlangeWidth)\
ON_ATTRIBUTE(BottomRadius)\
ON_ATTRIBUTE(BottomXDim)\
ON_ATTRIBUTE(Bound)\
ON_ATTRIBUTE(Boundaries)\
ON_ATTRIBUTE(Bounds)\
ON_ATTRIBUTE(BoxAlignment)\
ON_ATTRIBUTE(BoxHeight)\
ON_ATTRIBUTE(BoxRotateAngle)\
ON_ATTRIBUTE(BoxSlantAngle)\
ON_ATTRIBUTE(BoxWidth)\
ON_ATTRIBUTE(BuildingAddress)\
ON_ATTRIBUTE(CO2Content)\
ON_ATTRIBUTE(COContent)\
ON_ATTRIBUTE(CapacityByNumber)\
ON_ATTRIBUTE(CapacityByWeight)\
ON_ATTRIBUTE(CarbonContent)\
ON_ATTRIBUTE(CardinalEndPoint)\
ON_ATTRIBUTE(CardinalPoint)\
ON_ATTRIBUTE(CartesianPosition)\
ON_ATTRIBUTE(CasingDepth)\
ON_ATTRIBUTE(CasingThickness)\
ON_ATTRIBUTE(Category)\
ON_ATTRIBUTE(CausedBy)\
ON_ATTRIBUTE(CentreOfGravityInX)\
ON_ATTRIBUTE(CentreOfGravityInY)\
ON_ATTRIBUTE(CfsFaces)\
ON_ATTRIBUTE(ChangeAction)\
ON_ATTRIBUTE(CharacterSpacing)\
ON_ATTRIBUTE(ClassifiedConstraint)\
ON_ATTRIBUTE(ClassifiedMaterial)\
ON_ATTRIBUTE(Closed)\
ON_ATTRIBUTE(ClosedCurve)\
ON_ATTRIBUTE(Coefficient)\
ON_ATTRIBUTE(Colour)\
ON_ATTRIBUTE(ColourAppearance)\
ON_ATTRIBUTE(ColourComponents)\
ON_ATTRIBUTE(ColourIndex)\
ON_ATTRIBUTE(ColourList)\
ON_ATTRIBUTE(ColourTemperature)\
ON_ATTRIBUTE(Colours)\
ON_ATTRIBUTE(Columns)\
ON_ATTRIBUTE(CombustionTemperature)\
ON_ATTRIBUTE(Completion)\
ON_ATTRIBUTE(ComponentOfTotal)\
ON_ATTRIBUTE(Components)\
ON_ATTRIBUTE(CompositeProfile)\
ON_ATTRIBUTE(CompositionType)\
ON_ATTRIBUTE(CompressionFailureX)\
ON_ATTRIBUTE(CompressionFailureY)\
ON_ATTRIBUTE(CompressionFailureZ)\
ON_ATTRIBUTE(CompressiveStrength)\
ON_ATTRIBUTE(ConcentrationExponent)\
ON_ATTRIBUTE(Condition)\
ON_ATTRIBUTE(ConditionCoordinateSystem)\
ON_ATTRIBUTE(Confidentiality)\
ON_ATTRIBUTE(ConnectionConstraint)\
ON_ATTRIBUTE(ConnectionGeometry)\
ON_ATTRIBUTE(ConnectionType)\
ON_ATTRIBUTE(ConstantAttenuation)\
ON_ATTRIBUTE(ConstraintGrade)\
ON_ATTRIBUTE(ConstraintSource)\
ON_ATTRIBUTE(ConstructionType)\
ON_ATTRIBUTE(Contents)\
ON_ATTRIBUTE(ContextIdentifier)\
ON_ATTRIBUTE(ContextOfItems)\
ON_ATTRIBUTE(ContextType)\
ON_ATTRIBUTE(ControlElementId)\
ON_ATTRIBUTE(ControlPointsList)\
ON_ATTRIBUTE(ConversionFactor)\
ON_ATTRIBUTE(ConversionOffset)\
ON_ATTRIBUTE(CoordIndex)\
ON_ATTRIBUTE(CoordList)\
ON_ATTRIBUTE(CoordinateSpaceDimension)\
ON_ATTRIBUTE(Coordinates)\
ON_ATTRIBUTE(Corner)\
ON_ATTRIBUTE(CorrespondingBoundary)\
ON_ATTRIBUTE(CostQuantities)\
ON_ATTRIBUTE(CostType)\
ON_ATTRIBUTE(CostValues)\
ON_ATTRIBUTE(CountValue)\
ON_ATTRIBUTE(Country)\
ON_ATTRIBUTE(CreatingActor)\
ON_ATTRIBUTE(CreationDate)\
ON_ATTRIBUTE(CreationTime)\
ON_ATTRIBUTE(Creators)\
ON_ATTRIBUTE(Criterion)\
ON_ATTRIBUTE(CriterionDateTime)\
ON_ATTRIBUTE(CrossSectionArea)\
ON_ATTRIBUTE(CrossSectionPositions)\
ON_ATTRIBUTE(CrossSectionReinforcementDefinitions)\
ON_ATTRIBUTE(CrossSections)\
ON_ATTRIBUTE(Currency)\
ON_ATTRIBUTE(CurrentValue)\
ON_ATTRIBUTE(Curve)\
ON_ATTRIBUTE(Curve3D)\
ON_ATTRIBUTE(CurveColour)\
ON_ATTRIBUTE(CurveFont)\
ON_ATTRIBUTE(CurveFontScaling)\
ON_ATTRIBUTE(CurveForm)\
ON_ATTRIBUTE(CurveGeometry)\
ON_ATTRIBUTE(CurveInterpolation)\
ON_ATTRIBUTE(CurveOnRelatedElement)\
ON_ATTRIBUTE(CurveOnRelatingElement)\
ON_ATTRIBUTE(CurveWidth)\
ON_ATTRIBUTE(DailyInteraction)\
ON_ATTRIBUTE(DataOrigin)\
ON_ATTRIBUTE(DataValue)\
ON_ATTRIBUTE(DateComponent)\
ON_ATTRIBUTE(DayComponent)\
ON_ATTRIBUTE(DaylightSavingOffset)\
ON_ATTRIBUTE(DefinedUnit)\
ON_ATTRIBUTE(DefinedValues)\
ON_ATTRIBUTE(DefiningUnit)\
ON_ATTRIBUTE(DefiningValues)\
ON_ATTRIBUTE(Definition)\
ON_ATTRIBUTE(DefinitionType)\
ON_ATTRIBUTE(Degree)\
ON_ATTRIBUTE(DeltaTConstant)\
ON_ATTRIBUTE(DeltaTY)\
ON_ATTRIBUTE(DeltaTZ)\
ON_ATTRIBUTE(DeltaT_Constant)\
ON_ATTRIBUTE(DeltaT_Y)\
ON_ATTRIBUTE(DeltaT_Z)\
ON_ATTRIBUTE(DependantProperty)\
ON_ATTRIBUTE(DependingProperty)\
ON_ATTRIBUTE(DepreciatedValue)\
ON_ATTRIBUTE(Depth)\
ON_ATTRIBUTE(Description)\
ON_ATTRIBUTE(DestabilizingLoad)\
ON_ATTRIBUTE(DiffuseColour)\
ON_ATTRIBUTE(DiffuseReflectionColour)\
ON_ATTRIBUTE(DiffuseTransmissionColour)\
ON_ATTRIBUTE(Dimensions)\
ON_ATTRIBUTE(Dir)\
ON_ATTRIBUTE(Direction)\
ON_ATTRIBUTE(DirectionRatios)\
ON_ATTRIBUTE(DirectionSense)\
ON_ATTRIBUTE(Directrix)\
ON_ATTRIBUTE(Discrimination)\
ON_ATTRIBUTE(DispersionFactor)\
ON_ATTRIBUTE(DisplacementX)\
ON_ATTRIBUTE(DisplacementY)\
ON_ATTRIBUTE(DisplacementZ)\
ON_ATTRIBUTE(DissolvedSolidsContent)\
ON_ATTRIBUTE(Distance)\
ON_ATTRIBUTE(DistanceAlong)\
ON_ATTRIBUTE(DistanceAttenuation)\
ON_ATTRIBUTE(Distortion)\
ON_ATTRIBUTE(DistributionData)\
ON_ATTRIBUTE(DistributionPointFunction)\
ON_ATTRIBUTE(DocumentId)\
ON_ATTRIBUTE(DocumentOwner)\
ON_ATTRIBUTE(DocumentReferences)\
ON_ATTRIBUTE(Duration)\
ON_ATTRIBUTE(DurationType)\
ON_ATTRIBUTE(DynamicViscosity)\
ON_ATTRIBUTE(EarlyDate)\
ON_ATTRIBUTE(EarlyFinish)\
ON_ATTRIBUTE(EarlyStart)\
ON_ATTRIBUTE(Eastings)\
ON_ATTRIBUTE(EccentricityInX)\
ON_ATTRIBUTE(EccentricityInY)\
ON_ATTRIBUTE(EccentricityInZ)\
ON_ATTRIBUTE(EdgeElement)\
ON_ATTRIBUTE(EdgeEnd)\
ON_ATTRIBUTE(EdgeGeometry)\
ON_ATTRIBUTE(EdgeList)\
ON_ATTRIBUTE(EdgeRadius)\
ON_ATTRIBUTE(EdgeStart)\
ON_ATTRIBUTE(Edition)\
ON_ATTRIBUTE(EditionDate)\
ON_ATTRIBUTE(Editors)\
ON_ATTRIBUTE(EffectiveDepth)\
ON_ATTRIBUTE(ElectricCurrentExponent)\
ON_ATTRIBUTE(ElectricCurrentType)\
ON_ATTRIBUTE(ElectronicFormat)\
ON_ATTRIBUTE(ElectronicMailAddresses)\
ON_ATTRIBUTE(ElementType)\
ON_ATTRIBUTE(Elements)\
ON_ATTRIBUTE(Elevation)\
ON_ATTRIBUTE(ElevationOfRefHeight)\
ON_ATTRIBUTE(ElevationOfTerrain)\
ON_ATTRIBUTE(ElevationWithFlooring)\
ON_ATTRIBUTE(Enclosure)\
ON_ATTRIBUTE(EndParam)\
ON_ATTRIBUTE(EndProfile)\
ON_ATTRIBUTE(EndRadius)\
ON_ATTRIBUTE(EndSweptArea)\
ON_ATTRIBUTE(EndTag)\
ON_ATTRIBUTE(EndTime)\
ON_ATTRIBUTE(EnergySequence)\
ON_ATTRIBUTE(EnumerationReference)\
ON_ATTRIBUTE(EnumerationValues)\
ON_ATTRIBUTE(Enumerators)\
ON_ATTRIBUTE(EventOccurenceTime)\
ON_ATTRIBUTE(EventTriggerType)\
ON_ATTRIBUTE(ExceptionTimes)\
ON_ATTRIBUTE(ExchangeRate)\
ON_ATTRIBUTE(Exponent)\
ON_ATTRIBUTE(Expression)\
ON_ATTRIBUTE(ExtendedProperties)\
ON_ATTRIBUTE(Extent)\
ON_ATTRIBUTE(ExtrudedDirection)\
ON_ATTRIBUTE(FaceSurface)\
ON_ATTRIBUTE(Faces)\
ON_ATTRIBUTE(FacsimileNumbers)\
ON_ATTRIBUTE(Factor)\
ON_ATTRIBUTE(FamilyName)\
ON_ATTRIBUTE(FbsmFaces)\
ON_ATTRIBUTE(FeatureLength)\
ON_ATTRIBUTE(FileExtension)\
ON_ATTRIBUTE(FillStyleTarget)\
ON_ATTRIBUTE(FillStyles)\
ON_ATTRIBUTE(FilletRadius)\
ON_ATTRIBUTE(Finish)\
ON_ATTRIBUTE(FinishFloat)\
ON_ATTRIBUTE(FinishTime)\
ON_ATTRIBUTE(FirstMullionOffset)\
ON_ATTRIBUTE(FirstOperand)\
ON_ATTRIBUTE(FirstTransomOffset)\
ON_ATTRIBUTE(FixedAxisVertical)\
ON_ATTRIBUTE(FixedReference)\
ON_ATTRIBUTE(FixedUntilDate)\
ON_ATTRIBUTE(Flags)\
ON_ATTRIBUTE(FlangeEdgeRadius)\
ON_ATTRIBUTE(FlangeSlope)\
ON_ATTRIBUTE(FlangeThickness)\
ON_ATTRIBUTE(FlangeWidth)\
ON_ATTRIBUTE(FlowConditionSingleValue)\
ON_ATTRIBUTE(FlowConditionTimeSeries)\
ON_ATTRIBUTE(FlowDirection)\
ON_ATTRIBUTE(FlowrateSingleValue)\
ON_ATTRIBUTE(FlowrateTimeSeries)\
ON_ATTRIBUTE(Fluid)\
ON_ATTRIBUTE(FontFamily)\
ON_ATTRIBUTE(FontSize)\
ON_ATTRIBUTE(FontStyle)\
ON_ATTRIBUTE(FontVariant)\
ON_ATTRIBUTE(FontWeight)\
ON_ATTRIBUTE(ForLayerSet)\
ON_ATTRIBUTE(ForProfileEndSet)\
ON_ATTRIBUTE(ForProfileSet)\
ON_ATTRIBUTE(ForceX)\
ON_ATTRIBUTE(ForceY)\
ON_ATTRIBUTE(ForceZ)\
ON_ATTRIBUTE(Formula)\
ON_ATTRIBUTE(Fraction)\
ON_ATTRIBUTE(FrameDepth)\
ON_ATTRIBUTE(FrameThickness)\
ON_ATTRIBUTE(FreeFloat)\
ON_ATTRIBUTE(FreezingPoint)\
ON_ATTRIBUTE(Frequency)\
ON_ATTRIBUTE(FrictionCoefficient)\
ON_ATTRIBUTE(FullLoadCurrent)\
ON_ATTRIBUTE(GeodeticDatum)\
ON_ATTRIBUTE(Girth)\
ON_ATTRIBUTE(GivenName)\
ON_ATTRIBUTE(GivingApproval)\
ON_ATTRIBUTE(GlobalId)\
ON_ATTRIBUTE(GlobalOrLocal)\
ON_ATTRIBUTE(Green)\
ON_ATTRIBUTE(HardeningModule)\
ON_ATTRIBUTE(Hardness)\
ON_ATTRIBUTE(HasProperties)\
ON_ATTRIBUTE(HasPropertySets)\
ON_ATTRIBUTE(HasPropertyTemplates)\
ON_ATTRIBUTE(HasQuantities)\
ON_ATTRIBUTE(HasResults)\
ON_ATTRIBUTE(HatchLineAngle)\
ON_ATTRIBUTE(HatchLineAppearance)\
ON_ATTRIBUTE(HeadDepth2)\
ON_ATTRIBUTE(HeadDepth3)\
ON_ATTRIBUTE(HeadWidth)\
ON_ATTRIBUTE(Height)\
ON_ATTRIBUTE(HigherHeatingValue)\
ON_ATTRIBUTE(Horizontal)\
ON_ATTRIBUTE(HorizontalLength)\
ON_ATTRIBUTE(HourComponent)\
ON_ATTRIBUTE(HourOffset)\
ON_ATTRIBUTE(ID)\
ON_ATTRIBUTE(Id)\
ON_ATTRIBUTE(Identification)\
ON_ATTRIBUTE(Identifier)\
ON_ATTRIBUTE(ImpactType)\
ON_ATTRIBUTE(ImplicitOuter)\
ON_ATTRIBUTE(ImpliedOrder)\
ON_ATTRIBUTE(ImportanceRating)\
ON_ATTRIBUTE(ImpuritiesContent)\
ON_ATTRIBUTE(IncorporationDate)\
ON_ATTRIBUTE(InitialStress)\
ON_ATTRIBUTE(InnerBoundaries)\
ON_ATTRIBUTE(InnerCoordIndices)\
ON_ATTRIBUTE(InnerCurves)\
ON_ATTRIBUTE(InnerFilletRadius)\
ON_ATTRIBUTE(InnerRadius)\
ON_ATTRIBUTE(InnerReference)\
ON_ATTRIBUTE(InputFrequency)\
ON_ATTRIBUTE(InputPhase)\
ON_ATTRIBUTE(InputVoltage)\
ON_ATTRIBUTE(InstanceName)\
ON_ATTRIBUTE(IntendedUse)\
ON_ATTRIBUTE(Intensity)\
ON_ATTRIBUTE(Intent)\
ON_ATTRIBUTE(InterferenceGeometry)\
ON_ATTRIBUTE(InterferenceType)\
ON_ATTRIBUTE(InteriorOrExteriorSpace)\
ON_ATTRIBUTE(InternalFilletRadius)\
ON_ATTRIBUTE(InternalLocation)\
ON_ATTRIBUTE(InternalOrExternalBoundary)\
ON_ATTRIBUTE(IntersectingAxes)\
ON_ATTRIBUTE(Interval)\
ON_ATTRIBUTE(InventoryType)\
ON_ATTRIBUTE(InvisibleSegmentLength)\
ON_ATTRIBUTE(IsAttenuating)\
ON_ATTRIBUTE(IsCCW)\
ON_ATTRIBUTE(IsConvex)\
ON_ATTRIBUTE(IsCritical)\
ON_ATTRIBUTE(IsEndRadiusCCW)\
ON_ATTRIBUTE(IsHeading)\
ON_ATTRIBUTE(IsLinear)\
ON_ATTRIBUTE(IsMilestone)\
ON_ATTRIBUTE(IsOverAllocated)\
ON_ATTRIBUTE(IsPotable)\
ON_ATTRIBUTE(IsStartRadiusCCW)\
ON_ATTRIBUTE(IsVentilated)\
ON_ATTRIBUTE(IsothermalMoistureCapacity)\
ON_ATTRIBUTE(Item)\
ON_ATTRIBUTE(ItemOf)\
ON_ATTRIBUTE(ItemReference)\
ON_ATTRIBUTE(Items)\
ON_ATTRIBUTE(JobDescription)\
ON_ATTRIBUTE(Jurisdiction)\
ON_ATTRIBUTE(KnotMultiplicities)\
ON_ATTRIBUTE(KnotSpec)\
ON_ATTRIBUTE(Knots)\
ON_ATTRIBUTE(Label)\
ON_ATTRIBUTE(LagValue)\
ON_ATTRIBUTE(LandTitleNumber)\
ON_ATTRIBUTE(Language)\
ON_ATTRIBUTE(LastModifiedDate)\
ON_ATTRIBUTE(LastModifyingApplication)\
ON_ATTRIBUTE(LastModifyingUser)\
ON_ATTRIBUTE(LastRevisionTime)\
ON_ATTRIBUTE(LastUpdateDate)\
ON_ATTRIBUTE(LateDate)\
ON_ATTRIBUTE(LateFinish)\
ON_ATTRIBUTE(LateStart)\
ON_ATTRIBUTE(LateralAxisDirection)\
ON_ATTRIBUTE(LayerBlocked)\
ON_ATTRIBUTE(LayerFrozen)\
ON_ATTRIBUTE(LayerOn)\
ON_ATTRIBUTE(LayerSetDirection)\
ON_ATTRIBUTE(LayerSetName)\
ON_ATTRIBUTE(LayerStyles)\
ON_ATTRIBUTE(LayerThickness)\
ON_ATTRIBUTE(LegSlope)\
ON_ATTRIBUTE(LengthExponent)\
ON_ATTRIBUTE(LengthValue)\
ON_ATTRIBUTE(LetterSpacing)\
ON_ATTRIBUTE(Level)\
ON_ATTRIBUTE(LevelingDelay)\
ON_ATTRIBUTE(LibraryReference)\
ON_ATTRIBUTE(LifeCyclePhase)\
ON_ATTRIBUTE(LightColour)\
ON_ATTRIBUTE(LightDistributionCurve)\
ON_ATTRIBUTE(LightDistributionDataSource)\
ON_ATTRIBUTE(LightEmissionSource)\
ON_ATTRIBUTE(LineHeight)\
ON_ATTRIBUTE(LinearForceX)\
ON_ATTRIBUTE(LinearForceY)\
ON_ATTRIBUTE(LinearForceZ)\
ON_ATTRIBUTE(LinearMomentX)\
ON_ATTRIBUTE(LinearMomentY)\
ON_ATTRIBUTE(LinearMomentZ)\
ON_ATTRIBUTE(LinearStiffnessByAreaX)\
ON_ATTRIBUTE(LinearStiffnessByAreaY)\
ON_ATTRIBUTE(LinearStiffnessByAreaZ)\
ON_ATTRIBUTE(LinearStiffnessByLengthX)\
ON_ATTRIBUTE(LinearStiffnessByLengthY)\
ON_ATTRIBUTE(LinearStiffnessByLengthZ)\
ON_ATTRIBUTE(LinearStiffnessX)\
ON_ATTRIBUTE(LinearStiffnessY)\
ON_ATTRIBUTE(LinearStiffnessZ)\
ON_ATTRIBUTE(LiningDepth)\
ON_ATTRIBUTE(LiningOffset)\
ON_ATTRIBUTE(LiningThickness)\
ON_ATTRIBUTE(LiningToPanelOffsetX)\
ON_ATTRIBUTE(LiningToPanelOffsetY)\
ON_ATTRIBUTE(ListPositions)\
ON_ATTRIBUTE(ListValues)\
ON_ATTRIBUTE(Literal)\
ON_ATTRIBUTE(LoadedBy)\
ON_ATTRIBUTE(LocalOrigin)\
ON_ATTRIBUTE(Location)\
ON_ATTRIBUTE(LocationAtRelatedElement)\
ON_ATTRIBUTE(LocationAtRelatingElement)\
ON_ATTRIBUTE(LocationOfInteraction)\
ON_ATTRIBUTE(Locations)\
ON_ATTRIBUTE(LogicalAggregator)\
ON_ATTRIBUTE(LongDescription)\
ON_ATTRIBUTE(LongName)\
ON_ATTRIBUTE(LongitudinalBarCrossSectionArea)\
ON_ATTRIBUTE(LongitudinalBarNominalDiameter)\
ON_ATTRIBUTE(LongitudinalBarSpacing)\
ON_ATTRIBUTE(LongitudinalEndPosition)\
ON_ATTRIBUTE(LongitudinalStartPosition)\
ON_ATTRIBUTE(LoopVertex)\
ON_ATTRIBUTE(LowerBoundValue)\
ON_ATTRIBUTE(LowerHeatingValue)\
ON_ATTRIBUTE(LowerValue)\
ON_ATTRIBUTE(LowerVaporResistanceFactor)\
ON_ATTRIBUTE(LuminousFlux)\
ON_ATTRIBUTE(LuminousIntensity)\
ON_ATTRIBUTE(LuminousIntensityExponent)\
ON_ATTRIBUTE(Magnitude)\
ON_ATTRIBUTE(MainPlaneAngle)\
ON_ATTRIBUTE(MajorRadius)\
ON_ATTRIBUTE(MapProjection)\
ON_ATTRIBUTE(MapUnit)\
ON_ATTRIBUTE(MapZone)\
ON_ATTRIBUTE(MappedRepresentation)\
ON_ATTRIBUTE(MappedTo)\
ON_ATTRIBUTE(MappingOrigin)\
ON_ATTRIBUTE(MappingSource)\
ON_ATTRIBUTE(MappingTarget)\
ON_ATTRIBUTE(Maps)\
ON_ATTRIBUTE(MassDensity)\
ON_ATTRIBUTE(MassExponent)\
ON_ATTRIBUTE(MasterRepresentation)\
ON_ATTRIBUTE(Material)\
ON_ATTRIBUTE(MaterialClassifications)\
ON_ATTRIBUTE(MaterialConstituents)\
ON_ATTRIBUTE(MaterialLayers)\
ON_ATTRIBUTE(MaterialProfiles)\
ON_ATTRIBUTE(Materials)\
ON_ATTRIBUTE(MaxAggregateSize)\
ON_ATTRIBUTE(MaxRequiredArea)\
ON_ATTRIBUTE(MaximumPlateThickness)\
ON_ATTRIBUTE(MaximumPowerInput)\
ON_ATTRIBUTE(MaximumSectionModulusY)\
ON_ATTRIBUTE(MaximumSectionModulusZ)\
ON_ATTRIBUTE(MaximumValue)\
ON_ATTRIBUTE(MeshLength)\
ON_ATTRIBUTE(MeshWidth)\
ON_ATTRIBUTE(MessagingIDs)\
ON_ATTRIBUTE(MethodOfMeasurement)\
ON_ATTRIBUTE(MiddleNames)\
ON_ATTRIBUTE(MimeContentType)\
ON_ATTRIBUTE(MimeSubtype)\
ON_ATTRIBUTE(MinCurvatureRadius)\
ON_ATTRIBUTE(MinRequiredArea)\
ON_ATTRIBUTE(MinimumCircuitCurrent)\
ON_ATTRIBUTE(MinimumPlateThickness)\
ON_ATTRIBUTE(MinimumSectionModulusY)\
ON_ATTRIBUTE(MinimumSectionModulusZ)\
ON_ATTRIBUTE(MinimumValue)\
ON_ATTRIBUTE(MinorRadius)\
ON_ATTRIBUTE(MinuteComponent)\
ON_ATTRIBUTE(MinuteOffset)\
ON_ATTRIBUTE(Mode)\
ON_ATTRIBUTE(ModelOrDraughting)\
ON_ATTRIBUTE(ModelorDraughting)\
ON_ATTRIBUTE(MoistureDiffusivity)\
ON_ATTRIBUTE(MolecularWeight)\
ON_ATTRIBUTE(MomentOfInertiaY)\
ON_ATTRIBUTE(MomentOfInertiaYZ)\
ON_ATTRIBUTE(MomentOfInertiaZ)\
ON_ATTRIBUTE(MomentX)\
ON_ATTRIBUTE(MomentY)\
ON_ATTRIBUTE(MomentZ)\
ON_ATTRIBUTE(MonthComponent)\
ON_ATTRIBUTE(MostUsedValue)\
ON_ATTRIBUTE(MoveFrom)\
ON_ATTRIBUTE(MoveTo)\
ON_ATTRIBUTE(MullionThickness)\
ON_ATTRIBUTE(N20Content)\
ON_ATTRIBUTE(Name)\
ON_ATTRIBUTE(NominalBarDiameter)\
ON_ATTRIBUTE(NominalDiameter)\
ON_ATTRIBUTE(NominalLength)\
ON_ATTRIBUTE(NominalValue)\
ON_ATTRIBUTE(Normals)\
ON_ATTRIBUTE(Northings)\
ON_ATTRIBUTE(Notation)\
ON_ATTRIBUTE(NotationFacets)\
ON_ATTRIBUTE(NotationValue)\
ON_ATTRIBUTE(NumberOfRiser)\
ON_ATTRIBUTE(NumberOfRisers)\
ON_ATTRIBUTE(NumberOfTreads)\
ON_ATTRIBUTE(ObjectPlacement)\
ON_ATTRIBUTE(ObjectType)\
ON_ATTRIBUTE(ObjectiveQualifier)\
ON_ATTRIBUTE(Occurrences)\
ON_ATTRIBUTE(OffsetDirection)\
ON_ATTRIBUTE(OffsetDistances)\
ON_ATTRIBUTE(OffsetFromReferenceLine)\
ON_ATTRIBUTE(OffsetLateral)\
ON_ATTRIBUTE(OffsetLongitudinal)\
ON_ATTRIBUTE(OffsetValues)\
ON_ATTRIBUTE(OffsetVertical)\
ON_ATTRIBUTE(Opacity)\
ON_ATTRIBUTE(OperationType)\
ON_ATTRIBUTE(Operator)\
ON_ATTRIBUTE(Orientation)\
ON_ATTRIBUTE(OrientationOf2DPlane)\
ON_ATTRIBUTE(OriginalValue)\
ON_ATTRIBUTE(OrthogonalHeight)\
ON_ATTRIBUTE(Outer)\
ON_ATTRIBUTE(OuterBoundary)\
ON_ATTRIBUTE(OuterCurve)\
ON_ATTRIBUTE(OuterFilletRadius)\
ON_ATTRIBUTE(OverallDepth)\
ON_ATTRIBUTE(OverallHeight)\
ON_ATTRIBUTE(OverallWidth)\
ON_ATTRIBUTE(OverridingProperties)\
ON_ATTRIBUTE(Owner)\
ON_ATTRIBUTE(OwnerHistory)\
ON_ATTRIBUTE(OwningApplication)\
ON_ATTRIBUTE(OwningUser)\
ON_ATTRIBUTE(PHLevel)\
ON_ATTRIBUTE(PagerNumber)\
ON_ATTRIBUTE(PanelDepth)\
ON_ATTRIBUTE(PanelOperation)\
ON_ATTRIBUTE(PanelPosition)\
ON_ATTRIBUTE(PanelWidth)\
ON_ATTRIBUTE(ParabolaConstant)\
ON_ATTRIBUTE(ParamLength)\
ON_ATTRIBUTE(Parameter)\
ON_ATTRIBUTE(ParameterTakesPrecedence)\
ON_ATTRIBUTE(ParentBoundary)\
ON_ATTRIBUTE(ParentContext)\
ON_ATTRIBUTE(ParentCurve)\
ON_ATTRIBUTE(ParentEdge)\
ON_ATTRIBUTE(ParentProfile)\
ON_ATTRIBUTE(PartOfProductDefinitionShape)\
ON_ATTRIBUTE(PartitioningType)\
ON_ATTRIBUTE(Path)\
ON_ATTRIBUTE(PatternList)\
ON_ATTRIBUTE(PatternStart)\
ON_ATTRIBUTE(Perimeter)\
ON_ATTRIBUTE(PermitID)\
ON_ATTRIBUTE(Phase)\
ON_ATTRIBUTE(PhysicalOrVirtualBoundary)\
ON_ATTRIBUTE(PhysicalWeight)\
ON_ATTRIBUTE(Pixel)\
ON_ATTRIBUTE(Placement)\
ON_ATTRIBUTE(PlacementLocation)\
ON_ATTRIBUTE(PlacementRefDirection)\
ON_ATTRIBUTE(PlacementRelTo)\
ON_ATTRIBUTE(PlanarForceX)\
ON_ATTRIBUTE(PlanarForceY)\
ON_ATTRIBUTE(PlanarForceZ)\
ON_ATTRIBUTE(PlasticShapeFactorY)\
ON_ATTRIBUTE(PlasticShapeFactorZ)\
ON_ATTRIBUTE(PlasticStrain)\
ON_ATTRIBUTE(PnIndex)\
ON_ATTRIBUTE(Pnt)\
ON_ATTRIBUTE(PointOfReferenceHatchLine)\
ON_ATTRIBUTE(PointOnRelatedElement)\
ON_ATTRIBUTE(PointOnRelatingElement)\
ON_ATTRIBUTE(PointParameter)\
ON_ATTRIBUTE(PointParameterU)\
ON_ATTRIBUTE(PointParameterV)\
ON_ATTRIBUTE(Points)\
ON_ATTRIBUTE(PoissonRatio)\
ON_ATTRIBUTE(Polygon)\
ON_ATTRIBUTE(PolygonalBoundary)\
ON_ATTRIBUTE(Porosity)\
ON_ATTRIBUTE(Position)\
ON_ATTRIBUTE(PostalBox)\
ON_ATTRIBUTE(PostalCode)\
ON_ATTRIBUTE(PreStress)\
ON_ATTRIBUTE(Precision)\
ON_ATTRIBUTE(PredefinedType)\
ON_ATTRIBUTE(Prefix)\
ON_ATTRIBUTE(PrefixTitles)\
ON_ATTRIBUTE(PreparedBy)\
ON_ATTRIBUTE(PressureSingleValue)\
ON_ATTRIBUTE(PressureTimeSeries)\
ON_ATTRIBUTE(PrimaryMeasureType)\
ON_ATTRIBUTE(PrimaryUnit)\
ON_ATTRIBUTE(Priority)\
ON_ATTRIBUTE(ProcedureID)\
ON_ATTRIBUTE(ProcedureType)\
ON_ATTRIBUTE(ProcessType)\
ON_ATTRIBUTE(ProductDefinitional)\
ON_ATTRIBUTE(Profile)\
ON_ATTRIBUTE(ProfileDefinition)\
ON_ATTRIBUTE(ProfileName)\
ON_ATTRIBUTE(ProfileOfPort)\
ON_ATTRIBUTE(ProfileOrientation)\
ON_ATTRIBUTE(ProfileSectionLocation)\
ON_ATTRIBUTE(ProfileType)\
ON_ATTRIBUTE(Profiles)\
ON_ATTRIBUTE(ProjectedOrTrue)\
ON_ATTRIBUTE(Properties)\
ON_ATTRIBUTE(PropertyReference)\
ON_ATTRIBUTE(PropertySource)\
ON_ATTRIBUTE(ProportionalStress)\
ON_ATTRIBUTE(ProtectivePoreRatio)\
ON_ATTRIBUTE(ProxyType)\
ON_ATTRIBUTE(Publisher)\
ON_ATTRIBUTE(PunchList)\
ON_ATTRIBUTE(Purpose)\
ON_ATTRIBUTE(QuadricAttenuation)\
ON_ATTRIBUTE(Qualifier)\
ON_ATTRIBUTE(Quality)\
ON_ATTRIBUTE(Quantities)\
ON_ATTRIBUTE(QuantityInProcess)\
ON_ATTRIBUTE(Radius)\
ON_ATTRIBUTE(RasterCode)\
ON_ATTRIBUTE(RasterFormat)\
ON_ATTRIBUTE(RateDateTime)\
ON_ATTRIBUTE(RateSource)\
ON_ATTRIBUTE(RatedPowerInput)\
ON_ATTRIBUTE(RealizingElement)\
ON_ATTRIBUTE(RealizingElements)\
ON_ATTRIBUTE(Records)\
ON_ATTRIBUTE(Recurrence)\
ON_ATTRIBUTE(RecurrencePattern)\
ON_ATTRIBUTE(RecurrenceType)\
ON_ATTRIBUTE(Red)\
ON_ATTRIBUTE(RefDirection)\
ON_ATTRIBUTE(RefElevation)\
ON_ATTRIBUTE(RefLatitude)\
ON_ATTRIBUTE(RefLongitude)\
ON_ATTRIBUTE(ReferenceCurve)\
ON_ATTRIBUTE(ReferenceExtent)\
ON_ATTRIBUTE(ReferencePath)\
ON_ATTRIBUTE(ReferenceSurface)\
ON_ATTRIBUTE(ReferenceTokens)\
ON_ATTRIBUTE(ReferencedDocument)\
ON_ATTRIBUTE(ReferencedLibrary)\
ON_ATTRIBUTE(ReferencedSource)\
ON_ATTRIBUTE(ReferencedTimeSeries)\
ON_ATTRIBUTE(ReferencingValues)\
ON_ATTRIBUTE(ReflectanceColour)\
ON_ATTRIBUTE(ReflectanceMethod)\
ON_ATTRIBUTE(ReflectionColour)\
ON_ATTRIBUTE(RefractionIndex)\
ON_ATTRIBUTE(Region)\
ON_ATTRIBUTE(ReinforcementRole)\
ON_ATTRIBUTE(ReinforcementSectionDefinitions)\
ON_ATTRIBUTE(RelatedApproval)\
ON_ATTRIBUTE(RelatedApprovals)\
ON_ATTRIBUTE(RelatedBuildingElement)\
ON_ATTRIBUTE(RelatedBuildings)\
ON_ATTRIBUTE(RelatedClassifications)\
ON_ATTRIBUTE(RelatedConnectionType)\
ON_ATTRIBUTE(RelatedConstraints)\
ON_ATTRIBUTE(RelatedControlElements)\
ON_ATTRIBUTE(RelatedCoverings)\
ON_ATTRIBUTE(RelatedDefinitions)\
ON_ATTRIBUTE(RelatedDocuments)\
ON_ATTRIBUTE(RelatedDraughtingCallout)\
ON_ATTRIBUTE(RelatedElement)\
ON_ATTRIBUTE(RelatedElements)\
ON_ATTRIBUTE(RelatedFeatureElement)\
ON_ATTRIBUTE(RelatedItems)\
ON_ATTRIBUTE(RelatedMaterials)\
ON_ATTRIBUTE(RelatedMonetaryUnit)\
ON_ATTRIBUTE(RelatedObjects)\
ON_ATTRIBUTE(RelatedObjectsType)\
ON_ATTRIBUTE(RelatedOpeningElement)\
ON_ATTRIBUTE(RelatedOrganizations)\
ON_ATTRIBUTE(RelatedPort)\
ON_ATTRIBUTE(RelatedPriorities)\
ON_ATTRIBUTE(RelatedProcess)\
ON_ATTRIBUTE(RelatedProperties)\
ON_ATTRIBUTE(RelatedPropertySets)\
ON_ATTRIBUTE(RelatedResourceObjects)\
ON_ATTRIBUTE(RelatedSpace)\
ON_ATTRIBUTE(RelatedSpaceProgram)\
ON_ATTRIBUTE(RelatedStructuralActivity)\
ON_ATTRIBUTE(RelatedStructuralConnection)\
ON_ATTRIBUTE(RelatedStructuralMember)\
ON_ATTRIBUTE(RelatingActor)\
ON_ATTRIBUTE(RelatingAppliedValue)\
ON_ATTRIBUTE(RelatingApproval)\
ON_ATTRIBUTE(RelatingBuildingElement)\
ON_ATTRIBUTE(RelatingClassification)\
ON_ATTRIBUTE(RelatingConnectionType)\
ON_ATTRIBUTE(RelatingConstraint)\
ON_ATTRIBUTE(RelatingContext)\
ON_ATTRIBUTE(RelatingControl)\
ON_ATTRIBUTE(RelatingDocument)\
ON_ATTRIBUTE(RelatingDraughtingCallout)\
ON_ATTRIBUTE(RelatingElement)\
ON_ATTRIBUTE(RelatingFlowElement)\
ON_ATTRIBUTE(RelatingGroup)\
ON_ATTRIBUTE(RelatingItem)\
ON_ATTRIBUTE(RelatingLibrary)\
ON_ATTRIBUTE(RelatingMaterial)\
ON_ATTRIBUTE(RelatingMonetaryUnit)\
ON_ATTRIBUTE(RelatingObject)\
ON_ATTRIBUTE(RelatingOpeningElement)\
ON_ATTRIBUTE(RelatingOrganization)\
ON_ATTRIBUTE(RelatingPort)\
ON_ATTRIBUTE(RelatingPriorities)\
ON_ATTRIBUTE(RelatingProcess)\
ON_ATTRIBUTE(RelatingProduct)\
ON_ATTRIBUTE(RelatingProfileProperties)\
ON_ATTRIBUTE(RelatingPropertyDefinition)\
ON_ATTRIBUTE(RelatingReference)\
ON_ATTRIBUTE(RelatingResource)\
ON_ATTRIBUTE(RelatingSpace)\
ON_ATTRIBUTE(RelatingSpaceProgram)\
ON_ATTRIBUTE(RelatingStructuralMember)\
ON_ATTRIBUTE(RelatingStructure)\
ON_ATTRIBUTE(RelatingSystem)\
ON_ATTRIBUTE(RelatingTemplate)\
ON_ATTRIBUTE(RelatingType)\
ON_ATTRIBUTE(RelationshipType)\
ON_ATTRIBUTE(RelativePlacement)\
ON_ATTRIBUTE(RelaxationValue)\
ON_ATTRIBUTE(Relaxations)\
ON_ATTRIBUTE(RemainingTime)\
ON_ATTRIBUTE(RemainingUsage)\
ON_ATTRIBUTE(RemainingWork)\
ON_ATTRIBUTE(RepeatFactor)\
ON_ATTRIBUTE(RepeatS)\
ON_ATTRIBUTE(RepeatT)\
ON_ATTRIBUTE(Representation)\
ON_ATTRIBUTE(RepresentationContexts)\
ON_ATTRIBUTE(RepresentationIdentifier)\
ON_ATTRIBUTE(RepresentationMaps)\
ON_ATTRIBUTE(RepresentationType)\
ON_ATTRIBUTE(Representations)\
ON_ATTRIBUTE(RepresentedMaterial)\
ON_ATTRIBUTE(RequestID)\
ON_ATTRIBUTE(RequestedLocation)\
ON_ATTRIBUTE(RequestingApproval)\
ON_ATTRIBUTE(ResourceConsumption)\
ON_ATTRIBUTE(ResourceGroup)\
ON_ATTRIBUTE(ResourceIdentifier)\
ON_ATTRIBUTE(ResourceType)\
ON_ATTRIBUTE(ResponsiblePerson)\
ON_ATTRIBUTE(ResponsiblePersons)\
ON_ATTRIBUTE(RestartDistance)\
ON_ATTRIBUTE(ResultForLoadGroup)\
ON_ATTRIBUTE(ResultValues)\
ON_ATTRIBUTE(Revision)\
ON_ATTRIBUTE(RibHeight)\
ON_ATTRIBUTE(RibSpacing)\
ON_ATTRIBUTE(RibWidth)\
ON_ATTRIBUTE(RiserHeight)\
ON_ATTRIBUTE(Role)\
ON_ATTRIBUTE(Roles)\
ON_ATTRIBUTE(RotationalDisplacementRX)\
ON_ATTRIBUTE(RotationalDisplacementRY)\
ON_ATTRIBUTE(RotationalDisplacementRZ)\
ON_ATTRIBUTE(RotationalStiffnessByLengthX)\
ON_ATTRIBUTE(RotationalStiffnessByLengthY)\
ON_ATTRIBUTE(RotationalStiffnessByLengthZ)\
ON_ATTRIBUTE(RotationalStiffnessX)\
ON_ATTRIBUTE(RotationalStiffnessY)\
ON_ATTRIBUTE(RotationalStiffnessZ)\
ON_ATTRIBUTE(RoundingRadius)\
ON_ATTRIBUTE(RowCells)\
ON_ATTRIBUTE(Rows)\
ON_ATTRIBUTE(SameSense)\
ON_ATTRIBUTE(SbsmBoundary)\
ON_ATTRIBUTE(Scale)\
ON_ATTRIBUTE(Scale2)\
ON_ATTRIBUTE(Scale3)\
ON_ATTRIBUTE(ScheduleContour)\
ON_ATTRIBUTE(ScheduleDate)\
ON_ATTRIBUTE(ScheduleDuration)\
ON_ATTRIBUTE(ScheduleFinish)\
ON_ATTRIBUTE(ScheduleStart)\
ON_ATTRIBUTE(ScheduleUsage)\
ON_ATTRIBUTE(ScheduleWork)\
ON_ATTRIBUTE(Scope)\
ON_ATTRIBUTE(SecondComponent)\
ON_ATTRIBUTE(SecondMullionOffset)\
ON_ATTRIBUTE(SecondOperand)\
ON_ATTRIBUTE(SecondRepeatFactor)\
ON_ATTRIBUTE(SecondTransomOffset)\
ON_ATTRIBUTE(SecondaryMeasureType)\
ON_ATTRIBUTE(SecondaryPlaneAngle)\
ON_ATTRIBUTE(SecondaryUnit)\
ON_ATTRIBUTE(SectionDefinition)\
ON_ATTRIBUTE(SectionType)\
ON_ATTRIBUTE(SegmentLength)\
ON_ATTRIBUTE(Segments)\
ON_ATTRIBUTE(SelfIntersect)\
ON_ATTRIBUTE(SelfWeightCoefficients)\
ON_ATTRIBUTE(SemiAxis1)\
ON_ATTRIBUTE(SemiAxis2)\
ON_ATTRIBUTE(Sense)\
ON_ATTRIBUTE(SenseAgreement)\
ON_ATTRIBUTE(SequenceType)\
ON_ATTRIBUTE(ServiceLifeDuration)\
ON_ATTRIBUTE(ServiceLifeType)\
ON_ATTRIBUTE(SetPointValue)\
ON_ATTRIBUTE(ShapeAspectStyle)\
ON_ATTRIBUTE(ShapeRepresentations)\
ON_ATTRIBUTE(ShapeType)\
ON_ATTRIBUTE(SharedPlacement)\
ON_ATTRIBUTE(ShearAreaY)\
ON_ATTRIBUTE(ShearAreaZ)\
ON_ATTRIBUTE(ShearCentreY)\
ON_ATTRIBUTE(ShearCentreZ)\
ON_ATTRIBUTE(ShearDeformationAreaY)\
ON_ATTRIBUTE(ShearDeformationAreaZ)\
ON_ATTRIBUTE(ShearModulus)\
ON_ATTRIBUTE(ShearReinforcement)\
ON_ATTRIBUTE(SheathDiameter)\
ON_ATTRIBUTE(Side)\
ON_ATTRIBUTE(SiteAddress)\
ON_ATTRIBUTE(SizeInX)\
ON_ATTRIBUTE(SizeInY)\
ON_ATTRIBUTE(Sizeable)\
ON_ATTRIBUTE(SkillSet)\
ON_ATTRIBUTE(SlippageX)\
ON_ATTRIBUTE(SlippageY)\
ON_ATTRIBUTE(SlippageZ)\
ON_ATTRIBUTE(SolarReflectanceBack)\
ON_ATTRIBUTE(SolarReflectanceFront)\
ON_ATTRIBUTE(SolarTransmittance)\
ON_ATTRIBUTE(Sort)\
ON_ATTRIBUTE(SoundLevelSingleValue)\
ON_ATTRIBUTE(SoundLevelTimeSeries)\
ON_ATTRIBUTE(SoundScale)\
ON_ATTRIBUTE(SoundValues)\
ON_ATTRIBUTE(Source)\
ON_ATTRIBUTE(SourceCRS)\
ON_ATTRIBUTE(SourceDescription)\
ON_ATTRIBUTE(SpaceProgramIdentifier)\
ON_ATTRIBUTE(SpecificHeatCapacity)\
ON_ATTRIBUTE(SpecularColour)\
ON_ATTRIBUTE(SpecularHighlight)\
ON_ATTRIBUTE(SpineCurve)\
ON_ATTRIBUTE(SpreadAngle)\
ON_ATTRIBUTE(StandardRequiredArea)\
ON_ATTRIBUTE(Start)\
ON_ATTRIBUTE(StartDirection)\
ON_ATTRIBUTE(StartDistAlong)\
ON_ATTRIBUTE(StartFloat)\
ON_ATTRIBUTE(StartGradient)\
ON_ATTRIBUTE(StartHeight)\
ON_ATTRIBUTE(StartOfNextHatchLine)\
ON_ATTRIBUTE(StartParam)\
ON_ATTRIBUTE(StartPoint)\
ON_ATTRIBUTE(StartProfile)\
ON_ATTRIBUTE(StartRadius)\
ON_ATTRIBUTE(StartTag)\
ON_ATTRIBUTE(StartTime)\
ON_ATTRIBUTE(State)\
ON_ATTRIBUTE(Status)\
ON_ATTRIBUTE(StatusTime)\
ON_ATTRIBUTE(SteelGrade)\
ON_ATTRIBUTE(StyleOfSymbol)\
ON_ATTRIBUTE(Styles)\
ON_ATTRIBUTE(SubContractor)\
ON_ATTRIBUTE(SubmittedBy)\
ON_ATTRIBUTE(SubmittedOn)\
ON_ATTRIBUTE(SubsequentAppliedLoads)\
ON_ATTRIBUTE(SubsequentThickness)\
ON_ATTRIBUTE(SuffixTitles)\
ON_ATTRIBUTE(Suppliers)\
ON_ATTRIBUTE(SupportedLength)\
ON_ATTRIBUTE(SurfaceColour)\
ON_ATTRIBUTE(SurfaceForm)\
ON_ATTRIBUTE(SurfaceOnRelatedElement)\
ON_ATTRIBUTE(SurfaceOnRelatingElement)\
ON_ATTRIBUTE(SurfaceReinforcement1)\
ON_ATTRIBUTE(SurfaceReinforcement2)\
ON_ATTRIBUTE(SweptArea)\
ON_ATTRIBUTE(SweptCurve)\
ON_ATTRIBUTE(Symbol)\
ON_ATTRIBUTE(SystemType)\
ON_ATTRIBUTE(Tag)\
ON_ATTRIBUTE(TagList)\
ON_ATTRIBUTE(TangentialContinuity)\
ON_ATTRIBUTE(Target)\
ON_ATTRIBUTE(TargetCRS)\
ON_ATTRIBUTE(TargetScale)\
ON_ATTRIBUTE(TargetUsers)\
ON_ATTRIBUTE(TargetView)\
ON_ATTRIBUTE(TaskId)\
ON_ATTRIBUTE(TaskTime)\
ON_ATTRIBUTE(TelephoneNumbers)\
ON_ATTRIBUTE(TemperatureSingleValue)\
ON_ATTRIBUTE(TemperatureTimeSeries)\
ON_ATTRIBUTE(TemplateType)\
ON_ATTRIBUTE(TensionFailureX)\
ON_ATTRIBUTE(TensionFailureY)\
ON_ATTRIBUTE(TensionFailureZ)\
ON_ATTRIBUTE(TensionForce)\
ON_ATTRIBUTE(TexCoordIndex)\
ON_ATTRIBUTE(TexCoords)\
ON_ATTRIBUTE(TexCoordsList)\
ON_ATTRIBUTE(TextAlign)\
ON_ATTRIBUTE(TextCharacterAppearance)\
ON_ATTRIBUTE(TextDecoration)\
ON_ATTRIBUTE(TextFontStyle)\
ON_ATTRIBUTE(TextIndent)\
ON_ATTRIBUTE(TextStyle)\
ON_ATTRIBUTE(TextTransform)\
ON_ATTRIBUTE(TextureCoordinates)\
ON_ATTRIBUTE(TextureMaps)\
ON_ATTRIBUTE(TexturePoints)\
ON_ATTRIBUTE(TextureTransform)\
ON_ATTRIBUTE(TextureType)\
ON_ATTRIBUTE(TextureVertices)\
ON_ATTRIBUTE(Textures)\
ON_ATTRIBUTE(TheActor)\
ON_ATTRIBUTE(TheOrganization)\
ON_ATTRIBUTE(ThePerson)\
ON_ATTRIBUTE(TheoryType)\
ON_ATTRIBUTE(ThermalConductivity)\
ON_ATTRIBUTE(ThermalExpansionCoefficient)\
ON_ATTRIBUTE(ThermalIrEmissivityBack)\
ON_ATTRIBUTE(ThermalIrEmissivityFront)\
ON_ATTRIBUTE(ThermalIrTransmittance)\
ON_ATTRIBUTE(ThermalLoadSource)\
ON_ATTRIBUTE(ThermalLoadTimeSeriesValues)\
ON_ATTRIBUTE(ThermalLoadType)\
ON_ATTRIBUTE(ThermodynamicTemperatureExponent)\
ON_ATTRIBUTE(Thickness)\
ON_ATTRIBUTE(ThresholdDepth)\
ON_ATTRIBUTE(ThresholdOffset)\
ON_ATTRIBUTE(ThresholdThickness)\
ON_ATTRIBUTE(Tiles)\
ON_ATTRIBUTE(TilingPattern)\
ON_ATTRIBUTE(TilingScale)\
ON_ATTRIBUTE(TimeComponent)\
ON_ATTRIBUTE(TimeExponent)\
ON_ATTRIBUTE(TimeForTask)\
ON_ATTRIBUTE(TimeLag)\
ON_ATTRIBUTE(TimeOfApproval)\
ON_ATTRIBUTE(TimePeriods)\
ON_ATTRIBUTE(TimeSeries)\
ON_ATTRIBUTE(TimeSeriesDataType)\
ON_ATTRIBUTE(TimeSeriesReferences)\
ON_ATTRIBUTE(TimeSeriesScheduleType)\
ON_ATTRIBUTE(TimeStamp)\
ON_ATTRIBUTE(TimeStep)\
ON_ATTRIBUTE(TimeValue)\
ON_ATTRIBUTE(Title)\
ON_ATTRIBUTE(TopFlangeEdgeRadius)\
ON_ATTRIBUTE(TopFlangeFilletRadius)\
ON_ATTRIBUTE(TopFlangeSlope)\
ON_ATTRIBUTE(TopFlangeThickness)\
ON_ATTRIBUTE(TopFlangeWidth)\
ON_ATTRIBUTE(TopXDim)\
ON_ATTRIBUTE(TopXOffset)\
ON_ATTRIBUTE(TorsionalConstantX)\
ON_ATTRIBUTE(TorsionalSectionModulus)\
ON_ATTRIBUTE(TotalCrossSectionArea)\
ON_ATTRIBUTE(TotalFloat)\
ON_ATTRIBUTE(TotalReplacementCost)\
ON_ATTRIBUTE(Town)\
ON_ATTRIBUTE(Transition)\
ON_ATTRIBUTE(TransitionCurveType)\
ON_ATTRIBUTE(TranslationalStiffnessByAreaX)\
ON_ATTRIBUTE(TranslationalStiffnessByAreaY)\
ON_ATTRIBUTE(TranslationalStiffnessByAreaZ)\
ON_ATTRIBUTE(TranslationalStiffnessByLengthX)\
ON_ATTRIBUTE(TranslationalStiffnessByLengthY)\
ON_ATTRIBUTE(TranslationalStiffnessByLengthZ)\
ON_ATTRIBUTE(TranslationalStiffnessX)\
ON_ATTRIBUTE(TranslationalStiffnessY)\
ON_ATTRIBUTE(TranslationalStiffnessZ)\
ON_ATTRIBUTE(TransmissionColour)\
ON_ATTRIBUTE(TransomOffset)\
ON_ATTRIBUTE(TransomThickness)\
ON_ATTRIBUTE(Transparency)\
ON_ATTRIBUTE(TransverseBarCrossSectionArea)\
ON_ATTRIBUTE(TransverseBarNominalDiameter)\
ON_ATTRIBUTE(TransverseBarSpacing)\
ON_ATTRIBUTE(TransversePosition)\
ON_ATTRIBUTE(TreadLength)\
ON_ATTRIBUTE(TreeRootExpression)\
ON_ATTRIBUTE(Trim1)\
ON_ATTRIBUTE(Trim2)\
ON_ATTRIBUTE(TrueNorth)\
ON_ATTRIBUTE(TypeIdentifier)\
ON_ATTRIBUTE(U1)\
ON_ATTRIBUTE(U2)\
ON_ATTRIBUTE(UAxes)\
ON_ATTRIBUTE(UClosed)\
ON_ATTRIBUTE(UDegree)\
ON_ATTRIBUTE(UKnots)\
ON_ATTRIBUTE(UMultiplicities)\
ON_ATTRIBUTE(URLReference)\
ON_ATTRIBUTE(UltimateStrain)\
ON_ATTRIBUTE(UltimateStress)\
ON_ATTRIBUTE(Unit)\
ON_ATTRIBUTE(UnitBasis)\
ON_ATTRIBUTE(UnitComponent)\
ON_ATTRIBUTE(UnitType)\
ON_ATTRIBUTE(Units)\
ON_ATTRIBUTE(UnitsInContext)\
ON_ATTRIBUTE(UpdateDate)\
ON_ATTRIBUTE(UpperBoundValue)\
ON_ATTRIBUTE(UpperValue)\
ON_ATTRIBUTE(UpperVaporResistanceFactor)\
ON_ATTRIBUTE(UrlReference)\
ON_ATTRIBUTE(Usage)\
ON_ATTRIBUTE(UsageName)\
ON_ATTRIBUTE(UsageRatio)\
ON_ATTRIBUTE(Usense)\
ON_ATTRIBUTE(User)\
ON_ATTRIBUTE(UserDefinedCategory)\
ON_ATTRIBUTE(UserDefinedControlType)\
ON_ATTRIBUTE(UserDefinedDataOrigin)\
ON_ATTRIBUTE(UserDefinedEnergySequence)\
ON_ATTRIBUTE(UserDefinedEventTriggerType)\
ON_ATTRIBUTE(UserDefinedFunction)\
ON_ATTRIBUTE(UserDefinedGrade)\
ON_ATTRIBUTE(UserDefinedOperationType)\
ON_ATTRIBUTE(UserDefinedPartitioningType)\
ON_ATTRIBUTE(UserDefinedProcedureType)\
ON_ATTRIBUTE(UserDefinedPropertySource)\
ON_ATTRIBUTE(UserDefinedPurpose)\
ON_ATTRIBUTE(UserDefinedQualifier)\
ON_ATTRIBUTE(UserDefinedRole)\
ON_ATTRIBUTE(UserDefinedSequenceType)\
ON_ATTRIBUTE(UserDefinedTargetView)\
ON_ATTRIBUTE(UserDefinedThermalLoadSource)\
ON_ATTRIBUTE(UserDefinedType)\
ON_ATTRIBUTE(V1)\
ON_ATTRIBUTE(V2)\
ON_ATTRIBUTE(VAxes)\
ON_ATTRIBUTE(VClosed)\
ON_ATTRIBUTE(VDegree)\
ON_ATTRIBUTE(VKnots)\
ON_ATTRIBUTE(VMultiplicities)\
ON_ATTRIBUTE(ValidFrom)\
ON_ATTRIBUTE(ValidUntil)\
ON_ATTRIBUTE(ValueComponent)\
ON_ATTRIBUTE(ValueSource)\
ON_ATTRIBUTE(Values)\
ON_ATTRIBUTE(VaporPermeability)\
ON_ATTRIBUTE(VaryingAppliedLoadLocation)\
ON_ATTRIBUTE(VaryingThicknessLocation)\
ON_ATTRIBUTE(VelocitySingleValue)\
ON_ATTRIBUTE(VelocityTimeSeries)\
ON_ATTRIBUTE(Version)\
ON_ATTRIBUTE(VersionDate)\
ON_ATTRIBUTE(VertexGeometry)\
ON_ATTRIBUTE(Vertical)\
ON_ATTRIBUTE(VerticalAxisDirection)\
ON_ATTRIBUTE(VerticalDatum)\
ON_ATTRIBUTE(Vertices)\
ON_ATTRIBUTE(VisibleReflectanceBack)\
ON_ATTRIBUTE(VisibleReflectanceFront)\
ON_ATTRIBUTE(VisibleSegmentLength)\
ON_ATTRIBUTE(VisibleTransmittance)\
ON_ATTRIBUTE(Voids)\
ON_ATTRIBUTE(VolumeOnRelatedElement)\
ON_ATTRIBUTE(VolumeOnRelatingElement)\
ON_ATTRIBUTE(VolumeValue)\
ON_ATTRIBUTE(Vsense)\
ON_ATTRIBUTE(WAxes)\
ON_ATTRIBUTE(WWWHomePageURL)\
ON_ATTRIBUTE(WallThickness)\
ON_ATTRIBUTE(WarpingConstant)\
ON_ATTRIBUTE(WarpingMoment)\
ON_ATTRIBUTE(WarpingStiffness)\
ON_ATTRIBUTE(WaterImpermeability)\
ON_ATTRIBUTE(WebEdgeRadius)\
ON_ATTRIBUTE(WebSlope)\
ON_ATTRIBUTE(WebThickness)\
ON_ATTRIBUTE(WeekdayComponent)\
ON_ATTRIBUTE(WeightValue)\
ON_ATTRIBUTE(WeightsData)\
ON_ATTRIBUTE(WetBulbTemperatureSingleValue)\
ON_ATTRIBUTE(WetBulbTemperatureTimeSeries)\
ON_ATTRIBUTE(Width)\
ON_ATTRIBUTE(WordSpacing)\
ON_ATTRIBUTE(WorkControlType)\
ON_ATTRIBUTE(WorkMethod)\
ON_ATTRIBUTE(Workability)\
ON_ATTRIBUTE(WorkingTimes)\
ON_ATTRIBUTE(WorldCoordinateSystem)\
ON_ATTRIBUTE(XAxisAbscissa)\
ON_ATTRIBUTE(XAxisOrdinate)\
ON_ATTRIBUTE(XDim)\
ON_ATTRIBUTE(XLength)\
ON_ATTRIBUTE(YDim)\
ON_ATTRIBUTE(YLength)\
ON_ATTRIBUTE(YearComponent)\
ON_ATTRIBUTE(YieldStress)\
ON_ATTRIBUTE(YoungModulus)\
ON_ATTRIBUTE(ZDim)\
ON_ATTRIBUTE(ZLength)\
ON_ATTRIBUTE(Zone)\

