// Property of Bricsys NV. All rights reserved.
// This file is part of the BRX SDK, and its use is subject to the terms
// of the BRX SDK license agreement.
/////////////////////////////////////////////////////////////////////////

#undef ENTITIES_LIST
#define ENTITIES_LIST()\
ON_ENTITY(Ifc2DCompositeCurve)\
ON_ENTITY(IfcActionRequest)\
ON_ENTITY(IfcActor)\
ON_ENTITY(IfcActorRole)\
ON_ENTITY(IfcActuator)\
ON_ENTITY(IfcActuatorType)\
ON_ENTITY(IfcAddress)\
ON_ENTITY(IfcAdvancedBrep)\
ON_ENTITY(IfcAdvancedBrepWithVoids)\
ON_ENTITY(IfcAdvancedFace)\
ON_ENTITY(IfcAirTerminal)\
ON_ENTITY(IfcAirTerminalBox)\
ON_ENTITY(IfcAirTerminalBoxType)\
ON_ENTITY(IfcAirTerminalType)\
ON_ENTITY(IfcAirToAirHeatRecovery)\
ON_ENTITY(IfcAirToAirHeatRecoveryType)\
ON_ENTITY(IfcAlarm)\
ON_ENTITY(IfcAlarmType)\
ON_ENTITY(IfcAlignment)\
ON_ENTITY(IfcAlignment2DHorizontal)\
ON_ENTITY(IfcAlignment2DHorizontalSegment)\
ON_ENTITY(IfcAlignment2DSegment)\
ON_ENTITY(IfcAlignment2DVerSegCircularArc)\
ON_ENTITY(IfcAlignment2DVerSegLine)\
ON_ENTITY(IfcAlignment2DVerSegParabolicArc)\
ON_ENTITY(IfcAlignment2DVertical)\
ON_ENTITY(IfcAlignment2DVerticalSegment)\
ON_ENTITY(IfcAlignmentCurve)\
ON_ENTITY(IfcAngularDimension)\
ON_ENTITY(IfcAnnotation)\
ON_ENTITY(IfcAnnotationCurveOccurrence)\
ON_ENTITY(IfcAnnotationFillArea)\
ON_ENTITY(IfcAnnotationFillAreaOccurrence)\
ON_ENTITY(IfcAnnotationOccurrence)\
ON_ENTITY(IfcAnnotationSurface)\
ON_ENTITY(IfcAnnotationSurfaceOccurrence)\
ON_ENTITY(IfcAnnotationSymbolOccurrence)\
ON_ENTITY(IfcAnnotationTextOccurrence)\
ON_ENTITY(IfcApplication)\
ON_ENTITY(IfcAppliedValue)\
ON_ENTITY(IfcAppliedValueRelationship)\
ON_ENTITY(IfcApproval)\
ON_ENTITY(IfcApprovalActorRelationship)\
ON_ENTITY(IfcApprovalPropertyRelationship)\
ON_ENTITY(IfcApprovalRelationship)\
ON_ENTITY(IfcArbitraryClosedProfileDef)\
ON_ENTITY(IfcArbitraryOpenProfileDef)\
ON_ENTITY(IfcArbitraryProfileDefWithVoids)\
ON_ENTITY(IfcAsset)\
ON_ENTITY(IfcAsymmetricIShapeProfileDef)\
ON_ENTITY(IfcAudioVisualAppliance)\
ON_ENTITY(IfcAudioVisualApplianceType)\
ON_ENTITY(IfcAxis1Placement)\
ON_ENTITY(IfcAxis2Placement2D)\
ON_ENTITY(IfcAxis2Placement3D)\
ON_ENTITY(IfcBSplineCurve)\
ON_ENTITY(IfcBSplineCurveWithKnots)\
ON_ENTITY(IfcBSplineSurface)\
ON_ENTITY(IfcBSplineSurfaceWithKnots)\
ON_ENTITY(IfcBeam)\
ON_ENTITY(IfcBeamStandardCase)\
ON_ENTITY(IfcBeamType)\
ON_ENTITY(IfcBezierCurve)\
ON_ENTITY(IfcBlobTexture)\
ON_ENTITY(IfcBlock)\
ON_ENTITY(IfcBoiler)\
ON_ENTITY(IfcBoilerType)\
ON_ENTITY(IfcBooleanClippingResult)\
ON_ENTITY(IfcBooleanResult)\
ON_ENTITY(IfcBoundaryCondition)\
ON_ENTITY(IfcBoundaryCurve)\
ON_ENTITY(IfcBoundaryEdgeCondition)\
ON_ENTITY(IfcBoundaryFaceCondition)\
ON_ENTITY(IfcBoundaryNodeCondition)\
ON_ENTITY(IfcBoundaryNodeConditionWarping)\
ON_ENTITY(IfcBoundedCurve)\
ON_ENTITY(IfcBoundedSurface)\
ON_ENTITY(IfcBoundingBox)\
ON_ENTITY(IfcBoxedHalfSpace)\
ON_ENTITY(IfcBuilding)\
ON_ENTITY(IfcBuildingElement)\
ON_ENTITY(IfcBuildingElementComponent)\
ON_ENTITY(IfcBuildingElementPart)\
ON_ENTITY(IfcBuildingElementPartType)\
ON_ENTITY(IfcBuildingElementProxy)\
ON_ENTITY(IfcBuildingElementProxyType)\
ON_ENTITY(IfcBuildingElementType)\
ON_ENTITY(IfcBuildingStorey)\
ON_ENTITY(IfcBuildingSystem)\
ON_ENTITY(IfcBurner)\
ON_ENTITY(IfcBurnerType)\
ON_ENTITY(IfcCShapeProfileDef)\
ON_ENTITY(IfcCableCarrierFitting)\
ON_ENTITY(IfcCableCarrierFittingType)\
ON_ENTITY(IfcCableCarrierSegment)\
ON_ENTITY(IfcCableCarrierSegmentType)\
ON_ENTITY(IfcCableFitting)\
ON_ENTITY(IfcCableFittingType)\
ON_ENTITY(IfcCableSegment)\
ON_ENTITY(IfcCableSegmentType)\
ON_ENTITY(IfcCalendarDate)\
ON_ENTITY(IfcCartesianPoint)\
ON_ENTITY(IfcCartesianPointList)\
ON_ENTITY(IfcCartesianPointList2D)\
ON_ENTITY(IfcCartesianPointList3D)\
ON_ENTITY(IfcCartesianTransformationOperator)\
ON_ENTITY(IfcCartesianTransformationOperator2D)\
ON_ENTITY(IfcCartesianTransformationOperator2DnonUniform)\
ON_ENTITY(IfcCartesianTransformationOperator3D)\
ON_ENTITY(IfcCartesianTransformationOperator3DnonUniform)\
ON_ENTITY(IfcCenterLineProfileDef)\
ON_ENTITY(IfcChamferEdgeFeature)\
ON_ENTITY(IfcChiller)\
ON_ENTITY(IfcChillerType)\
ON_ENTITY(IfcChimney)\
ON_ENTITY(IfcChimneyType)\
ON_ENTITY(IfcCircle)\
ON_ENTITY(IfcCircleHollowProfileDef)\
ON_ENTITY(IfcCircleProfileDef)\
ON_ENTITY(IfcCircularArcSegment2D)\
ON_ENTITY(IfcCivilElement)\
ON_ENTITY(IfcCivilElementType)\
ON_ENTITY(IfcClassification)\
ON_ENTITY(IfcClassificationItem)\
ON_ENTITY(IfcClassificationItemRelationship)\
ON_ENTITY(IfcClassificationNotation)\
ON_ENTITY(IfcClassificationNotationFacet)\
ON_ENTITY(IfcClassificationReference)\
ON_ENTITY(IfcClosedShell)\
ON_ENTITY(IfcCoil)\
ON_ENTITY(IfcCoilType)\
ON_ENTITY(IfcColourRgb)\
ON_ENTITY(IfcColourRgbList)\
ON_ENTITY(IfcColourSpecification)\
ON_ENTITY(IfcColumn)\
ON_ENTITY(IfcColumnStandardCase)\
ON_ENTITY(IfcColumnType)\
ON_ENTITY(IfcCommunicationsAppliance)\
ON_ENTITY(IfcCommunicationsApplianceType)\
ON_ENTITY(IfcComplexProperty)\
ON_ENTITY(IfcComplexPropertyTemplate)\
ON_ENTITY(IfcCompositeCurve)\
ON_ENTITY(IfcCompositeCurveOnSurface)\
ON_ENTITY(IfcCompositeCurveSegment)\
ON_ENTITY(IfcCompositeProfileDef)\
ON_ENTITY(IfcCompressor)\
ON_ENTITY(IfcCompressorType)\
ON_ENTITY(IfcCondenser)\
ON_ENTITY(IfcCondenserType)\
ON_ENTITY(IfcCondition)\
ON_ENTITY(IfcConditionCriterion)\
ON_ENTITY(IfcConic)\
ON_ENTITY(IfcConnectedFaceSet)\
ON_ENTITY(IfcConnectionCurveGeometry)\
ON_ENTITY(IfcConnectionGeometry)\
ON_ENTITY(IfcConnectionPointEccentricity)\
ON_ENTITY(IfcConnectionPointGeometry)\
ON_ENTITY(IfcConnectionPortGeometry)\
ON_ENTITY(IfcConnectionSurfaceGeometry)\
ON_ENTITY(IfcConnectionVolumeGeometry)\
ON_ENTITY(IfcConstraint)\
ON_ENTITY(IfcConstraintAggregationRelationship)\
ON_ENTITY(IfcConstraintClassificationRelationship)\
ON_ENTITY(IfcConstraintRelationship)\
ON_ENTITY(IfcConstructionEquipmentResource)\
ON_ENTITY(IfcConstructionEquipmentResourceType)\
ON_ENTITY(IfcConstructionMaterialResource)\
ON_ENTITY(IfcConstructionMaterialResourceType)\
ON_ENTITY(IfcConstructionProductResource)\
ON_ENTITY(IfcConstructionProductResourceType)\
ON_ENTITY(IfcConstructionResource)\
ON_ENTITY(IfcConstructionResourceType)\
ON_ENTITY(IfcContext)\
ON_ENTITY(IfcContextDependentUnit)\
ON_ENTITY(IfcControl)\
ON_ENTITY(IfcController)\
ON_ENTITY(IfcControllerType)\
ON_ENTITY(IfcConversionBasedUnit)\
ON_ENTITY(IfcConversionBasedUnitWithOffset)\
ON_ENTITY(IfcCooledBeam)\
ON_ENTITY(IfcCooledBeamType)\
ON_ENTITY(IfcCoolingTower)\
ON_ENTITY(IfcCoolingTowerType)\
ON_ENTITY(IfcCoordinateOperation)\
ON_ENTITY(IfcCoordinateReferenceSystem)\
ON_ENTITY(IfcCoordinatedUniversalTimeOffset)\
ON_ENTITY(IfcCostItem)\
ON_ENTITY(IfcCostSchedule)\
ON_ENTITY(IfcCostValue)\
ON_ENTITY(IfcCovering)\
ON_ENTITY(IfcCoveringType)\
ON_ENTITY(IfcCraneRailAShapeProfileDef)\
ON_ENTITY(IfcCraneRailFShapeProfileDef)\
ON_ENTITY(IfcCrewResource)\
ON_ENTITY(IfcCrewResourceType)\
ON_ENTITY(IfcCsgPrimitive3D)\
ON_ENTITY(IfcCsgSolid)\
ON_ENTITY(IfcCurrencyRelationship)\
ON_ENTITY(IfcCurtainWall)\
ON_ENTITY(IfcCurtainWallType)\
ON_ENTITY(IfcCurve)\
ON_ENTITY(IfcCurveBoundedPlane)\
ON_ENTITY(IfcCurveBoundedSurface)\
ON_ENTITY(IfcCurveSegment2D)\
ON_ENTITY(IfcCurveStyle)\
ON_ENTITY(IfcCurveStyleFont)\
ON_ENTITY(IfcCurveStyleFontAndScaling)\
ON_ENTITY(IfcCurveStyleFontPattern)\
ON_ENTITY(IfcCylindricalSurface)\
ON_ENTITY(IfcDamper)\
ON_ENTITY(IfcDamperType)\
ON_ENTITY(IfcDateAndTime)\
ON_ENTITY(IfcDefinedSymbol)\
ON_ENTITY(IfcDerivedProfileDef)\
ON_ENTITY(IfcDerivedUnit)\
ON_ENTITY(IfcDerivedUnitElement)\
ON_ENTITY(IfcDiameterDimension)\
ON_ENTITY(IfcDimensionCalloutRelationship)\
ON_ENTITY(IfcDimensionCurve)\
ON_ENTITY(IfcDimensionCurveDirectedCallout)\
ON_ENTITY(IfcDimensionCurveTerminator)\
ON_ENTITY(IfcDimensionPair)\
ON_ENTITY(IfcDimensionalExponents)\
ON_ENTITY(IfcDirection)\
ON_ENTITY(IfcDiscreteAccessory)\
ON_ENTITY(IfcDiscreteAccessoryType)\
ON_ENTITY(IfcDistanceExpression)\
ON_ENTITY(IfcDistributionChamberElement)\
ON_ENTITY(IfcDistributionChamberElementType)\
ON_ENTITY(IfcDistributionCircuit)\
ON_ENTITY(IfcDistributionControlElement)\
ON_ENTITY(IfcDistributionControlElementType)\
ON_ENTITY(IfcDistributionElement)\
ON_ENTITY(IfcDistributionElementType)\
ON_ENTITY(IfcDistributionFlowElement)\
ON_ENTITY(IfcDistributionFlowElementType)\
ON_ENTITY(IfcDistributionPort)\
ON_ENTITY(IfcDistributionSystem)\
ON_ENTITY(IfcDocumentElectronicFormat)\
ON_ENTITY(IfcDocumentInformation)\
ON_ENTITY(IfcDocumentInformationRelationship)\
ON_ENTITY(IfcDocumentReference)\
ON_ENTITY(IfcDoor)\
ON_ENTITY(IfcDoorLiningProperties)\
ON_ENTITY(IfcDoorPanelProperties)\
ON_ENTITY(IfcDoorStandardCase)\
ON_ENTITY(IfcDoorStyle)\
ON_ENTITY(IfcDoorType)\
ON_ENTITY(IfcDraughtingCallout)\
ON_ENTITY(IfcDraughtingCalloutRelationship)\
ON_ENTITY(IfcDraughtingPreDefinedColour)\
ON_ENTITY(IfcDraughtingPreDefinedCurveFont)\
ON_ENTITY(IfcDraughtingPreDefinedTextFont)\
ON_ENTITY(IfcDuctFitting)\
ON_ENTITY(IfcDuctFittingType)\
ON_ENTITY(IfcDuctSegment)\
ON_ENTITY(IfcDuctSegmentType)\
ON_ENTITY(IfcDuctSilencer)\
ON_ENTITY(IfcDuctSilencerType)\
ON_ENTITY(IfcEdge)\
ON_ENTITY(IfcEdgeCurve)\
ON_ENTITY(IfcEdgeFeature)\
ON_ENTITY(IfcEdgeLoop)\
ON_ENTITY(IfcElectricAppliance)\
ON_ENTITY(IfcElectricApplianceType)\
ON_ENTITY(IfcElectricDistributionBoard)\
ON_ENTITY(IfcElectricDistributionBoardType)\
ON_ENTITY(IfcElectricDistributionPoint)\
ON_ENTITY(IfcElectricFlowStorageDevice)\
ON_ENTITY(IfcElectricFlowStorageDeviceType)\
ON_ENTITY(IfcElectricGenerator)\
ON_ENTITY(IfcElectricGeneratorType)\
ON_ENTITY(IfcElectricHeaterType)\
ON_ENTITY(IfcElectricMotor)\
ON_ENTITY(IfcElectricMotorType)\
ON_ENTITY(IfcElectricTimeControl)\
ON_ENTITY(IfcElectricTimeControlType)\
ON_ENTITY(IfcElectricalBaseProperties)\
ON_ENTITY(IfcElectricalCircuit)\
ON_ENTITY(IfcElectricalElement)\
ON_ENTITY(IfcElement)\
ON_ENTITY(IfcElementAssembly)\
ON_ENTITY(IfcElementAssemblyType)\
ON_ENTITY(IfcElementComponent)\
ON_ENTITY(IfcElementComponentType)\
ON_ENTITY(IfcElementQuantity)\
ON_ENTITY(IfcElementType)\
ON_ENTITY(IfcElementarySurface)\
ON_ENTITY(IfcEllipse)\
ON_ENTITY(IfcEllipseProfileDef)\
ON_ENTITY(IfcEnergyConversionDevice)\
ON_ENTITY(IfcEnergyConversionDeviceType)\
ON_ENTITY(IfcEnergyProperties)\
ON_ENTITY(IfcEngine)\
ON_ENTITY(IfcEngineType)\
ON_ENTITY(IfcEnvironmentalImpactValue)\
ON_ENTITY(IfcEquipmentElement)\
ON_ENTITY(IfcEquipmentStandard)\
ON_ENTITY(IfcEvaporativeCooler)\
ON_ENTITY(IfcEvaporativeCoolerType)\
ON_ENTITY(IfcEvaporator)\
ON_ENTITY(IfcEvaporatorType)\
ON_ENTITY(IfcEvent)\
ON_ENTITY(IfcEventTime)\
ON_ENTITY(IfcEventType)\
ON_ENTITY(IfcExtendedMaterialProperties)\
ON_ENTITY(IfcExtendedProperties)\
ON_ENTITY(IfcExternalInformation)\
ON_ENTITY(IfcExternalReference)\
ON_ENTITY(IfcExternalReferenceRelationship)\
ON_ENTITY(IfcExternalSpatialElement)\
ON_ENTITY(IfcExternalSpatialStructureElement)\
ON_ENTITY(IfcExternallyDefinedHatchStyle)\
ON_ENTITY(IfcExternallyDefinedSurfaceStyle)\
ON_ENTITY(IfcExternallyDefinedSymbol)\
ON_ENTITY(IfcExternallyDefinedTextFont)\
ON_ENTITY(IfcExtrudedAreaSolid)\
ON_ENTITY(IfcExtrudedAreaSolidTapered)\
ON_ENTITY(IfcFace)\
ON_ENTITY(IfcFaceBasedSurfaceModel)\
ON_ENTITY(IfcFaceBound)\
ON_ENTITY(IfcFaceOuterBound)\
ON_ENTITY(IfcFaceSurface)\
ON_ENTITY(IfcFacetedBrep)\
ON_ENTITY(IfcFacetedBrepWithVoids)\
ON_ENTITY(IfcFailureConnectionCondition)\
ON_ENTITY(IfcFan)\
ON_ENTITY(IfcFanType)\
ON_ENTITY(IfcFastener)\
ON_ENTITY(IfcFastenerType)\
ON_ENTITY(IfcFeatureElement)\
ON_ENTITY(IfcFeatureElementAddition)\
ON_ENTITY(IfcFeatureElementSubtraction)\
ON_ENTITY(IfcFillAreaStyle)\
ON_ENTITY(IfcFillAreaStyleHatching)\
ON_ENTITY(IfcFillAreaStyleTileSymbolWithStyle)\
ON_ENTITY(IfcFillAreaStyleTiles)\
ON_ENTITY(IfcFilter)\
ON_ENTITY(IfcFilterType)\
ON_ENTITY(IfcFireSuppressionTerminal)\
ON_ENTITY(IfcFireSuppressionTerminalType)\
ON_ENTITY(IfcFixedReferenceSweptAreaSolid)\
ON_ENTITY(IfcFlowController)\
ON_ENTITY(IfcFlowControllerType)\
ON_ENTITY(IfcFlowFitting)\
ON_ENTITY(IfcFlowFittingType)\
ON_ENTITY(IfcFlowInstrument)\
ON_ENTITY(IfcFlowInstrumentType)\
ON_ENTITY(IfcFlowMeter)\
ON_ENTITY(IfcFlowMeterType)\
ON_ENTITY(IfcFlowMovingDevice)\
ON_ENTITY(IfcFlowMovingDeviceType)\
ON_ENTITY(IfcFlowSegment)\
ON_ENTITY(IfcFlowSegmentType)\
ON_ENTITY(IfcFlowStorageDevice)\
ON_ENTITY(IfcFlowStorageDeviceType)\
ON_ENTITY(IfcFlowTerminal)\
ON_ENTITY(IfcFlowTerminalType)\
ON_ENTITY(IfcFlowTreatmentDevice)\
ON_ENTITY(IfcFlowTreatmentDeviceType)\
ON_ENTITY(IfcFluidFlowProperties)\
ON_ENTITY(IfcFooting)\
ON_ENTITY(IfcFootingType)\
ON_ENTITY(IfcFuelProperties)\
ON_ENTITY(IfcFurnishingElement)\
ON_ENTITY(IfcFurnishingElementType)\
ON_ENTITY(IfcFurniture)\
ON_ENTITY(IfcFurnitureStandard)\
ON_ENTITY(IfcFurnitureType)\
ON_ENTITY(IfcGasTerminalType)\
ON_ENTITY(IfcGeneralMaterialProperties)\
ON_ENTITY(IfcGeneralProfileProperties)\
ON_ENTITY(IfcGeographicElement)\
ON_ENTITY(IfcGeographicElementType)\
ON_ENTITY(IfcGeometricCurveSet)\
ON_ENTITY(IfcGeometricRepresentationContext)\
ON_ENTITY(IfcGeometricRepresentationItem)\
ON_ENTITY(IfcGeometricRepresentationSubContext)\
ON_ENTITY(IfcGeometricSet)\
ON_ENTITY(IfcGrid)\
ON_ENTITY(IfcGridAxis)\
ON_ENTITY(IfcGridPlacement)\
ON_ENTITY(IfcGroup)\
ON_ENTITY(IfcHalfSpaceSolid)\
ON_ENTITY(IfcHeatExchanger)\
ON_ENTITY(IfcHeatExchangerType)\
ON_ENTITY(IfcHumidifier)\
ON_ENTITY(IfcHumidifierType)\
ON_ENTITY(IfcHygroscopicMaterialProperties)\
ON_ENTITY(IfcIShapeProfileDef)\
ON_ENTITY(IfcImageTexture)\
ON_ENTITY(IfcIndexedColourMap)\
ON_ENTITY(IfcIndexedPolyCurve)\
ON_ENTITY(IfcIndexedPolygonalFace)\
ON_ENTITY(IfcIndexedPolygonalFaceWithVoids)\
ON_ENTITY(IfcIndexedTextureMap)\
ON_ENTITY(IfcIndexedTriangleTextureMap)\
ON_ENTITY(IfcInterceptor)\
ON_ENTITY(IfcInterceptorType)\
ON_ENTITY(IfcIntersectionCurve)\
ON_ENTITY(IfcInventory)\
ON_ENTITY(IfcIrregularTimeSeries)\
ON_ENTITY(IfcIrregularTimeSeriesValue)\
ON_ENTITY(IfcJunctionBox)\
ON_ENTITY(IfcJunctionBoxType)\
ON_ENTITY(IfcLShapeProfileDef)\
ON_ENTITY(IfcLaborResource)\
ON_ENTITY(IfcLaborResourceType)\
ON_ENTITY(IfcLagTime)\
ON_ENTITY(IfcLamp)\
ON_ENTITY(IfcLampType)\
ON_ENTITY(IfcLibraryInformation)\
ON_ENTITY(IfcLibraryReference)\
ON_ENTITY(IfcLightDistributionData)\
ON_ENTITY(IfcLightFixture)\
ON_ENTITY(IfcLightFixtureType)\
ON_ENTITY(IfcLightIntensityDistribution)\
ON_ENTITY(IfcLightSource)\
ON_ENTITY(IfcLightSourceAmbient)\
ON_ENTITY(IfcLightSourceDirectional)\
ON_ENTITY(IfcLightSourceGoniometric)\
ON_ENTITY(IfcLightSourcePositional)\
ON_ENTITY(IfcLightSourceSpot)\
ON_ENTITY(IfcLine)\
ON_ENTITY(IfcLineSegment2D)\
ON_ENTITY(IfcLinearDimension)\
ON_ENTITY(IfcLinearPlacement)\
ON_ENTITY(IfcLinearPositioningElement)\
ON_ENTITY(IfcLocalPlacement)\
ON_ENTITY(IfcLocalTime)\
ON_ENTITY(IfcLoop)\
ON_ENTITY(IfcManifoldSolidBrep)\
ON_ENTITY(IfcMapConversion)\
ON_ENTITY(IfcMappedItem)\
ON_ENTITY(IfcMaterial)\
ON_ENTITY(IfcMaterialClassificationRelationship)\
ON_ENTITY(IfcMaterialConstituent)\
ON_ENTITY(IfcMaterialConstituentSet)\
ON_ENTITY(IfcMaterialDefinition)\
ON_ENTITY(IfcMaterialDefinitionRepresentation)\
ON_ENTITY(IfcMaterialLayer)\
ON_ENTITY(IfcMaterialLayerSet)\
ON_ENTITY(IfcMaterialLayerSetUsage)\
ON_ENTITY(IfcMaterialLayerWithOffsets)\
ON_ENTITY(IfcMaterialList)\
ON_ENTITY(IfcMaterialProfile)\
ON_ENTITY(IfcMaterialProfileSet)\
ON_ENTITY(IfcMaterialProfileSetUsage)\
ON_ENTITY(IfcMaterialProfileSetUsageTapering)\
ON_ENTITY(IfcMaterialProfileWithOffsets)\
ON_ENTITY(IfcMaterialProperties)\
ON_ENTITY(IfcMaterialRelationship)\
ON_ENTITY(IfcMaterialUsageDefinition)\
ON_ENTITY(IfcMeasureWithUnit)\
ON_ENTITY(IfcMechanicalConcreteMaterialProperties)\
ON_ENTITY(IfcMechanicalFastener)\
ON_ENTITY(IfcMechanicalFastenerType)\
ON_ENTITY(IfcMechanicalMaterialProperties)\
ON_ENTITY(IfcMechanicalSteelMaterialProperties)\
ON_ENTITY(IfcMedicalDevice)\
ON_ENTITY(IfcMedicalDeviceType)\
ON_ENTITY(IfcMember)\
ON_ENTITY(IfcMemberStandardCase)\
ON_ENTITY(IfcMemberType)\
ON_ENTITY(IfcMetric)\
ON_ENTITY(IfcMirroredProfileDef)\
ON_ENTITY(IfcMonetaryUnit)\
ON_ENTITY(IfcMotorConnection)\
ON_ENTITY(IfcMotorConnectionType)\
ON_ENTITY(IfcMove)\
ON_ENTITY(IfcNamedUnit)\
ON_ENTITY(IfcObject)\
ON_ENTITY(IfcObjectDefinition)\
ON_ENTITY(IfcObjectPlacement)\
ON_ENTITY(IfcObjective)\
ON_ENTITY(IfcOccupant)\
ON_ENTITY(IfcOffsetCurve)\
ON_ENTITY(IfcOffsetCurve2D)\
ON_ENTITY(IfcOffsetCurve3D)\
ON_ENTITY(IfcOffsetCurveByDistances)\
ON_ENTITY(IfcOneDirectionRepeatFactor)\
ON_ENTITY(IfcOpenShell)\
ON_ENTITY(IfcOpeningElement)\
ON_ENTITY(IfcOpeningStandardCase)\
ON_ENTITY(IfcOpticalMaterialProperties)\
ON_ENTITY(IfcOrderAction)\
ON_ENTITY(IfcOrganization)\
ON_ENTITY(IfcOrganizationRelationship)\
ON_ENTITY(IfcOrientationExpression)\
ON_ENTITY(IfcOrientedEdge)\
ON_ENTITY(IfcOuterBoundaryCurve)\
ON_ENTITY(IfcOutlet)\
ON_ENTITY(IfcOutletType)\
ON_ENTITY(IfcOwnerHistory)\
ON_ENTITY(IfcParameterizedProfileDef)\
ON_ENTITY(IfcPath)\
ON_ENTITY(IfcPcurve)\
ON_ENTITY(IfcPerformanceHistory)\
ON_ENTITY(IfcPermeableCoveringProperties)\
ON_ENTITY(IfcPermit)\
ON_ENTITY(IfcPerson)\
ON_ENTITY(IfcPersonAndOrganization)\
ON_ENTITY(IfcPhysicalComplexQuantity)\
ON_ENTITY(IfcPhysicalQuantity)\
ON_ENTITY(IfcPhysicalSimpleQuantity)\
ON_ENTITY(IfcPile)\
ON_ENTITY(IfcPileType)\
ON_ENTITY(IfcPipeFitting)\
ON_ENTITY(IfcPipeFittingType)\
ON_ENTITY(IfcPipeSegment)\
ON_ENTITY(IfcPipeSegmentType)\
ON_ENTITY(IfcPixelTexture)\
ON_ENTITY(IfcPlacement)\
ON_ENTITY(IfcPlanarBox)\
ON_ENTITY(IfcPlanarExtent)\
ON_ENTITY(IfcPlane)\
ON_ENTITY(IfcPlate)\
ON_ENTITY(IfcPlateStandardCase)\
ON_ENTITY(IfcPlateType)\
ON_ENTITY(IfcPoint)\
ON_ENTITY(IfcPointOnCurve)\
ON_ENTITY(IfcPointOnSurface)\
ON_ENTITY(IfcPolyLoop)\
ON_ENTITY(IfcPolygonalBoundedHalfSpace)\
ON_ENTITY(IfcPolygonalFaceSet)\
ON_ENTITY(IfcPolyline)\
ON_ENTITY(IfcPort)\
ON_ENTITY(IfcPositioningElement)\
ON_ENTITY(IfcPostalAddress)\
ON_ENTITY(IfcPreDefinedColour)\
ON_ENTITY(IfcPreDefinedCurveFont)\
ON_ENTITY(IfcPreDefinedDimensionSymbol)\
ON_ENTITY(IfcPreDefinedItem)\
ON_ENTITY(IfcPreDefinedPointMarkerSymbol)\
ON_ENTITY(IfcPreDefinedProperties)\
ON_ENTITY(IfcPreDefinedPropertySet)\
ON_ENTITY(IfcPreDefinedSymbol)\
ON_ENTITY(IfcPreDefinedTerminatorSymbol)\
ON_ENTITY(IfcPreDefinedTextFont)\
ON_ENTITY(IfcPresentationItem)\
ON_ENTITY(IfcPresentationLayerAssignment)\
ON_ENTITY(IfcPresentationLayerWithStyle)\
ON_ENTITY(IfcPresentationStyle)\
ON_ENTITY(IfcPresentationStyleAssignment)\
ON_ENTITY(IfcProcedure)\
ON_ENTITY(IfcProcedureType)\
ON_ENTITY(IfcProcess)\
ON_ENTITY(IfcProduct)\
ON_ENTITY(IfcProductDefinitionShape)\
ON_ENTITY(IfcProductRepresentation)\
ON_ENTITY(IfcProductsOfCombustionProperties)\
ON_ENTITY(IfcProfileDef)\
ON_ENTITY(IfcProfileProperties)\
ON_ENTITY(IfcProject)\
ON_ENTITY(IfcProjectLibrary)\
ON_ENTITY(IfcProjectOrder)\
ON_ENTITY(IfcProjectOrderRecord)\
ON_ENTITY(IfcProjectedCRS)\
ON_ENTITY(IfcProjectionCurve)\
ON_ENTITY(IfcProjectionElement)\
ON_ENTITY(IfcProperty)\
ON_ENTITY(IfcPropertyAbstraction)\
ON_ENTITY(IfcPropertyBoundedValue)\
ON_ENTITY(IfcPropertyConstraintRelationship)\
ON_ENTITY(IfcPropertyDefinition)\
ON_ENTITY(IfcPropertyDependencyRelationship)\
ON_ENTITY(IfcPropertyEnumeratedValue)\
ON_ENTITY(IfcPropertyEnumeration)\
ON_ENTITY(IfcPropertyListValue)\
ON_ENTITY(IfcPropertyReferenceValue)\
ON_ENTITY(IfcPropertySet)\
ON_ENTITY(IfcPropertySetDefinition)\
ON_ENTITY(IfcPropertySetTemplate)\
ON_ENTITY(IfcPropertySingleValue)\
ON_ENTITY(IfcPropertyTableValue)\
ON_ENTITY(IfcPropertyTemplate)\
ON_ENTITY(IfcPropertyTemplateDefinition)\
ON_ENTITY(IfcProtectiveDevice)\
ON_ENTITY(IfcProtectiveDeviceTrippingUnit)\
ON_ENTITY(IfcProtectiveDeviceTrippingUnitType)\
ON_ENTITY(IfcProtectiveDeviceType)\
ON_ENTITY(IfcProxy)\
ON_ENTITY(IfcPump)\
ON_ENTITY(IfcPumpType)\
ON_ENTITY(IfcQuantityArea)\
ON_ENTITY(IfcQuantityCount)\
ON_ENTITY(IfcQuantityLength)\
ON_ENTITY(IfcQuantitySet)\
ON_ENTITY(IfcQuantityTime)\
ON_ENTITY(IfcQuantityVolume)\
ON_ENTITY(IfcQuantityWeight)\
ON_ENTITY(IfcRadiusDimension)\
ON_ENTITY(IfcRailing)\
ON_ENTITY(IfcRailingType)\
ON_ENTITY(IfcRamp)\
ON_ENTITY(IfcRampFlight)\
ON_ENTITY(IfcRampFlightType)\
ON_ENTITY(IfcRampType)\
ON_ENTITY(IfcRationalBSplineCurveWithKnots)\
ON_ENTITY(IfcRationalBSplineSurfaceWithKnots)\
ON_ENTITY(IfcRationalBezierCurve)\
ON_ENTITY(IfcRectangleHollowProfileDef)\
ON_ENTITY(IfcRectangleProfileDef)\
ON_ENTITY(IfcRectangularPyramid)\
ON_ENTITY(IfcRectangularTrimmedSurface)\
ON_ENTITY(IfcRecurrencePattern)\
ON_ENTITY(IfcReference)\
ON_ENTITY(IfcReferencesValueDocument)\
ON_ENTITY(IfcReferent)\
ON_ENTITY(IfcRegularTimeSeries)\
ON_ENTITY(IfcReinforcementBarProperties)\
ON_ENTITY(IfcReinforcementDefinitionProperties)\
ON_ENTITY(IfcReinforcingBar)\
ON_ENTITY(IfcReinforcingBarType)\
ON_ENTITY(IfcReinforcingElement)\
ON_ENTITY(IfcReinforcingElementType)\
ON_ENTITY(IfcReinforcingMesh)\
ON_ENTITY(IfcReinforcingMeshType)\
ON_ENTITY(IfcRelAggregates)\
ON_ENTITY(IfcRelAssigns)\
ON_ENTITY(IfcRelAssignsTasks)\
ON_ENTITY(IfcRelAssignsToActor)\
ON_ENTITY(IfcRelAssignsToControl)\
ON_ENTITY(IfcRelAssignsToGroup)\
ON_ENTITY(IfcRelAssignsToGroupByFactor)\
ON_ENTITY(IfcRelAssignsToProcess)\
ON_ENTITY(IfcRelAssignsToProduct)\
ON_ENTITY(IfcRelAssignsToProjectOrder)\
ON_ENTITY(IfcRelAssignsToResource)\
ON_ENTITY(IfcRelAssociates)\
ON_ENTITY(IfcRelAssociatesAppliedValue)\
ON_ENTITY(IfcRelAssociatesApproval)\
ON_ENTITY(IfcRelAssociatesClassification)\
ON_ENTITY(IfcRelAssociatesConstraint)\
ON_ENTITY(IfcRelAssociatesDocument)\
ON_ENTITY(IfcRelAssociatesLibrary)\
ON_ENTITY(IfcRelAssociatesMaterial)\
ON_ENTITY(IfcRelAssociatesProfileProperties)\
ON_ENTITY(IfcRelConnects)\
ON_ENTITY(IfcRelConnectsElements)\
ON_ENTITY(IfcRelConnectsPathElements)\
ON_ENTITY(IfcRelConnectsPortToElement)\
ON_ENTITY(IfcRelConnectsPorts)\
ON_ENTITY(IfcRelConnectsStructuralActivity)\
ON_ENTITY(IfcRelConnectsStructuralElement)\
ON_ENTITY(IfcRelConnectsStructuralMember)\
ON_ENTITY(IfcRelConnectsWithEccentricity)\
ON_ENTITY(IfcRelConnectsWithRealizingElements)\
ON_ENTITY(IfcRelContainedInSpatialStructure)\
ON_ENTITY(IfcRelCoversBldgElements)\
ON_ENTITY(IfcRelCoversSpaces)\
ON_ENTITY(IfcRelDeclares)\
ON_ENTITY(IfcRelDecomposes)\
ON_ENTITY(IfcRelDefines)\
ON_ENTITY(IfcRelDefinesByObject)\
ON_ENTITY(IfcRelDefinesByProperties)\
ON_ENTITY(IfcRelDefinesByTemplate)\
ON_ENTITY(IfcRelDefinesByType)\
ON_ENTITY(IfcRelFillsElement)\
ON_ENTITY(IfcRelFlowControlElements)\
ON_ENTITY(IfcRelInteractionRequirements)\
ON_ENTITY(IfcRelInterferesElements)\
ON_ENTITY(IfcRelNests)\
ON_ENTITY(IfcRelOccupiesSpaces)\
ON_ENTITY(IfcRelOverridesProperties)\
ON_ENTITY(IfcRelProjectsElement)\
ON_ENTITY(IfcRelReferencedInSpatialStructure)\
ON_ENTITY(IfcRelSchedulesCostItems)\
ON_ENTITY(IfcRelSequence)\
ON_ENTITY(IfcRelServicesBuildings)\
ON_ENTITY(IfcRelSpaceBoundary)\
ON_ENTITY(IfcRelSpaceBoundary1stLevel)\
ON_ENTITY(IfcRelSpaceBoundary2ndLevel)\
ON_ENTITY(IfcRelVoidsElement)\
ON_ENTITY(IfcRelationship)\
ON_ENTITY(IfcRelaxation)\
ON_ENTITY(IfcReparametrisedCompositeCurveSegment)\
ON_ENTITY(IfcRepresentation)\
ON_ENTITY(IfcRepresentationContext)\
ON_ENTITY(IfcRepresentationItem)\
ON_ENTITY(IfcRepresentationMap)\
ON_ENTITY(IfcResource)\
ON_ENTITY(IfcResourceApprovalRelationship)\
ON_ENTITY(IfcResourceConstraintRelationship)\
ON_ENTITY(IfcResourceLevelRelationship)\
ON_ENTITY(IfcResourceTime)\
ON_ENTITY(IfcRevolvedAreaSolid)\
ON_ENTITY(IfcRevolvedAreaSolidTapered)\
ON_ENTITY(IfcRibPlateProfileProperties)\
ON_ENTITY(IfcRightCircularCone)\
ON_ENTITY(IfcRightCircularCylinder)\
ON_ENTITY(IfcRoof)\
ON_ENTITY(IfcRoofType)\
ON_ENTITY(IfcRoot)\
ON_ENTITY(IfcRoundedEdgeFeature)\
ON_ENTITY(IfcRoundedRectangleProfileDef)\
ON_ENTITY(IfcSIUnit)\
ON_ENTITY(IfcSanitaryTerminal)\
ON_ENTITY(IfcSanitaryTerminalType)\
ON_ENTITY(IfcScheduleTimeControl)\
ON_ENTITY(IfcSchedulingTime)\
ON_ENTITY(IfcSeamCurve)\
ON_ENTITY(IfcSectionProperties)\
ON_ENTITY(IfcSectionReinforcementProperties)\
ON_ENTITY(IfcSectionedSolid)\
ON_ENTITY(IfcSectionedSolidHorizontal)\
ON_ENTITY(IfcSectionedSpine)\
ON_ENTITY(IfcSensor)\
ON_ENTITY(IfcSensorType)\
ON_ENTITY(IfcServiceLife)\
ON_ENTITY(IfcServiceLifeFactor)\
ON_ENTITY(IfcShadingDevice)\
ON_ENTITY(IfcShadingDeviceType)\
ON_ENTITY(IfcShapeAspect)\
ON_ENTITY(IfcShapeModel)\
ON_ENTITY(IfcShapeRepresentation)\
ON_ENTITY(IfcShellBasedSurfaceModel)\
ON_ENTITY(IfcSimpleProperty)\
ON_ENTITY(IfcSimplePropertyTemplate)\
ON_ENTITY(IfcSite)\
ON_ENTITY(IfcSlab)\
ON_ENTITY(IfcSlabElementedCase)\
ON_ENTITY(IfcSlabStandardCase)\
ON_ENTITY(IfcSlabType)\
ON_ENTITY(IfcSlippageConnectionCondition)\
ON_ENTITY(IfcSolarDevice)\
ON_ENTITY(IfcSolarDeviceType)\
ON_ENTITY(IfcSolidModel)\
ON_ENTITY(IfcSoundProperties)\
ON_ENTITY(IfcSoundValue)\
ON_ENTITY(IfcSpace)\
ON_ENTITY(IfcSpaceHeater)\
ON_ENTITY(IfcSpaceHeaterType)\
ON_ENTITY(IfcSpaceProgram)\
ON_ENTITY(IfcSpaceThermalLoadProperties)\
ON_ENTITY(IfcSpaceType)\
ON_ENTITY(IfcSpatialElement)\
ON_ENTITY(IfcSpatialElementType)\
ON_ENTITY(IfcSpatialStructureElement)\
ON_ENTITY(IfcSpatialStructureElementType)\
ON_ENTITY(IfcSpatialZone)\
ON_ENTITY(IfcSpatialZoneType)\
ON_ENTITY(IfcSphere)\
ON_ENTITY(IfcSphericalSurface)\
ON_ENTITY(IfcStackTerminal)\
ON_ENTITY(IfcStackTerminalType)\
ON_ENTITY(IfcStair)\
ON_ENTITY(IfcStairFlight)\
ON_ENTITY(IfcStairFlightType)\
ON_ENTITY(IfcStairType)\
ON_ENTITY(IfcStructuralAction)\
ON_ENTITY(IfcStructuralActivity)\
ON_ENTITY(IfcStructuralAnalysisModel)\
ON_ENTITY(IfcStructuralConnection)\
ON_ENTITY(IfcStructuralConnectionCondition)\
ON_ENTITY(IfcStructuralCurveAction)\
ON_ENTITY(IfcStructuralCurveConnection)\
ON_ENTITY(IfcStructuralCurveMember)\
ON_ENTITY(IfcStructuralCurveMemberVarying)\
ON_ENTITY(IfcStructuralCurveReaction)\
ON_ENTITY(IfcStructuralItem)\
ON_ENTITY(IfcStructuralLinearAction)\
ON_ENTITY(IfcStructuralLinearActionVarying)\
ON_ENTITY(IfcStructuralLoad)\
ON_ENTITY(IfcStructuralLoadCase)\
ON_ENTITY(IfcStructuralLoadConfiguration)\
ON_ENTITY(IfcStructuralLoadGroup)\
ON_ENTITY(IfcStructuralLoadLinearForce)\
ON_ENTITY(IfcStructuralLoadOrResult)\
ON_ENTITY(IfcStructuralLoadPlanarForce)\
ON_ENTITY(IfcStructuralLoadSingleDisplacement)\
ON_ENTITY(IfcStructuralLoadSingleDisplacementDistortion)\
ON_ENTITY(IfcStructuralLoadSingleForce)\
ON_ENTITY(IfcStructuralLoadSingleForceWarping)\
ON_ENTITY(IfcStructuralLoadStatic)\
ON_ENTITY(IfcStructuralLoadTemperature)\
ON_ENTITY(IfcStructuralMember)\
ON_ENTITY(IfcStructuralPlanarAction)\
ON_ENTITY(IfcStructuralPlanarActionVarying)\
ON_ENTITY(IfcStructuralPointAction)\
ON_ENTITY(IfcStructuralPointConnection)\
ON_ENTITY(IfcStructuralPointReaction)\
ON_ENTITY(IfcStructuralProfileProperties)\
ON_ENTITY(IfcStructuralReaction)\
ON_ENTITY(IfcStructuralResultGroup)\
ON_ENTITY(IfcStructuralSteelProfileProperties)\
ON_ENTITY(IfcStructuralSurfaceAction)\
ON_ENTITY(IfcStructuralSurfaceConnection)\
ON_ENTITY(IfcStructuralSurfaceMember)\
ON_ENTITY(IfcStructuralSurfaceMemberVarying)\
ON_ENTITY(IfcStructuralSurfaceReaction)\
ON_ENTITY(IfcStructuredDimensionCallout)\
ON_ENTITY(IfcStyleModel)\
ON_ENTITY(IfcStyledItem)\
ON_ENTITY(IfcStyledRepresentation)\
ON_ENTITY(IfcSubContractResource)\
ON_ENTITY(IfcSubContractResourceType)\
ON_ENTITY(IfcSubedge)\
ON_ENTITY(IfcSurface)\
ON_ENTITY(IfcSurfaceCurve)\
ON_ENTITY(IfcSurfaceCurveSweptAreaSolid)\
ON_ENTITY(IfcSurfaceFeature)\
ON_ENTITY(IfcSurfaceOfLinearExtrusion)\
ON_ENTITY(IfcSurfaceOfRevolution)\
ON_ENTITY(IfcSurfaceReinforcementArea)\
ON_ENTITY(IfcSurfaceStyle)\
ON_ENTITY(IfcSurfaceStyleLighting)\
ON_ENTITY(IfcSurfaceStyleRefraction)\
ON_ENTITY(IfcSurfaceStyleRendering)\
ON_ENTITY(IfcSurfaceStyleShading)\
ON_ENTITY(IfcSurfaceStyleWithTextures)\
ON_ENTITY(IfcSurfaceTexture)\
ON_ENTITY(IfcSweptAreaSolid)\
ON_ENTITY(IfcSweptDiskSolid)\
ON_ENTITY(IfcSweptDiskSolidPolygonal)\
ON_ENTITY(IfcSweptSurface)\
ON_ENTITY(IfcSwitchingDevice)\
ON_ENTITY(IfcSwitchingDeviceType)\
ON_ENTITY(IfcSymbolStyle)\
ON_ENTITY(IfcSystem)\
ON_ENTITY(IfcSystemFurnitureElement)\
ON_ENTITY(IfcSystemFurnitureElementType)\
ON_ENTITY(IfcTShapeProfileDef)\
ON_ENTITY(IfcTable)\
ON_ENTITY(IfcTableColumn)\
ON_ENTITY(IfcTableRow)\
ON_ENTITY(IfcTank)\
ON_ENTITY(IfcTankType)\
ON_ENTITY(IfcTask)\
ON_ENTITY(IfcTaskTime)\
ON_ENTITY(IfcTaskTimeRecurring)\
ON_ENTITY(IfcTaskType)\
ON_ENTITY(IfcTelecomAddress)\
ON_ENTITY(IfcTendon)\
ON_ENTITY(IfcTendonAnchor)\
ON_ENTITY(IfcTendonAnchorType)\
ON_ENTITY(IfcTendonType)\
ON_ENTITY(IfcTerminatorSymbol)\
ON_ENTITY(IfcTessellatedFaceSet)\
ON_ENTITY(IfcTessellatedItem)\
ON_ENTITY(IfcTextLiteral)\
ON_ENTITY(IfcTextLiteralWithExtent)\
ON_ENTITY(IfcTextStyle)\
ON_ENTITY(IfcTextStyleFontModel)\
ON_ENTITY(IfcTextStyleForDefinedFont)\
ON_ENTITY(IfcTextStyleTextModel)\
ON_ENTITY(IfcTextStyleWithBoxCharacteristics)\
ON_ENTITY(IfcTextureCoordinate)\
ON_ENTITY(IfcTextureCoordinateGenerator)\
ON_ENTITY(IfcTextureMap)\
ON_ENTITY(IfcTextureVertex)\
ON_ENTITY(IfcTextureVertexList)\
ON_ENTITY(IfcThermalMaterialProperties)\
ON_ENTITY(IfcTimePeriod)\
ON_ENTITY(IfcTimeSeries)\
ON_ENTITY(IfcTimeSeriesReferenceRelationship)\
ON_ENTITY(IfcTimeSeriesSchedule)\
ON_ENTITY(IfcTimeSeriesValue)\
ON_ENTITY(IfcTopologicalRepresentationItem)\
ON_ENTITY(IfcTopologyRepresentation)\
ON_ENTITY(IfcToroidalSurface)\
ON_ENTITY(IfcTransformer)\
ON_ENTITY(IfcTransformerType)\
ON_ENTITY(IfcTransitionCurveSegment2D)\
ON_ENTITY(IfcTransportElement)\
ON_ENTITY(IfcTransportElementType)\
ON_ENTITY(IfcTrapeziumProfileDef)\
ON_ENTITY(IfcTriangulatedFaceSet)\
ON_ENTITY(IfcTriangulatedIrregularNetwork)\
ON_ENTITY(IfcTrimmedCurve)\
ON_ENTITY(IfcTubeBundle)\
ON_ENTITY(IfcTubeBundleType)\
ON_ENTITY(IfcTwoDirectionRepeatFactor)\
ON_ENTITY(IfcTypeObject)\
ON_ENTITY(IfcTypeProcess)\
ON_ENTITY(IfcTypeProduct)\
ON_ENTITY(IfcTypeResource)\
ON_ENTITY(IfcUShapeProfileDef)\
ON_ENTITY(IfcUnitAssignment)\
ON_ENTITY(IfcUnitaryControlElement)\
ON_ENTITY(IfcUnitaryControlElementType)\
ON_ENTITY(IfcUnitaryEquipment)\
ON_ENTITY(IfcUnitaryEquipmentType)\
ON_ENTITY(IfcValve)\
ON_ENTITY(IfcValveType)\
ON_ENTITY(IfcVector)\
ON_ENTITY(IfcVertex)\
ON_ENTITY(IfcVertexBasedTextureMap)\
ON_ENTITY(IfcVertexLoop)\
ON_ENTITY(IfcVertexPoint)\
ON_ENTITY(IfcVibrationIsolator)\
ON_ENTITY(IfcVibrationIsolatorType)\
ON_ENTITY(IfcVirtualElement)\
ON_ENTITY(IfcVirtualGridIntersection)\
ON_ENTITY(IfcVoidingFeature)\
ON_ENTITY(IfcWall)\
ON_ENTITY(IfcWallElementedCase)\
ON_ENTITY(IfcWallStandardCase)\
ON_ENTITY(IfcWallType)\
ON_ENTITY(IfcWasteTerminal)\
ON_ENTITY(IfcWasteTerminalType)\
ON_ENTITY(IfcWaterProperties)\
ON_ENTITY(IfcWindow)\
ON_ENTITY(IfcWindowLiningProperties)\
ON_ENTITY(IfcWindowPanelProperties)\
ON_ENTITY(IfcWindowStandardCase)\
ON_ENTITY(IfcWindowStyle)\
ON_ENTITY(IfcWindowType)\
ON_ENTITY(IfcWorkCalendar)\
ON_ENTITY(IfcWorkControl)\
ON_ENTITY(IfcWorkPlan)\
ON_ENTITY(IfcWorkSchedule)\
ON_ENTITY(IfcWorkTime)\
ON_ENTITY(IfcZShapeProfileDef)\
ON_ENTITY(IfcZone)\

